//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TRUNCATE_ACTION;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JTRUNCATE_ACTION = interface;

  JTRUNCATE_ACTIONClass = interface(JObjectClass)
    ['{35876DFD-F0AA-4DF1-9D18-FF286DA21EF8}']
    function _GetTRUNCATE_ACTION_DO_NOT_TRUNCATE : JTRUNCATE_ACTION; cdecl;     //  A: $19
    function _GetTRUNCATE_ACTION_TRUNCATE : JTRUNCATE_ACTION; cdecl;            //  A: $19
    function _GetTRUNCATE_ACTION_UNSPECIFIED : JTRUNCATE_ACTION; cdecl;         //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property TRUNCATE_ACTION_DO_NOT_TRUNCATE : JTRUNCATE_ACTION read _GetTRUNCATE_ACTION_DO_NOT_TRUNCATE;// Lcom/zebra/rfid/api3/TRUNCATE_ACTION; A: $19
    property TRUNCATE_ACTION_TRUNCATE : JTRUNCATE_ACTION read _GetTRUNCATE_ACTION_TRUNCATE;// Lcom/zebra/rfid/api3/TRUNCATE_ACTION; A: $19
    property TRUNCATE_ACTION_UNSPECIFIED : JTRUNCATE_ACTION read _GetTRUNCATE_ACTION_UNSPECIFIED;// Lcom/zebra/rfid/api3/TRUNCATE_ACTION; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/TRUNCATE_ACTION')]
  JTRUNCATE_ACTION = interface(JObject)
    ['{834BF9BB-6DFC-425C-90C1-8291E4FBD687}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJTRUNCATE_ACTION = class(TJavaGenericImport<JTRUNCATE_ACTIONClass, JTRUNCATE_ACTION>)
  end;

implementation

end.
