//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bf;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.concurrent.BlockingQueue,
  com.zebra.ASCII_SDK.Command_SetStopTrigger,
  com.zebra.ASCII_SDK.Command_SetStartTrigger,
  com.zebra.rfid.api3.m,
  com.zebra.rfid.api3.cl,
  com.zebra.rfid.api3.BATCH_MODE_EVENT,
  com.zebra.rfid.api3.v,
  com.zebra.rfid.api3.OPERATION_END_SUMMARY,
  com.zebra.rfid.api3.POWER_EVENT,
  com.zebra.rfid.api3.BATTERY_EVENT,
  com.zebra.rfid.api3.cp,
  java.util.concurrent.atomic.AtomicBoolean,
  java.util.logging.Logger,
  com.zebra.rfid.api3.RFIDResults,
  com.zebra.rfid.api3.PostFilter,
  com.zebra.rfid.api3.AntennaInfo,
  com.zebra.rfid.api3.TriggerInfo,
  com.zebra.rfid.api3.TagStorageSettings,
  com.zebra.rfid.api3.StartTrigger,
  com.zebra.rfid.api3.StopTrigger,
  com.zebra.rfid.api3.DYNAMIC_POWER_OPTIMIZATION,
  com.zebra.rfid.api3.da,
  com.zebra.rfid.api3.AttributeInfo,
  com.zebra.rfid.api3.SetAttribute,
  com.zebra.rfid.api3.RegulatoryConfig,
  com.zebra.rfid.api3.RegionInfo,
  com.zebra.rfid.api3.Antennas,
  com.zebra.rfid.api3.bc,
  com.zebra.rfid.api3.RFID_EVENT_TYPE,
  com.zebra.rfid.api3.ReaderCapabilities,
  com.zebra.rfid.api3.TagData,
  com.zebra.rfid.api3.n,
  com.zebra.rfid.api3.AccessFilter,
  com.zebra.rfid.api3.ae,
  java.util.logging.Level,
  com.zebra.rfid.api3.TagAccess_Sequence,
  com.zebra.ASCII_SDK.ENUM_MEMORY_BANK,
  com.zebra.ASCII_SDK.Command_Lock,
  com.zebra.rfid.api3.TagAccess_LockAccessParams,
  com.zebra.ASCII_SDK.Command,
  com.zebra.ASCII_SDK.COMMAND_TYPE,
  com.zebra.ASCII_SDK.CONFIG_TYPE,
  com.zebra.ASCII_SDK.ResponseMsg;

type
  Jbf = interface;

  JbfClass = interface(JObjectClass)
    ['{6B3399C3-3325-4D6D-A58E-C441C8E26926}']
    function _Getj : JLogger; cdecl;                                            //  A: $19
    function a(Integerparam0 : Integer; Integerparam1 : Integer; JAttributeInfoparam2 : JAttributeInfo) : JRFIDResults; cdecl; overload;// (IILcom/zebra/rfid/api3/AttributeInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JDYNAMIC_POWER_OPTIMIZATIONparam1 : JDYNAMIC_POWER_OPTIMIZATION) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JHashMapparam1 : JHashMap) : JRFIDResults; cdecl; overload;// (ILjava/util/HashMap;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JLevelparam1 : JLevel) : JRFIDResults; cdecl; overload;// (ILjava/util/logging/Level;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JRegionInfoparam1 : JRegionInfo) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegionInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JRegulatoryConfigparam1 : JRegulatoryConfig) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegulatoryConfig;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JSetAttributeparam1 : JSetAttribute) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/SetAttribute;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStartTriggerparam1 : JStartTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StartTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStopTriggerparam1 : JStopTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StopTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStringparam1 : JString; JStringparam2 : JString; JAntennaInfoparam3 : JAntennaInfo) : JRFIDResults; cdecl; overload;// (ILjava/lang/String;Ljava/lang/String;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JTagDataparam1 : JTagData; Integerparam2 : Integer; booleanparam3 : boolean) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/TagData;IZ)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JTagStorageSettingsparam1 : JTagStorageSettings) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/TagStorageSettings;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; Jvparam1 : Jv) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/v;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; Integerparam2 : Integer) : Integer; cdecl; overload;// (ISI)I A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_Configparam2 : JAntennas_Config; JAntennas_AntennaRfConfigparam3 : JAntennas_AntennaRfConfig; JAntennas_RFModeparam4 : JAntennas_RFMode) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$Config;Lcom/zebra/rfid/api3/Antennas$AntennaRfConfig;Lcom/zebra/rfid/api3/Antennas$RFMode;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_SingulationControlparam2 : JAntennas_SingulationControl) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$SingulationControl;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; Jbcparam2 : Jbc; TJavaArrayIntegerparam3 : TJavaArray<Integer>) : Integer; cdecl; overload;// (ISLcom/zebra/rfid/api3/bc;[I)I A: $1
    function a(Integerparam0 : Integer; TJavaArrayJDYNAMIC_POWER_OPTIMIZATIONparam1 : TJavaArray<JDYNAMIC_POWER_OPTIMIZATION>) : JRFIDResults; cdecl; overload;// (I[Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; TJavaArrayJUNIQUE_TAG_REPORT_SETTINGparam1 : TJavaArray<JUNIQUE_TAG_REPORT_SETTING>) : JRFIDResults; cdecl; overload;// (I[Lcom/zebra/rfid/api3/UNIQUE_TAG_REPORT_SETTING;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; TJavaArrayJclparam1 : TJavaArray<Jcl>; Integerparam2 : Integer; booleanparam3 : boolean; TJavaArrayJTagDataparam4 : TJavaArray<JTagData>) : Integer; cdecl; overload;// (I[Lcom/zebra/rfid/api3/cl;IZ[Lcom/zebra/rfid/api3/TagData;)I A: $1
    function a(Integerparam0 : Integer; booleanparam1 : boolean) : JRFIDResults; cdecl; overload;// (IZ)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JArrayListparam0 : JArrayList) : JRFIDResults; cdecl; overload;  // (Ljava/util/ArrayList;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JRFIDResultsparam0 : JRFIDResults) : JString; cdecl; overload;   // (Lcom/zebra/rfid/api3/RFIDResults;)Ljava/lang/String; A: $1
    function a(JStringparam0 : JString) : JRFIDResults; cdecl; overload;        // (Ljava/lang/String;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JTagStorageSettingsparam0 : JTagStorageSettings) : JRFIDResults; cdecl; overload;// (Lcom/zebra/rfid/api3/TagStorageSettings;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Jdaparam0 : Jda) : JRFIDResults; cdecl; overload;                // (Lcom/zebra/rfid/api3/da;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; Integerparam1 : Integer) : JRFIDResults; cdecl; overload;// (II)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JRegulatoryConfigparam1 : JRegulatoryConfig) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegulatoryConfig;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JStartTriggerparam1 : JStartTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StartTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JStopTriggerparam1 : JStopTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StopTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_Configparam2 : JAntennas_Config; JAntennas_AntennaRfConfigparam3 : JAntennas_AntennaRfConfig; JAntennas_RFModeparam4 : JAntennas_RFMode) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$Config;Lcom/zebra/rfid/api3/Antennas$AntennaRfConfig;Lcom/zebra/rfid/api3/Antennas$RFMode;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_SingulationControlparam2 : JAntennas_SingulationControl) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$SingulationControl;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(JStringparam0 : JString) : JRFIDResults; cdecl; overload;        // (Ljava/lang/String;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function c(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function d(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function e(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function f(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    procedure a ; cdecl; overload;                                              // ()V A: $1
    procedure a(JStringparam0 : JString; JStringparam1 : JString) ; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
    property j : JLogger read _Getj;                                            // Ljava/util/logging/Logger; A: $19
  end;

  [JavaSignature('com/zebra/rfid/api3/bf')]
  Jbf = interface(JObject)
    ['{A5AECD2B-E437-49C7-9F68-C2508DCB1CF6}']
    function a(Integerparam0 : Integer; Integerparam1 : Integer; JAttributeInfoparam2 : JAttributeInfo) : JRFIDResults; cdecl; overload;// (IILcom/zebra/rfid/api3/AttributeInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JDYNAMIC_POWER_OPTIMIZATIONparam1 : JDYNAMIC_POWER_OPTIMIZATION) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JHashMapparam1 : JHashMap) : JRFIDResults; cdecl; overload;// (ILjava/util/HashMap;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JLevelparam1 : JLevel) : JRFIDResults; cdecl; overload;// (ILjava/util/logging/Level;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JRegionInfoparam1 : JRegionInfo) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegionInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JRegulatoryConfigparam1 : JRegulatoryConfig) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegulatoryConfig;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JSetAttributeparam1 : JSetAttribute) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/SetAttribute;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStartTriggerparam1 : JStartTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StartTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStopTriggerparam1 : JStopTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StopTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JStringparam1 : JString; JStringparam2 : JString; JAntennaInfoparam3 : JAntennaInfo) : JRFIDResults; cdecl; overload;// (ILjava/lang/String;Ljava/lang/String;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JTagDataparam1 : JTagData; Integerparam2 : Integer; booleanparam3 : boolean) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/TagData;IZ)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; JTagStorageSettingsparam1 : JTagStorageSettings) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/TagStorageSettings;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; Jvparam1 : Jv) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/v;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; Integerparam2 : Integer) : Integer; cdecl; overload;// (ISI)I A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_Configparam2 : JAntennas_Config; JAntennas_AntennaRfConfigparam3 : JAntennas_AntennaRfConfig; JAntennas_RFModeparam4 : JAntennas_RFMode) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$Config;Lcom/zebra/rfid/api3/Antennas$AntennaRfConfig;Lcom/zebra/rfid/api3/Antennas$RFMode;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_SingulationControlparam2 : JAntennas_SingulationControl) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$SingulationControl;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; SmallIntparam1 : SmallInt; Jbcparam2 : Jbc; TJavaArrayIntegerparam3 : TJavaArray<Integer>) : Integer; cdecl; overload;// (ISLcom/zebra/rfid/api3/bc;[I)I A: $1
    function a(Integerparam0 : Integer; TJavaArrayJDYNAMIC_POWER_OPTIMIZATIONparam1 : TJavaArray<JDYNAMIC_POWER_OPTIMIZATION>) : JRFIDResults; cdecl; overload;// (I[Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; TJavaArrayJUNIQUE_TAG_REPORT_SETTINGparam1 : TJavaArray<JUNIQUE_TAG_REPORT_SETTING>) : JRFIDResults; cdecl; overload;// (I[Lcom/zebra/rfid/api3/UNIQUE_TAG_REPORT_SETTING;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Integerparam0 : Integer; TJavaArrayJclparam1 : TJavaArray<Jcl>; Integerparam2 : Integer; booleanparam3 : boolean; TJavaArrayJTagDataparam4 : TJavaArray<JTagData>) : Integer; cdecl; overload;// (I[Lcom/zebra/rfid/api3/cl;IZ[Lcom/zebra/rfid/api3/TagData;)I A: $1
    function a(Integerparam0 : Integer; booleanparam1 : boolean) : JRFIDResults; cdecl; overload;// (IZ)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JArrayListparam0 : JArrayList) : JRFIDResults; cdecl; overload;  // (Ljava/util/ArrayList;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JRFIDResultsparam0 : JRFIDResults) : JString; cdecl; overload;   // (Lcom/zebra/rfid/api3/RFIDResults;)Ljava/lang/String; A: $1
    function a(JStringparam0 : JString) : JRFIDResults; cdecl; overload;        // (Ljava/lang/String;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(JTagStorageSettingsparam0 : JTagStorageSettings) : JRFIDResults; cdecl; overload;// (Lcom/zebra/rfid/api3/TagStorageSettings;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function a(Jdaparam0 : Jda) : JRFIDResults; cdecl; overload;                // (Lcom/zebra/rfid/api3/da;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; Integerparam1 : Integer) : JRFIDResults; cdecl; overload;// (II)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JRegulatoryConfigparam1 : JRegulatoryConfig) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/RegulatoryConfig;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JStartTriggerparam1 : JStartTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StartTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; JStopTriggerparam1 : JStopTrigger) : JRFIDResults; cdecl; overload;// (ILcom/zebra/rfid/api3/StopTrigger;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_Configparam2 : JAntennas_Config; JAntennas_AntennaRfConfigparam3 : JAntennas_AntennaRfConfig; JAntennas_RFModeparam4 : JAntennas_RFMode) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$Config;Lcom/zebra/rfid/api3/Antennas$AntennaRfConfig;Lcom/zebra/rfid/api3/Antennas$RFMode;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(Integerparam0 : Integer; SmallIntparam1 : SmallInt; JAntennas_SingulationControlparam2 : JAntennas_SingulationControl) : JRFIDResults; cdecl; overload;// (ISLcom/zebra/rfid/api3/Antennas$SingulationControl;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function b(JStringparam0 : JString) : JRFIDResults; cdecl; overload;        // (Ljava/lang/String;)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function c(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function d(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function e(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function f(Integerparam0 : Integer) : JRFIDResults; cdecl; overload;        // (I)Lcom/zebra/rfid/api3/RFIDResults; A: $1
    procedure a ; cdecl; overload;                                              // ()V A: $1
    procedure a(JStringparam0 : JString; JStringparam1 : JString) ; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
  end;

  TJbf = class(TJavaGenericImport<JbfClass, Jbf>)
  end;

implementation

end.
