//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.y;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jy = interface;

  JyClass = interface(JObjectClass)
    ['{285A8464-4A23-484A-8B33-081D4EF000E5}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : TJavaArray<Integer>; cdecl;                                //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : TJavaArray<Integer>) ; cdecl;                       //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : TJavaArray<Integer> read _Getb write _Setb;                    // [I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/y')]
  Jy = interface(JObject)
    ['{5CCDC913-1A17-4476-989B-C29865C2F7F2}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : TJavaArray<Integer>; cdecl;                                //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : TJavaArray<Integer>) ; cdecl;                       //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : TJavaArray<Integer> read _Getb write _Setb;                    // [I A: $1
  end;

  TJy = class(TJavaGenericImport<JyClass, Jy>)
  end;

implementation

end.
