//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.FILTER_ACTION;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JFILTER_ACTION = interface;

  JFILTER_ACTIONClass = interface(JObjectClass)
    ['{AE00A6AA-0AF9-4C9F-8A7F-EE8812DD9708}']
    function _GetFILTER_ACTION_DEFAULT : JFILTER_ACTION; cdecl;                 //  A: $19
    function _GetFILTER_ACTION_STATE_AWARE : JFILTER_ACTION; cdecl;             //  A: $19
    function _GetFILTER_ACTION_STATE_UNAWARE : JFILTER_ACTION; cdecl;           //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property FILTER_ACTION_DEFAULT : JFILTER_ACTION read _GetFILTER_ACTION_DEFAULT;// Lcom/zebra/rfid/api3/FILTER_ACTION; A: $19
    property FILTER_ACTION_STATE_AWARE : JFILTER_ACTION read _GetFILTER_ACTION_STATE_AWARE;// Lcom/zebra/rfid/api3/FILTER_ACTION; A: $19
    property FILTER_ACTION_STATE_UNAWARE : JFILTER_ACTION read _GetFILTER_ACTION_STATE_UNAWARE;// Lcom/zebra/rfid/api3/FILTER_ACTION; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/FILTER_ACTION')]
  JFILTER_ACTION = interface(JObject)
    ['{F4643FF8-457B-4E8D-AA47-4705BDCF948D}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJFILTER_ACTION = class(TJavaGenericImport<JFILTER_ACTIONClass, JFILTER_ACTION>)
  end;

implementation

end.
