//
// Generated by JavaToPas v1.5 20170214 - 172218
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.g;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.ANTENNA_STOP_TRIGGER_TYPE;

type
  Jg = interface;

  JgClass = interface(JObjectClass)
    ['{E73B556C-8065-497E-8343-B44C84EED4C7}']
    function _Geta : JANTENNA_STOP_TRIGGER_TYPE; cdecl;                         //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : Integer; cdecl;                                            //  A: $1
    procedure _Seta(Value : JANTENNA_STOP_TRIGGER_TYPE) ; cdecl;                //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : Integer) ; cdecl;                                   //  A: $1
    property a : JANTENNA_STOP_TRIGGER_TYPE read _Geta write _Seta;             // Lcom/zebra/rfid/api3/ANTENNA_STOP_TRIGGER_TYPE; A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : Integer read _Getc write _Setc;                                // I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/g')]
  Jg = interface(JObject)
    ['{6E90DE39-8AC4-4430-84AB-700F862AD069}']
    function _Geta : JANTENNA_STOP_TRIGGER_TYPE; cdecl;                         //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : Integer; cdecl;                                            //  A: $1
    procedure _Seta(Value : JANTENNA_STOP_TRIGGER_TYPE) ; cdecl;                //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : Integer) ; cdecl;                                   //  A: $1
    property a : JANTENNA_STOP_TRIGGER_TYPE read _Geta write _Seta;             // Lcom/zebra/rfid/api3/ANTENNA_STOP_TRIGGER_TYPE; A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : Integer read _Getc write _Setc;                                // I A: $1
  end;

  TJg = class(TJavaGenericImport<JgClass, Jg>)
  end;

implementation

end.
