//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.cz;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.SYSTEMTIME;

type
  Jcz = interface;

  JczClass = interface(JObjectClass)
    ['{23A15F17-C2AB-4DDF-B966-C9B0D4C8AFF4}']
    function _Geta : JSYSTEMTIME; cdecl;                                        //  A: $1
    function _Getb : JSYSTEMTIME; cdecl;                                        //  A: $1
    procedure _Seta(Value : JSYSTEMTIME) ; cdecl;                               //  A: $1
    procedure _Setb(Value : JSYSTEMTIME) ; cdecl;                               //  A: $1
    property a : JSYSTEMTIME read _Geta write _Seta;                            // Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    property b : JSYSTEMTIME read _Getb write _Setb;                            // Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/cz')]
  Jcz = interface(JObject)
    ['{0E1B28B0-5AA6-4BB0-9D52-3712387E72D5}']
    function _Geta : JSYSTEMTIME; cdecl;                                        //  A: $1
    function _Getb : JSYSTEMTIME; cdecl;                                        //  A: $1
    procedure _Seta(Value : JSYSTEMTIME) ; cdecl;                               //  A: $1
    procedure _Setb(Value : JSYSTEMTIME) ; cdecl;                               //  A: $1
    property a : JSYSTEMTIME read _Geta write _Seta;                            // Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    property b : JSYSTEMTIME read _Getb write _Setb;                            // Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
  end;

  TJcz = class(TJavaGenericImport<JczClass, Jcz>)
  end;

implementation

end.
