//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.INVENTORY_STATE;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JINVENTORY_STATE = interface;

  JINVENTORY_STATEClass = interface(JObjectClass)
    ['{07552D97-E798-4B37-B994-24F02AFA9349}']
    function GetInventoryState(value : Integer) : JINVENTORY_STATE; cdecl;      // (I)Lcom/zebra/rfid/api3/INVENTORY_STATE; A: $9
    function _GetINVENTORY_STATE_A : JINVENTORY_STATE; cdecl;                   //  A: $19
    function _GetINVENTORY_STATE_AB_FLIP : JINVENTORY_STATE; cdecl;             //  A: $19
    function _GetINVENTORY_STATE_B : JINVENTORY_STATE; cdecl;                   //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property INVENTORY_STATE_A : JINVENTORY_STATE read _GetINVENTORY_STATE_A;   // Lcom/zebra/rfid/api3/INVENTORY_STATE; A: $19
    property INVENTORY_STATE_AB_FLIP : JINVENTORY_STATE read _GetINVENTORY_STATE_AB_FLIP;// Lcom/zebra/rfid/api3/INVENTORY_STATE; A: $19
    property INVENTORY_STATE_B : JINVENTORY_STATE read _GetINVENTORY_STATE_B;   // Lcom/zebra/rfid/api3/INVENTORY_STATE; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/INVENTORY_STATE')]
  JINVENTORY_STATE = interface(JObject)
    ['{E40F279F-13C8-4C87-AF14-0BF9519CC6A1}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJINVENTORY_STATE = class(TJavaGenericImport<JINVENTORY_STATEClass, JINVENTORY_STATE>)
  end;

implementation

end.
