//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagAccess_LockAccessParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.LOCK_PRIVILEGE,
  com.zebra.rfid.api3.Impinj,
  com.zebra.rfid.api3.LOCK_DATA_FIELD;

type
  JTagAccess_LockAccessParams = interface;

  JTagAccess_LockAccessParamsClass = interface(JObjectClass)
    ['{76CF0C3E-E2EF-447F-97CE-DDB61AA528F9}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getAccessPasswordMemoryIndex : Integer; cdecl;                     // ()I A: $1
    function getEPCMemoryIndex : Integer; cdecl;                                // ()I A: $1
    function getKillPasswordMemoryIndex : Integer; cdecl;                       // ()I A: $1
    function getLockPrivilege : TJavaArray<JLOCK_PRIVILEGE>; cdecl;             // ()[Lcom/zebra/rfid/api3/LOCK_PRIVILEGE; A: $1
    function getTIDMemoryIndex : Integer; cdecl;                                // ()I A: $1
    function getUserMemoryIndex : Integer; cdecl;                               // ()I A: $1
    function init(JTagAccessparam0 : JTagAccess) : JTagAccess_LockAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    function init(m_nAccessPassword : Int64; m_eLockPrivilege : TJavaArray<JLOCK_PRIVILEGE>) : JTagAccess_LockAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;J[Lcom/zebra/rfid/api3/LOCK_PRIVILEGE;)V A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setLockPrivilege(lockDataField : JLOCK_DATA_FIELD; lockPrivilege : JLOCK_PRIVILEGE) ; cdecl;// (Lcom/zebra/rfid/api3/LOCK_DATA_FIELD;Lcom/zebra/rfid/api3/LOCK_PRIVILEGE;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess_LockAccessParams')]
  JTagAccess_LockAccessParams = interface(JObject)
    ['{91A96665-78AF-4CBB-A9F0-2043BC05F5C7}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getAccessPasswordMemoryIndex : Integer; cdecl;                     // ()I A: $1
    function getEPCMemoryIndex : Integer; cdecl;                                // ()I A: $1
    function getKillPasswordMemoryIndex : Integer; cdecl;                       // ()I A: $1
    function getLockPrivilege : TJavaArray<JLOCK_PRIVILEGE>; cdecl;             // ()[Lcom/zebra/rfid/api3/LOCK_PRIVILEGE; A: $1
    function getTIDMemoryIndex : Integer; cdecl;                                // ()I A: $1
    function getUserMemoryIndex : Integer; cdecl;                               // ()I A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setLockPrivilege(lockDataField : JLOCK_DATA_FIELD; lockPrivilege : JLOCK_PRIVILEGE) ; cdecl;// (Lcom/zebra/rfid/api3/LOCK_DATA_FIELD;Lcom/zebra/rfid/api3/LOCK_PRIVILEGE;)V A: $1
  end;

  TJTagAccess_LockAccessParams = class(TJavaGenericImport<JTagAccess_LockAccessParamsClass, JTagAccess_LockAccessParams>)
  end;

const
  TJTagAccess_LockAccessParamsb = 5;

implementation

end.
