//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ap;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jap = interface;

  JapClass = interface(JObjectClass)
    ['{ACE6EEF5-31CD-4F21-AC69-8C0674DE6F02}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ap')]
  Jap = interface(JObject)
    ['{82265CC2-88EC-4E21-950A-B370015225C1}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  TJap = class(TJavaGenericImport<JapClass, Jap>)
  end;

implementation

end.
