//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.MATCH_RANGE;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JMATCH_RANGE = interface;

  JMATCH_RANGEClass = interface(JObjectClass)
    ['{C036DC20-9BC0-40FE-BBC2-FAB8393DC805}']
    function _GetGREATER_THAN_LOWER_LIMIT : JMATCH_RANGE; cdecl;                //  A: $19
    function _GetLOWER_THAN_UPPER_LIMIT : JMATCH_RANGE; cdecl;                  //  A: $19
    function _GetOUTSIDE_RANGE : JMATCH_RANGE; cdecl;                           //  A: $19
    function _GetWITHIN_RANGE : JMATCH_RANGE; cdecl;                            //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property GREATER_THAN_LOWER_LIMIT : JMATCH_RANGE read _GetGREATER_THAN_LOWER_LIMIT;// Lcom/zebra/rfid/api3/MATCH_RANGE; A: $19
    property LOWER_THAN_UPPER_LIMIT : JMATCH_RANGE read _GetLOWER_THAN_UPPER_LIMIT;// Lcom/zebra/rfid/api3/MATCH_RANGE; A: $19
    property OUTSIDE_RANGE : JMATCH_RANGE read _GetOUTSIDE_RANGE;               // Lcom/zebra/rfid/api3/MATCH_RANGE; A: $19
    property WITHIN_RANGE : JMATCH_RANGE read _GetWITHIN_RANGE;                 // Lcom/zebra/rfid/api3/MATCH_RANGE; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/MATCH_RANGE')]
  JMATCH_RANGE = interface(JObject)
    ['{6C3B8941-B4EC-4D5D-87E3-5F29F0B9387E}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJMATCH_RANGE = class(TJavaGenericImport<JMATCH_RANGEClass, JMATCH_RANGE>)
  end;

implementation

end.
