//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Events_InventoryStartEventData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Events;

type
  JEvents_InventoryStartEventData = interface;

  JEvents_InventoryStartEventDataClass = interface(JObjectClass)
    ['{4236F65F-229F-4A80-A071-6BE11011C55E}']
  end;

  [JavaSignature('com/zebra/rfid/api3/Events_InventoryStartEventData')]
  JEvents_InventoryStartEventData = interface(JObject)
    ['{E659FC33-6B18-476C-8EA6-FBEFDA28656D}']
  end;

  TJEvents_InventoryStartEventData = class(TJavaGenericImport<JEvents_InventoryStartEventDataClass, JEvents_InventoryStartEventData>)
  end;

implementation

end.
