//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.OPERATION_QUALIFIER;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JOPERATION_QUALIFIER = interface;

  JOPERATION_QUALIFIERClass = interface(JObjectClass)
    ['{88E03C12-4FCC-48D9-89E7-BE3AD2F7CDB2}']
    function _GetC1G2_OPERATION : JOPERATION_QUALIFIER; cdecl;                  //  A: $19
    function _GetLOCATE_TAG : JOPERATION_QUALIFIER; cdecl;                      //  A: $19
    function _GetNXP_EAS_SCAN : JOPERATION_QUALIFIER; cdecl;                    //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property C1G2_OPERATION : JOPERATION_QUALIFIER read _GetC1G2_OPERATION;     // Lcom/zebra/rfid/api3/OPERATION_QUALIFIER; A: $19
    property LOCATE_TAG : JOPERATION_QUALIFIER read _GetLOCATE_TAG;             // Lcom/zebra/rfid/api3/OPERATION_QUALIFIER; A: $19
    property NXP_EAS_SCAN : JOPERATION_QUALIFIER read _GetNXP_EAS_SCAN;         // Lcom/zebra/rfid/api3/OPERATION_QUALIFIER; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/OPERATION_QUALIFIER')]
  JOPERATION_QUALIFIER = interface(JObject)
    ['{F9A2CAFE-E339-4BBB-B471-40FFCAE6F249}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJOPERATION_QUALIFIER = class(TJavaGenericImport<JOPERATION_QUALIFIERClass, JOPERATION_QUALIFIER>)
  end;

implementation

end.
