//
// Generated by JavaToPas v1.5 20170214 - 172217
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.AccessOperationResult;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.ImpinjQTData,
  com.zebra.rfid.api3.NXPChangeConfigResult;

type
  JAccessOperationResult = interface;

  JAccessOperationResultClass = interface(JObjectClass)
    ['{9D847B7F-AE85-4A9A-B6F1-2638BECE5943}']
    function _GetImpinjQTData : JImpinjQTData; cdecl;                           //  A: $1
    function _GetNXPChangeConfigResult : JNXPChangeConfigResult; cdecl;         //  A: $1
    procedure _SetImpinjQTData(Value : JImpinjQTData) ; cdecl;                  //  A: $1
    procedure _SetNXPChangeConfigResult(Value : JNXPChangeConfigResult) ; cdecl;//  A: $1
    property ImpinjQTData : JImpinjQTData read _GetImpinjQTData write _SetImpinjQTData;// Lcom/zebra/rfid/api3/ImpinjQTData; A: $1
    property NXPChangeConfigResult : JNXPChangeConfigResult read _GetNXPChangeConfigResult write _SetNXPChangeConfigResult;// Lcom/zebra/rfid/api3/NXPChangeConfigResult; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/AccessOperationResult')]
  JAccessOperationResult = interface(JObject)
    ['{CE7C0F18-48E9-4417-A3AF-0E65CE9E56D8}']
    function _GetImpinjQTData : JImpinjQTData; cdecl;                           //  A: $1
    function _GetNXPChangeConfigResult : JNXPChangeConfigResult; cdecl;         //  A: $1
    procedure _SetImpinjQTData(Value : JImpinjQTData) ; cdecl;                  //  A: $1
    procedure _SetNXPChangeConfigResult(Value : JNXPChangeConfigResult) ; cdecl;//  A: $1
    property ImpinjQTData : JImpinjQTData read _GetImpinjQTData write _SetImpinjQTData;// Lcom/zebra/rfid/api3/ImpinjQTData; A: $1
    property NXPChangeConfigResult : JNXPChangeConfigResult read _GetNXPChangeConfigResult write _SetNXPChangeConfigResult;// Lcom/zebra/rfid/api3/NXPChangeConfigResult; A: $1
  end;

  TJAccessOperationResult = class(TJavaGenericImport<JAccessOperationResultClass, JAccessOperationResult>)
  end;

implementation

end.
