//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.u;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Ju = interface;

  JuClass = interface(JObjectClass)
    ['{303E42C9-C266-4D41-9246-E94940848AF0}']
  end;

  [JavaSignature('com/zebra/rfid/api3/u')]
  Ju = interface(JObject)
    ['{9320519C-BF60-4299-A764-F14837A4E82A}']
  end;

  TJu = class(TJavaGenericImport<JuClass, Ju>)
  end;

implementation

end.
