//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ac;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jac = interface;

  JacClass = interface(JObjectClass)
    ['{25CE2D02-7736-451E-920B-DD08C6A0297F}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : boolean; cdecl;                                            //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : boolean) ; cdecl;                                   //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : boolean read _Getb write _Setb;                                // Z A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ac')]
  Jac = interface(JObject)
    ['{F928F463-A5D2-45A8-8DD1-560D9981C480}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : boolean; cdecl;                                            //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : boolean) ; cdecl;                                   //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : boolean read _Getb write _Setb;                                // Z A: $1
  end;

  TJac = class(TJavaGenericImport<JacClass, Jac>)
  end;

implementation

end.
