//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TAG_EVENT_REPORT_TRIGGER;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JTAG_EVENT_REPORT_TRIGGER = interface;

  JTAG_EVENT_REPORT_TRIGGERClass = interface(JObjectClass)
    ['{7E43F7C0-F7F1-4D19-8A86-4FB2DD08C602}']
    function _GetIMMEDIATE : JTAG_EVENT_REPORT_TRIGGER; cdecl;                  //  A: $19
    function _GetMODERATED : JTAG_EVENT_REPORT_TRIGGER; cdecl;                  //  A: $19
    function _GetNEVER : JTAG_EVENT_REPORT_TRIGGER; cdecl;                      //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property IMMEDIATE : JTAG_EVENT_REPORT_TRIGGER read _GetIMMEDIATE;          // Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $19
    property MODERATED : JTAG_EVENT_REPORT_TRIGGER read _GetMODERATED;          // Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $19
    property NEVER : JTAG_EVENT_REPORT_TRIGGER read _GetNEVER;                  // Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER')]
  JTAG_EVENT_REPORT_TRIGGER = interface(JObject)
    ['{39A1C914-00B4-4AF9-B6D3-07C557DD7084}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJTAG_EVENT_REPORT_TRIGGER = class(TJavaGenericImport<JTAG_EVENT_REPORT_TRIGGERClass, JTAG_EVENT_REPORT_TRIGGER>)
  end;

implementation

end.
