//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Impinj;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.ay,
  com.zebra.rfid.api3.TagData,
  com.zebra.rfid.api3.AntennaInfo,
  com.zebra.rfid.api3.AccessFilter,
  com.zebra.rfid.api3.TagAccess_Sequence,
  com.zebra.rfid.api3.NXP,
  com.zebra.rfid.api3.cl,
  com.zebra.rfid.api3.TagAccess_ReadAccessParams,
  com.zebra.rfid.api3.TagAccess_WriteAccessParams,
  com.zebra.rfid.api3.TagAccess_KillAccessParams,
  com.zebra.rfid.api3.TagAccess_LockAccessParams,
  com.zebra.rfid.api3.TagAccess_BlockEraseAccessParams,
  com.zebra.rfid.api3.TagAccess_BlockPermalockAccessParams,
  com.zebra.rfid.api3.TagAccess_WriteSpecificFieldAccessParams,
  com.zebra.rfid.api3.TagAccess_RecommisionAccessParams;

type
  JImpinj_QTWriteAccessParams = interface; // merged
  JImpinj_QTReadAccessParams = interface; // merged
  JTagAccess = interface; // merged
  JImpinj = interface;

  JImpinjClass = interface(JObjectClass)
    ['{8158571B-C17E-4CE3-ABAC-4E0C4E18CAF0}']
    function QTReadWait(tagID : JString; qtReadAccessParams : JImpinj_QTReadAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/Impinj$QTReadAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    function init(tagAccess : JTagAccess) : JImpinj; cdecl; overload;           // (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    procedure QTReadEvent(qtReadAccessParams : JImpinj_QTReadAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/Impinj$QTReadAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure QTWriteEvent(qtWriteAccessParams : JImpinj_QTWriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/Impinj$QTWriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure QTWriteWait(tagID : JString; qtWriteAccessParams : JImpinj_QTWriteAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/Impinj$QTWriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure init(nativeLibParams : Jay) ; cdecl; overload;                    // (Lcom/zebra/rfid/api3/ay;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Impinj$QTReadAccessParams')]
  JImpinj = interface(JObject)
    ['{74010F33-F73B-4B91-8B2C-F76D9E9E726B}']
    function QTReadWait(tagID : JString; qtReadAccessParams : JImpinj_QTReadAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/Impinj$QTReadAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    procedure QTReadEvent(qtReadAccessParams : JImpinj_QTReadAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/Impinj$QTReadAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure QTWriteEvent(qtWriteAccessParams : JImpinj_QTWriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/Impinj$QTWriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure QTWriteWait(tagID : JString; qtWriteAccessParams : JImpinj_QTWriteAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/Impinj$QTWriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
  end;

  TJImpinj = class(TJavaGenericImport<JImpinjClass, JImpinj>)
  end;

  // Merged from: .\com.zebra.rfid.api3.TagAccess.pas
  JTagAccessClass = interface(JObjectClass)
    ['{9131D26A-DB52-4CD4-AFD5-847F294B13EC}']
    function _GetImpinj : JImpinj; cdecl;                                       //  A: $1
    function _GetNXP : JNXP; cdecl;                                             //  A: $1
    function _GetOperationSequence : JTagAccess_Sequence; cdecl;                //  A: $1
    function blockPermalockWait(tagID : JString; blockPermalockAccessParams : JTagAccess_BlockPermalockAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$BlockPermalockAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    function init : JTagAccess; cdecl; overload;                                // ()V A: $1
    function readWait(tagID : JString; readAccessParams : JTagAccess_ReadAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$ReadAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    procedure _SetImpinj(Value : JImpinj) ; cdecl;                              //  A: $1
    procedure _SetNXP(Value : JNXP) ; cdecl;                                    //  A: $1
    procedure _SetOperationSequence(Value : JTagAccess_Sequence) ; cdecl;       //  A: $1
    procedure blockEraseEvent(blockEraseAccessParams : JTagAccess_BlockEraseAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$BlockEraseAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockEraseWait(tagID : JString; blockEraseAccessParams : JTagAccess_BlockEraseAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$BlockEraseAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    procedure blockPermalockEvent(blockPermalockAccessParams : JTagAccess_BlockPermalockAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$BlockPermalockAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockWriteEvent(writeAccessParams : JTagAccess_WriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockWriteWait(tagID : JString; writeAccessParams : JTagAccess_WriteAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    procedure getLastAccessResult(successCount : TJavaArray<Integer>; failureCount : TJavaArray<Integer>) ; cdecl;// ([I[I)V A: $1
    procedure init(nativeLibParams : Jay) ; cdecl; overload;                    // (Lcom/zebra/rfid/api3/ay;)V A: $1
    procedure killEvent(killAccessParams : JTagAccess_KillAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$KillAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure killWait(tagID : JString; killAccessParams : JTagAccess_KillAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$KillAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure lockEvent(lockAccessParams : JTagAccess_LockAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$LockAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure lockWait(tagID : JString; lockAccessParams : JTagAccess_LockAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$LockAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure readEvent(readAccessParams : JTagAccess_ReadAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$ReadAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure recommisionEvent(recommisionAccessParams : JTagAccess_RecommisionAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$RecommisionAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure recommisionWait(tagID : JString; recommisionAccessParams : JTagAccess_RecommisionAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$RecommisionAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure stopAccess ; cdecl;                                               // ()V A: $1
    procedure writeAccessPasswordWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeEvent(writeAccessParams : JTagAccess_WriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeKillPasswordWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeTagIDWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeWait(tagID : JString; writeAccessParams : JTagAccess_WriteAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    property Impinj : JImpinj read _GetImpinj write _SetImpinj;                 // Lcom/zebra/rfid/api3/Impinj; A: $1
    property NXP : JNXP read _GetNXP write _SetNXP;                             // Lcom/zebra/rfid/api3/NXP; A: $1
    property OperationSequence : JTagAccess_Sequence read _GetOperationSequence write _SetOperationSequence;// Lcom/zebra/rfid/api3/TagAccess$Sequence; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess$BlockPermalockAccessParams')]
  JTagAccess = interface(JObject)
    ['{8FEA2217-BAE6-4896-A0AE-BD91152960D3}']
    function _GetImpinj : JImpinj; cdecl;                                       //  A: $1
    function _GetNXP : JNXP; cdecl;                                             //  A: $1
    function _GetOperationSequence : JTagAccess_Sequence; cdecl;                //  A: $1
    function blockPermalockWait(tagID : JString; blockPermalockAccessParams : JTagAccess_BlockPermalockAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$BlockPermalockAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    function readWait(tagID : JString; readAccessParams : JTagAccess_ReadAccessParams; antennaInfo : JAntennaInfo) : JTagData; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$ReadAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)Lcom/zebra/rfid/api3/TagData; A: $1
    procedure _SetImpinj(Value : JImpinj) ; cdecl;                              //  A: $1
    procedure _SetNXP(Value : JNXP) ; cdecl;                                    //  A: $1
    procedure _SetOperationSequence(Value : JTagAccess_Sequence) ; cdecl;       //  A: $1
    procedure blockEraseEvent(blockEraseAccessParams : JTagAccess_BlockEraseAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$BlockEraseAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockEraseWait(tagID : JString; blockEraseAccessParams : JTagAccess_BlockEraseAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$BlockEraseAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    procedure blockPermalockEvent(blockPermalockAccessParams : JTagAccess_BlockPermalockAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$BlockPermalockAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockWriteEvent(writeAccessParams : JTagAccess_WriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure blockWriteWait(tagID : JString; writeAccessParams : JTagAccess_WriteAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    procedure getLastAccessResult(successCount : TJavaArray<Integer>; failureCount : TJavaArray<Integer>) ; cdecl;// ([I[I)V A: $1
    procedure killEvent(killAccessParams : JTagAccess_KillAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$KillAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure killWait(tagID : JString; killAccessParams : JTagAccess_KillAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$KillAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure lockEvent(lockAccessParams : JTagAccess_LockAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$LockAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure lockWait(tagID : JString; lockAccessParams : JTagAccess_LockAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$LockAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure readEvent(readAccessParams : JTagAccess_ReadAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$ReadAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure recommisionEvent(recommisionAccessParams : JTagAccess_RecommisionAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$RecommisionAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure recommisionWait(tagID : JString; recommisionAccessParams : JTagAccess_RecommisionAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$RecommisionAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure stopAccess ; cdecl;                                               // ()V A: $1
    procedure writeAccessPasswordWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeEvent(writeAccessParams : JTagAccess_WriteAccessParams; accessFilter : JAccessFilter; antennaInfo : JAntennaInfo) ; cdecl;// (Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AccessFilter;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeKillPasswordWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeTagIDWait(tagID : JString; writeSpecificFieldAccessParams : JTagAccess_WriteSpecificFieldAccessParams; antennaInfo : JAntennaInfo) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteSpecificFieldAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;)V A: $1
    procedure writeWait(tagID : JString; writeAccessParams : JTagAccess_WriteAccessParams; antennaInfo : JAntennaInfo; tagData : JTagData) ; cdecl;// (Ljava/lang/String;Lcom/zebra/rfid/api3/TagAccess$WriteAccessParams;Lcom/zebra/rfid/api3/AntennaInfo;Lcom/zebra/rfid/api3/TagData;)V A: $1
    property Impinj : JImpinj read _GetImpinj write _SetImpinj;                 // Lcom/zebra/rfid/api3/Impinj; A: $1
    property NXP : JNXP read _GetNXP write _SetNXP;                             // Lcom/zebra/rfid/api3/NXP; A: $1
    property OperationSequence : JTagAccess_Sequence read _GetOperationSequence write _SetOperationSequence;// Lcom/zebra/rfid/api3/TagAccess$Sequence; A: $1
  end;

  TJTagAccess = class(TJavaGenericImport<JTagAccessClass, JTagAccess>)
  end;


  // Merged from: .\com.zebra.rfid.api3.Impinj_QTReadAccessParams.pas
  JImpinj_QTReadAccessParamsClass = interface(JObjectClass)
    ['{DD8175E5-27E2-4D54-A391-B9CE0E31EE70}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function init(JImpinjparam0 : JImpinj) : JImpinj_QTReadAccessParams; cdecl; // (Lcom/zebra/rfid/api3/Impinj;)V A: $1
    procedure setAccessPassword(m_nAccessPassword : Int64) ; cdecl;             // (J)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Impinj_QTReadAccessParams')]
  JImpinj_QTReadAccessParams = interface(JObject)
    ['{8DB5D2A0-A221-433E-B7D4-87A3F7EE999A}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    procedure setAccessPassword(m_nAccessPassword : Int64) ; cdecl;             // (J)V A: $1
  end;

  TJImpinj_QTReadAccessParams = class(TJavaGenericImport<JImpinj_QTReadAccessParamsClass, JImpinj_QTReadAccessParams>)
  end;


  // Merged from: .\com.zebra.rfid.api3.Impinj_QTWriteAccessParams.pas
  JImpinj_QTWriteAccessParamsClass = interface(JObjectClass)
    ['{4E718E34-EA8C-481D-B68C-6F7C1B6BBCE4}']
    function _Getm_QTControlData : SmallInt; cdecl;                             //  A: $1
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getQTControlData : SmallInt; cdecl;                                // ()S A: $1
    function init(JImpinjparam0 : JImpinj) : JImpinj_QTWriteAccessParams; cdecl;// (Lcom/zebra/rfid/api3/Impinj;)V A: $1
    function isQTPersist : boolean; cdecl;                                      // ()Z A: $1
    procedure _Setm_QTControlData(Value : SmallInt) ; cdecl;                    //  A: $1
    procedure setAccessPassword(m_nAccessPassword : Int64) ; cdecl;             // (J)V A: $1
    procedure setQTControlData(m_QTControlData : SmallInt) ; cdecl;             // (S)V A: $1
    procedure setQTPersist(QTPersist : boolean) ; cdecl;                        // (Z)V A: $1
    property m_QTControlData : SmallInt read _Getm_QTControlData write _Setm_QTControlData;// S A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Impinj_QTWriteAccessParams')]
  JImpinj_QTWriteAccessParams = interface(JObject)
    ['{0EC04D1C-02B3-49F5-916A-EE9176597B8F}']
    function _Getm_QTControlData : SmallInt; cdecl;                             //  A: $1
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getQTControlData : SmallInt; cdecl;                                // ()S A: $1
    function isQTPersist : boolean; cdecl;                                      // ()Z A: $1
    procedure _Setm_QTControlData(Value : SmallInt) ; cdecl;                    //  A: $1
    procedure setAccessPassword(m_nAccessPassword : Int64) ; cdecl;             // (J)V A: $1
    procedure setQTControlData(m_QTControlData : SmallInt) ; cdecl;             // (S)V A: $1
    procedure setQTPersist(QTPersist : boolean) ; cdecl;                        // (Z)V A: $1
    property m_QTControlData : SmallInt read _Getm_QTControlData write _Setm_QTControlData;// S A: $1
  end;

  TJImpinj_QTWriteAccessParams = class(TJavaGenericImport<JImpinj_QTWriteAccessParamsClass, JImpinj_QTWriteAccessParams>)
  end;


implementation

end.
