//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.UpdateStatus;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JUpdateStatus = interface;

  JUpdateStatusClass = interface(JObjectClass)
    ['{90119365-2CA0-4A51-B901-832AECBBCAD0}']
    function getPercentage : Integer; cdecl;                                    // ()I A: $1
    function getUpdateInfo : JString; cdecl;                                    // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/UpdateStatus')]
  JUpdateStatus = interface(JObject)
    ['{3B256E5E-FD4A-4320-ABDB-3E65DF3A2249}']
    function getPercentage : Integer; cdecl;                                    // ()I A: $1
    function getUpdateInfo : JString; cdecl;                                    // ()Ljava/lang/String; A: $1
  end;

  TJUpdateStatus = class(TJavaGenericImport<JUpdateStatusClass, JUpdateStatus>)
  end;

implementation

end.
