//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.db;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.MEMORY_BANK;

type
  Jdb = interface;

  JdbClass = interface(JObjectClass)
    ['{ED941928-77D7-42FF-8452-1549DB00E928}']
    function _Geta : JMEMORY_BANK; cdecl;                                       //  A: $1
    function _Getb : SmallInt; cdecl;                                           //  A: $1
    function _Getc : TJavaArray<Byte>; cdecl;                                   //  A: $1
    function _Getd : SmallInt; cdecl;                                           //  A: $1
    function _Gete : Int64; cdecl;                                              //  A: $1
    procedure _Seta(Value : JMEMORY_BANK) ; cdecl;                              //  A: $1
    procedure _Setb(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setc(Value : TJavaArray<Byte>) ; cdecl;                          //  A: $1
    procedure _Setd(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Sete(Value : Int64) ; cdecl;                                     //  A: $1
    property a : JMEMORY_BANK read _Geta write _Seta;                           // Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    property b : SmallInt read _Getb write _Setb;                               // S A: $1
    property c : TJavaArray<Byte> read _Getc write _Setc;                       // [B A: $1
    property d : SmallInt read _Getd write _Setd;                               // S A: $1
    property e : Int64 read _Gete write _Sete;                                  // J A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/db')]
  Jdb = interface(JObject)
    ['{B2AB061A-2BB6-4852-8534-B22C8180E5F7}']
    function _Geta : JMEMORY_BANK; cdecl;                                       //  A: $1
    function _Getb : SmallInt; cdecl;                                           //  A: $1
    function _Getc : TJavaArray<Byte>; cdecl;                                   //  A: $1
    function _Getd : SmallInt; cdecl;                                           //  A: $1
    function _Gete : Int64; cdecl;                                              //  A: $1
    procedure _Seta(Value : JMEMORY_BANK) ; cdecl;                              //  A: $1
    procedure _Setb(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setc(Value : TJavaArray<Byte>) ; cdecl;                          //  A: $1
    procedure _Setd(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Sete(Value : Int64) ; cdecl;                                     //  A: $1
    property a : JMEMORY_BANK read _Geta write _Seta;                           // Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    property b : SmallInt read _Getb write _Setb;                               // S A: $1
    property c : TJavaArray<Byte> read _Getc write _Setc;                       // [B A: $1
    property d : SmallInt read _Getd write _Setd;                               // S A: $1
    property e : Int64 read _Gete write _Sete;                                  // J A: $1
  end;

  TJdb = class(TJavaGenericImport<JdbClass, Jdb>)
  end;

implementation

end.
