//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RUN_STATUS;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JRUN_STATUS = interface;

  JRUN_STATUSClass = interface(JObjectClass)
    ['{6734D01B-73BB-4476-BE5F-690E7AA01505}']
    function getRunStatus : boolean; cdecl;                                     // ()Z A: $1
    function init : JRUN_STATUS; cdecl;                                         // ()V A: $1
    procedure setRunStatus(status : boolean) ; cdecl;                           // (Z)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/RUN_STATUS')]
  JRUN_STATUS = interface(JObject)
    ['{70A1E53B-D959-4FFE-821B-F74C67DF791B}']
    function getRunStatus : boolean; cdecl;                                     // ()Z A: $1
    procedure setRunStatus(status : boolean) ; cdecl;                           // (Z)V A: $1
  end;

  TJRUN_STATUS = class(TJavaGenericImport<JRUN_STATUSClass, JRUN_STATUS>)
  end;

implementation

end.
