//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bc;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.MEMORY_BANK,
  com.zebra.rfid.api3.FILTER_ACTION,
  com.zebra.rfid.api3.x,
  com.zebra.rfid.api3.TRUNCATE_ACTION;

type
  Jbc = interface;

  JbcClass = interface(JObjectClass)
    ['{B9F8E552-C1E5-42E0-A953-B8D9BB8B4211}']
    function _Geta : JMEMORY_BANK; cdecl;                                       //  A: $1
    function _Getb : TJavaArray<Byte>; cdecl;                                   //  A: $1
    function _Getc : SmallInt; cdecl;                                           //  A: $1
    function _Getd : SmallInt; cdecl;                                           //  A: $1
    function _Gete : JFILTER_ACTION; cdecl;                                     //  A: $1
    function _Getf : Jx; cdecl;                                                 //  A: $1
    function _Getg : JTRUNCATE_ACTION; cdecl;                                   //  A: $1
    procedure _Seta(Value : JMEMORY_BANK) ; cdecl;                              //  A: $1
    procedure _Setb(Value : TJavaArray<Byte>) ; cdecl;                          //  A: $1
    procedure _Setc(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setd(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Sete(Value : JFILTER_ACTION) ; cdecl;                            //  A: $1
    procedure _Setf(Value : Jx) ; cdecl;                                        //  A: $1
    procedure _Setg(Value : JTRUNCATE_ACTION) ; cdecl;                          //  A: $1
    property a : JMEMORY_BANK read _Geta write _Seta;                           // Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    property b : TJavaArray<Byte> read _Getb write _Setb;                       // [B A: $1
    property c : SmallInt read _Getc write _Setc;                               // S A: $1
    property d : SmallInt read _Getd write _Setd;                               // S A: $1
    property e : JFILTER_ACTION read _Gete write _Sete;                         // Lcom/zebra/rfid/api3/FILTER_ACTION; A: $1
    property f : Jx read _Getf write _Setf;                                     // Lcom/zebra/rfid/api3/x; A: $1
    property g : JTRUNCATE_ACTION read _Getg write _Setg;                       // Lcom/zebra/rfid/api3/TRUNCATE_ACTION; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/bc')]
  Jbc = interface(JObject)
    ['{E3E7D249-9CFB-4054-9228-D7AD5609500F}']
    function _Geta : JMEMORY_BANK; cdecl;                                       //  A: $1
    function _Getb : TJavaArray<Byte>; cdecl;                                   //  A: $1
    function _Getc : SmallInt; cdecl;                                           //  A: $1
    function _Getd : SmallInt; cdecl;                                           //  A: $1
    function _Gete : JFILTER_ACTION; cdecl;                                     //  A: $1
    function _Getf : Jx; cdecl;                                                 //  A: $1
    function _Getg : JTRUNCATE_ACTION; cdecl;                                   //  A: $1
    procedure _Seta(Value : JMEMORY_BANK) ; cdecl;                              //  A: $1
    procedure _Setb(Value : TJavaArray<Byte>) ; cdecl;                          //  A: $1
    procedure _Setc(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setd(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Sete(Value : JFILTER_ACTION) ; cdecl;                            //  A: $1
    procedure _Setf(Value : Jx) ; cdecl;                                        //  A: $1
    procedure _Setg(Value : JTRUNCATE_ACTION) ; cdecl;                          //  A: $1
    property a : JMEMORY_BANK read _Geta write _Seta;                           // Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    property b : TJavaArray<Byte> read _Getb write _Setb;                       // [B A: $1
    property c : SmallInt read _Getc write _Setc;                               // S A: $1
    property d : SmallInt read _Getd write _Setd;                               // S A: $1
    property e : JFILTER_ACTION read _Gete write _Sete;                         // Lcom/zebra/rfid/api3/FILTER_ACTION; A: $1
    property f : Jx read _Getf write _Setf;                                     // Lcom/zebra/rfid/api3/x; A: $1
    property g : JTRUNCATE_ACTION read _Getg write _Setg;                       // Lcom/zebra/rfid/api3/TRUNCATE_ACTION; A: $1
  end;

  TJbc = class(TJavaGenericImport<JbcClass, Jbc>)
  end;

implementation

end.
