//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.UNTRACEABLE_TID;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JUNTRACEABLE_TID = interface;

  JUNTRACEABLE_TIDClass = interface(JObjectClass)
    ['{212C19A8-7224-462E-AC67-9E6680E9AB88}']
    function GetUntraceableTidValue(untraceableTid : JString) : JUNTRACEABLE_TID; cdecl; overload;// (Ljava/lang/String;)Lcom/zebra/rfid/api3/UNTRACEABLE_TID; A: $9
    function GetUntraceableTidValue(value : Integer) : JUNTRACEABLE_TID; cdecl; overload;// (I)Lcom/zebra/rfid/api3/UNTRACEABLE_TID; A: $9
    function _GetHIDE_ALL_TID : JUNTRACEABLE_TID; cdecl;                        //  A: $19
    function _GetHIDE_SOME_TID : JUNTRACEABLE_TID; cdecl;                       //  A: $19
    function _GetSHOW_TID : JUNTRACEABLE_TID; cdecl;                            //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    property HIDE_ALL_TID : JUNTRACEABLE_TID read _GetHIDE_ALL_TID;             // Lcom/zebra/rfid/api3/UNTRACEABLE_TID; A: $19
    property HIDE_SOME_TID : JUNTRACEABLE_TID read _GetHIDE_SOME_TID;           // Lcom/zebra/rfid/api3/UNTRACEABLE_TID; A: $19
    property SHOW_TID : JUNTRACEABLE_TID read _GetSHOW_TID;                     // Lcom/zebra/rfid/api3/UNTRACEABLE_TID; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/UNTRACEABLE_TID')]
  JUNTRACEABLE_TID = interface(JObject)
    ['{A52A2DFF-F02B-4136-9AB8-67E619D4E6B8}']
  end;

  TJUNTRACEABLE_TID = class(TJavaGenericImport<JUNTRACEABLE_TIDClass, JUNTRACEABLE_TID>)
  end;

implementation

end.
