//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Events_ReaderExceptionEventData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.bj,
  com.zebra.rfid.api3.Events,
  com.zebra.rfid.api3.READER_EXCEPTION_EVENT_TYPE;

type
  JEvents_ReaderExceptionEventData = interface;

  JEvents_ReaderExceptionEventDataClass = interface(JObjectClass)
    ['{50BAFE52-7315-40FC-845F-2FBCA86A061D}']
    function getReaderExceptionEventInfo : JString; cdecl;                      // ()Ljava/lang/String; A: $1
    function getReaderExceptionEventType : JREADER_EXCEPTION_EVENT_TYPE; cdecl; // ()Lcom/zebra/rfid/api3/READER_EXCEPTION_EVENT_TYPE; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Events_ReaderExceptionEventData')]
  JEvents_ReaderExceptionEventData = interface(JObject)
    ['{A3930B28-F60F-43ED-968A-337378842F5A}']
    function getReaderExceptionEventInfo : JString; cdecl;                      // ()Ljava/lang/String; A: $1
    function getReaderExceptionEventType : JREADER_EXCEPTION_EVENT_TYPE; cdecl; // ()Lcom/zebra/rfid/api3/READER_EXCEPTION_EVENT_TYPE; A: $1
  end;

  TJEvents_ReaderExceptionEventData = class(TJavaGenericImport<JEvents_ReaderExceptionEventDataClass, JEvents_ReaderExceptionEventData>)
  end;

implementation

end.
