//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ct;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jct = interface;

  JctClass = interface(JObjectClass)
    ['{F9307FC6-94DD-4912-BE1A-7B752870F371}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ct')]
  Jct = interface(JObject)
    ['{BD07E0C9-0D3D-4C45-8F91-2EF30CC65ADA}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
  end;

  TJct = class(TJavaGenericImport<JctClass, Jct>)
  end;

implementation

end.
