//
// Generated by JavaToPas v1.5 20170214 - 172215
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_Read;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.ENUM_MEMORY_BANK,
  com.zebra.ASCII_SDK.Param_ReportConfig,
  com.zebra.ASCII_SDK.Param_AccessConfig,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_Read = interface;

  JCommand_ReadClass = interface(JObjectClass)
    ['{77FE6D59-CCFB-49DC-ADBB-2EFEB5CA7C27}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetAccessConfig : JParam_AccessConfig; cdecl;                     //  A: $1
    function _GetReportConfig : JParam_ReportConfig; cdecl;                     //  A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getBank : JENUM_MEMORY_BANK; cdecl;                                // ()Lcom/zebra/ASCII_SDK/ENUM_MEMORY_BANK; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getCriteriaIndex : SmallInt; cdecl;                                // ()S A: $1
    function getLength : SmallInt; cdecl;                                       // ()S A: $1
    function getOffset : SmallInt; cdecl;                                       // ()S A: $1
    function getPassword : Int64; cdecl;                                        // ()J A: $1
    function init : JCommand_Read; cdecl;                                       // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure _SetAccessConfig(Value : JParam_AccessConfig) ; cdecl;            //  A: $1
    procedure _SetReportConfig(Value : JParam_ReportConfig) ; cdecl;            //  A: $1
    procedure setBank(value : JENUM_MEMORY_BANK) ; cdecl;                       // (Lcom/zebra/ASCII_SDK/ENUM_MEMORY_BANK;)V A: $1
    procedure setCriteriaIndex(value : SmallInt) ; cdecl;                       // (S)V A: $1
    procedure setLength(value : SmallInt) ; cdecl;                              // (S)V A: $1
    procedure setOffset(value : SmallInt) ; cdecl;                              // (S)V A: $1
    procedure setPassword(value : Int64) ; cdecl;                               // (J)V A: $1
    property AccessConfig : JParam_AccessConfig read _GetAccessConfig write _SetAccessConfig;// Lcom/zebra/ASCII_SDK/Param_AccessConfig; A: $1
    property ReportConfig : JParam_ReportConfig read _GetReportConfig write _SetReportConfig;// Lcom/zebra/ASCII_SDK/Param_ReportConfig; A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_Read')]
  JCommand_Read = interface(JObject)
    ['{63D873BB-AE45-4138-982B-B0E935EE3D71}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetAccessConfig : JParam_AccessConfig; cdecl;                     //  A: $1
    function _GetReportConfig : JParam_ReportConfig; cdecl;                     //  A: $1
    function getBank : JENUM_MEMORY_BANK; cdecl;                                // ()Lcom/zebra/ASCII_SDK/ENUM_MEMORY_BANK; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getCriteriaIndex : SmallInt; cdecl;                                // ()S A: $1
    function getLength : SmallInt; cdecl;                                       // ()S A: $1
    function getOffset : SmallInt; cdecl;                                       // ()S A: $1
    function getPassword : Int64; cdecl;                                        // ()J A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure _SetAccessConfig(Value : JParam_AccessConfig) ; cdecl;            //  A: $1
    procedure _SetReportConfig(Value : JParam_ReportConfig) ; cdecl;            //  A: $1
    procedure setBank(value : JENUM_MEMORY_BANK) ; cdecl;                       // (Lcom/zebra/ASCII_SDK/ENUM_MEMORY_BANK;)V A: $1
    procedure setCriteriaIndex(value : SmallInt) ; cdecl;                       // (S)V A: $1
    procedure setLength(value : SmallInt) ; cdecl;                              // (S)V A: $1
    procedure setOffset(value : SmallInt) ; cdecl;                              // (S)V A: $1
    procedure setPassword(value : Int64) ; cdecl;                               // (J)V A: $1
    property AccessConfig : JParam_AccessConfig read _GetAccessConfig write _SetAccessConfig;// Lcom/zebra/ASCII_SDK/Param_AccessConfig; A: $1
    property ReportConfig : JParam_ReportConfig read _GetReportConfig write _SetReportConfig;// Lcom/zebra/ASCII_SDK/Param_ReportConfig; A: $1
  end;

  TJCommand_Read = class(TJavaGenericImport<JCommand_ReadClass, JCommand_Read>)
  end;

const
  TJCommand_ReadcommandName = 'Read';

implementation

end.
