//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagAccess_WriteSpecificFieldAccessParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Impinj;

type
  JTagAccess_WriteSpecificFieldAccessParams = interface;

  JTagAccess_WriteSpecificFieldAccessParamsClass = interface(JObjectClass)
    ['{D2DE968F-8316-4992-8EBA-ED1ED636F67C}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getWriteData : TJavaArray<Byte>; cdecl;                            // ()[B A: $1
    function getWriteDataLength : Integer; cdecl;                               // ()I A: $1
    function init(JTagAccessparam0 : JTagAccess) : JTagAccess_WriteSpecificFieldAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    function init(m_WriteData : TJavaArray<Byte>; m_nWriteDataLength : Integer; m_nAccessPassword : Int64) : JTagAccess_WriteSpecificFieldAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;[BIJ)V A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setWriteData(writeData : TJavaArray<Byte>) ; cdecl;               // ([B)V A: $1
    procedure setWriteDataLength(writeDataLength : Integer) ; cdecl;            // (I)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess_WriteSpecificFieldAccessParams')]
  JTagAccess_WriteSpecificFieldAccessParams = interface(JObject)
    ['{DC030FD9-AC04-4F57-9834-5CDC630DE0A1}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getWriteData : TJavaArray<Byte>; cdecl;                            // ()[B A: $1
    function getWriteDataLength : Integer; cdecl;                               // ()I A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setWriteData(writeData : TJavaArray<Byte>) ; cdecl;               // ([B)V A: $1
    procedure setWriteDataLength(writeDataLength : Integer) ; cdecl;            // (I)V A: $1
  end;

  TJTagAccess_WriteSpecificFieldAccessParams = class(TJavaGenericImport<JTagAccess_WriteSpecificFieldAccessParamsClass, JTagAccess_WriteSpecificFieldAccessParams>)
  end;

implementation

end.
