//
// Generated by JavaToPas v1.5 20170214 - 172216
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.ENUM_MODULATION;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JENUM_MODULATION = interface;

  JENUM_MODULATIONClass = interface(JObjectClass)
    ['{28FBE335-0B42-462F-A5BC-7525861587ED}']
    function _GetMV_2 : JENUM_MODULATION; cdecl;                                //  A: $4019
    function _GetMV_4 : JENUM_MODULATION; cdecl;                                //  A: $4019
    function _GetMV_8 : JENUM_MODULATION; cdecl;                                //  A: $4019
    function _GetMV_FM0 : JENUM_MODULATION; cdecl;                              //  A: $4019
    function getEnum(enumValS : JString) : JENUM_MODULATION; cdecl;             // (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $9
    function getEnumValue : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function valueOf(&name : JString) : JENUM_MODULATION; cdecl;                // (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $9
    function values : TJavaArray<JENUM_MODULATION>; cdecl;                      // ()[Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $9
    property MV_2 : JENUM_MODULATION read _GetMV_2;                             // Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $4019
    property MV_4 : JENUM_MODULATION read _GetMV_4;                             // Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $4019
    property MV_8 : JENUM_MODULATION read _GetMV_8;                             // Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $4019
    property MV_FM0 : JENUM_MODULATION read _GetMV_FM0;                         // Lcom/zebra/ASCII_SDK/ENUM_MODULATION; A: $4019
  end;

  [JavaSignature('com/zebra/ASCII_SDK/ENUM_MODULATION')]
  JENUM_MODULATION = interface(JObject)
    ['{EBDFABE6-BE86-4E4A-ABC9-FF7FCB68317E}']
    function getEnumValue : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
  end;

  TJENUM_MODULATION = class(TJavaGenericImport<JENUM_MODULATIONClass, JENUM_MODULATION>)
  end;

implementation

end.
