//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagAccess_WriteAccessParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.MEMORY_BANK,
  com.zebra.rfid.api3.Impinj;

type
  JTagAccess_WriteAccessParams = interface;

  JTagAccess_WriteAccessParamsClass = interface(JObjectClass)
    ['{E4776667-A9D6-492B-B2A8-A524411CC256}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getByteOffset : Integer; cdecl;                                    // ()I A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getStringWriteData : JString; cdecl;                               // ()Ljava/lang/String; A: $1
    function getWriteData : TJavaArray<Byte>; cdecl;                            // ()[B A: $1
    function getWriteDataLength : Integer; cdecl;                               // ()I A: $1
    function init(JTagAccessparam0 : JTagAccess) : JTagAccess_WriteAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    function init(m_eMemoryBank : JMEMORY_BANK; m_nByteOffset : Integer; m_nWriteDataLength : Integer; m_nAccessPassword : Int64; m_WriteData : TJavaArray<Byte>) : JTagAccess_WriteAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;Lcom/zebra/rfid/api3/MEMORY_BANK;IIJ[B)V A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setByteOffset(byteOffset : Integer) ; cdecl;                      // (I)V A: $1
    procedure setMemoryBank(memoryBank : JMEMORY_BANK) ; cdecl;                 // (Lcom/zebra/rfid/api3/MEMORY_BANK;)V A: $1
    procedure setWriteData(writeData : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
    procedure setWriteData(writeDataInStringFormat : JString) ; cdecl; overload;// (Ljava/lang/String;)V A: $1
    procedure setWriteDataLength(writeDataLength : Integer) ; cdecl;            // (I)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess_WriteAccessParams')]
  JTagAccess_WriteAccessParams = interface(JObject)
    ['{5CAD001E-9066-4E74-8A9B-42B8445FA7EE}']
    function getAccessPassword : Int64; cdecl;                                  // ()J A: $1
    function getByteOffset : Integer; cdecl;                                    // ()I A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getStringWriteData : JString; cdecl;                               // ()Ljava/lang/String; A: $1
    function getWriteData : TJavaArray<Byte>; cdecl;                            // ()[B A: $1
    function getWriteDataLength : Integer; cdecl;                               // ()I A: $1
    procedure setAccessPassword(accessPassword : Int64) ; cdecl;                // (J)V A: $1
    procedure setByteOffset(byteOffset : Integer) ; cdecl;                      // (I)V A: $1
    procedure setMemoryBank(memoryBank : JMEMORY_BANK) ; cdecl;                 // (Lcom/zebra/rfid/api3/MEMORY_BANK;)V A: $1
    procedure setWriteData(writeData : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
    procedure setWriteData(writeDataInStringFormat : JString) ; cdecl; overload;// (Ljava/lang/String;)V A: $1
    procedure setWriteDataLength(writeDataLength : Integer) ; cdecl;            // (I)V A: $1
  end;

  TJTagAccess_WriteAccessParams = class(TJavaGenericImport<JTagAccess_WriteAccessParamsClass, JTagAccess_WriteAccessParams>)
  end;

implementation

end.
