//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Events_BufferFullWarningEventData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Events;

type
  JEvents_BufferFullWarningEventData = interface;

  JEvents_BufferFullWarningEventDataClass = interface(JObjectClass)
    ['{BF31890A-5F7E-44FB-81A7-9F0D12DBF818}']
  end;

  [JavaSignature('com/zebra/rfid/api3/Events_BufferFullWarningEventData')]
  JEvents_BufferFullWarningEventData = interface(JObject)
    ['{BEAF0838-C7B8-4F60-A65C-EBCE52B3C1C8}']
  end;

  TJEvents_BufferFullWarningEventData = class(TJavaGenericImport<JEvents_BufferFullWarningEventDataClass, JEvents_BufferFullWarningEventData>)
  end;

implementation

end.
