//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ab;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jab = interface;

  JabClass = interface(JObjectClass)
    ['{8BFB0349-7B2E-447A-9630-39F0405723CB}']
  end;

  [JavaSignature('com/zebra/rfid/api3/ab')]
  Jab = interface(JObject)
    ['{E7EC2CE1-AE7B-48E0-96AF-4DE6B1679081}']
  end;

  TJab = class(TJavaGenericImport<JabClass, Jab>)
  end;

implementation

end.
