//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bw;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jbw = interface;

  JbwClass = interface(JObjectClass)
    ['{8DAAD3CD-A883-4141-8557-BEF71A70CEBE}']
    function _Geta : Jbw; cdecl;                                                //  A: $19
    function _Getb : Jbw; cdecl;                                                //  A: $19
    function _Getc : Jbw; cdecl;                                                //  A: $19
    function _Getd : Jbw; cdecl;                                                //  A: $19
    function _Gete : Jbw; cdecl;                                                //  A: $19
    function _Getf : Integer; cdecl;                                            //  A: $11
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property a : Jbw read _Geta;                                                // Lcom/zebra/rfid/api3/bw; A: $19
    property b : Jbw read _Getb;                                                // Lcom/zebra/rfid/api3/bw; A: $19
    property c : Jbw read _Getc;                                                // Lcom/zebra/rfid/api3/bw; A: $19
    property d : Jbw read _Getd;                                                // Lcom/zebra/rfid/api3/bw; A: $19
    property e : Jbw read _Gete;                                                // Lcom/zebra/rfid/api3/bw; A: $19
    property f : Integer read _Getf;                                            // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/bw')]
  Jbw = interface(JObject)
    ['{78E5ADB7-1835-4B55-8392-72153996B382}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJbw = class(TJavaGenericImport<JbwClass, Jbw>)
  end;

implementation

end.
