//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Constants;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JConstants = interface;

  JConstantsClass = interface(JObjectClass)
    ['{DFD4561B-4081-4402-9FEB-BEAE2AF5061C}']
    function _GetACTION_READER_AVAILABLE : JString; cdecl;                      //  A: $19
    function _GetACTION_READER_BATTERY_CHARGING : JString; cdecl;               //  A: $19
    function _GetACTION_READER_BATTERY_CRITICAL : JString; cdecl;               //  A: $19
    function _GetACTION_READER_BATTERY_LOW : JString; cdecl;                    //  A: $19
    function _GetACTION_READER_CONNECTED : JString; cdecl;                      //  A: $19
    function _GetACTION_READER_CONN_FAILED : JString; cdecl;                    //  A: $19
    function _GetACTION_READER_DISCONNECTED : JString; cdecl;                   //  A: $19
    function _GetACTION_READER_STATUS_OBTAINED : JString; cdecl;                //  A: $19
    function _GetAUTO_DETECT_READERS : JString; cdecl;                          //  A: $19
    function _GetAUTO_RECONNECTION_COUNT : Integer; cdecl;                      //  A: $19
    function _GetAUTO_RECONNECT_READERS : JString; cdecl;                       //  A: $19
    function _GetBATTERY_LEVEL_REQ_STRING : JString; cdecl;                     //  A: $19
    function _GetCOLLAPSED_HEIGHT : Integer; cdecl;                             //  A: $9
    function _GetCONNECTION_SETTINGS_STATUS : JString; cdecl;                   //  A: $19
    function _GetDATA_BLUETOOTH_DEVICE : JString; cdecl;                        //  A: $19
    function _GetDEBUG : boolean; cdecl;                                        //  A: $19
    function _GetDURATION : JString; cdecl;                                     //  A: $19
    function _GetEPC_MEMORY : JString; cdecl;                                   //  A: $19
    function _GetFILTER_1_ACTION : JString; cdecl;                              //  A: $19
    function _GetFILTER_1_ENABLED : JString; cdecl;                             //  A: $19
    function _GetFILTER_1_MEMORY_BANK : JString; cdecl;                         //  A: $19
    function _GetFILTER_1_OFFSET : JString; cdecl;                              //  A: $19
    function _GetFILTER_1_STATUS : JString; cdecl;                              //  A: $19
    function _GetFILTER_1_TAG_PATTERN : JString; cdecl;                         //  A: $19
    function _GetFILTER_1_TARGET : JString; cdecl;                              //  A: $19
    function _GetFILTER_2_ACTION : JString; cdecl;                              //  A: $19
    function _GetFILTER_2_ENABLED : JString; cdecl;                             //  A: $19
    function _GetFILTER_2_MEMORY_BANK : JString; cdecl;                         //  A: $19
    function _GetFILTER_2_OFFSET : JString; cdecl;                              //  A: $19
    function _GetFILTER_2_STATUS : JString; cdecl;                              //  A: $19
    function _GetFILTER_2_TAG_PATTERN : JString; cdecl;                         //  A: $19
    function _GetFILTER_2_TARGET : JString; cdecl;                              //  A: $19
    function _GetGENX_DEVICE : JString; cdecl;                                  //  A: $19
    function _GetHANDHELD : JString; cdecl;                                     //  A: $19
    function _GetIMMEDIATE : JString; cdecl;                                    //  A: $19
    function _GetINTENT_ACTION : JString; cdecl;                                //  A: $19
    function _GetINTENT_DATA : JString; cdecl;                                  //  A: $19
    function _GetINVENTORY_LIST_FONT_SIZE : Integer; cdecl;                     //  A: $9
    function _GetINVENTORY_LIST_MARGIN_SIZE : Integer; cdecl;                   //  A: $9
    function _GetLOCATE_TAG_EMPTY : JString; cdecl;                             //  A: $19
    function _GetNGE : JString; cdecl;                                          //  A: $19
    function _GetNOTIFICATIONS_ID : JString; cdecl;                             //  A: $19
    function _GetNOTIFICATIONS_TEXT : JString; cdecl;                           //  A: $19
    function _GetNOTIFY_BATTERY_STATUS : JString; cdecl;                        //  A: $19
    function _GetNOTIFY_READER_AVAILABLE : JString; cdecl;                      //  A: $19
    function _GetNOTIFY_READER_CONNECTION : JString; cdecl;                     //  A: $19
    function _GetN_ATTEMPTS : JString; cdecl;                                   //  A: $19
    function _GetOFF : JString; cdecl;                                          //  A: $19
    function _GetON : JString; cdecl;                                           //  A: $19
    function _GetPERIODIC : JString; cdecl;                                     //  A: $19
    function _GetRESERVED_MEMORY : JString; cdecl;                              //  A: $19
    function _GetRESPONSE_TIMEOUT : Integer; cdecl;                             //  A: $19
    function _GetSAVE_CONFIG_COMMAND_STRING : JString; cdecl;                   //  A: $19
    function _GetSETTING_ITEM_ID : JString; cdecl;                              //  A: $19
    function _GetSTART_TRIGGER_HANDHELD_PRESSED_CHECKED : JString; cdecl;       //  A: $19
    function _GetSTART_TRIGGER_HANDHELD_RELEASED_CHECKED : JString; cdecl;      //  A: $19
    function _GetSTART_TRIGGER_PERIODIC_DURATION : JString; cdecl;              //  A: $19
    function _GetSTART_TRIGGER_PERIODIC_START_TIME : JString; cdecl;            //  A: $19
    function _GetSTART_TRIGGER_STATUS : JString; cdecl;                         //  A: $19
    function _GetSTOP_TRIGGER_DURATION : JString; cdecl;                        //  A: $19
    function _GetSTOP_TRIGGER_HANDHELD_PRESSED_CHECKED : JString; cdecl;        //  A: $19
    function _GetSTOP_TRIGGER_HANDHELD_RELEASED_CHECKED : JString; cdecl;       //  A: $19
    function _GetSTOP_TRIGGER_HANDHELD_TIMEOUT : JString; cdecl;                //  A: $19
    function _GetSTOP_TRIGGER_N_ATTEMPTS_NO_OF_ATTEMPTS : JString; cdecl;       //  A: $19
    function _GetSTOP_TRIGGER_N_ATTEMPTS_TIMEOUT : JString; cdecl;              //  A: $19
    function _GetSTOP_TRIGGER_STATUS : JString; cdecl;                          //  A: $19
    function _GetSTOP_TRIGGER_TAG_OBSERVE_NO_OF_TAGS : JString; cdecl;          //  A: $19
    function _GetSTOP_TRIGGER_TAG_OBSERVE_TIMEOUT : JString; cdecl;             //  A: $19
    function _GetTAG_ID : JString; cdecl;                                       //  A: $19
    function _GetTAG_OBSERVATION : JString; cdecl;                              //  A: $19
    function _GetTAG_PREFS : JString; cdecl;                                    //  A: $19
    function _GetTAG_REPORT_CHANNEL_INDEX : JString; cdecl;                     //  A: $19
    function _GetTAG_REPORT_FIRST_SEEN_TIME : JString; cdecl;                   //  A: $19
    function _GetTAG_REPORT_LAST_SEEN_TIME : JString; cdecl;                    //  A: $19
    function _GetTAG_REPORT_PC : JString; cdecl;                                //  A: $19
    function _GetTAG_REPORT_PHASE : JString; cdecl;                             //  A: $19
    function _GetTAG_REPORT_RSSI : JString; cdecl;                              //  A: $19
    function _GetTAG_REPORT_STATUS : JString; cdecl;                            //  A: $19
    function _GetTAG_REPORT_TAG_SEEN_COUNT : JString; cdecl;                    //  A: $19
    function _GetTID_MEMORY : JString; cdecl;                                   //  A: $19
    function _GetTRIGGER_STATUS : JString; cdecl;                               //  A: $19
    function _GetTYPE_DEBUG : Integer; cdecl;                                   //  A: $19
    function _GetTYPE_ERROR : Integer; cdecl;                                   //  A: $19
    function _GetUNIQUE_TAG_LIMIT : Integer; cdecl;                             //  A: $19
    function _GetUSER_MEMORY : JString; cdecl;                                  //  A: $19
    function init : JConstants; cdecl;                                          // ()V A: $1
    property ACTION_READER_AVAILABLE : JString read _GetACTION_READER_AVAILABLE;// Ljava/lang/String; A: $19
    property ACTION_READER_BATTERY_CHARGING : JString read _GetACTION_READER_BATTERY_CHARGING;// Ljava/lang/String; A: $19
    property ACTION_READER_BATTERY_CRITICAL : JString read _GetACTION_READER_BATTERY_CRITICAL;// Ljava/lang/String; A: $19
    property ACTION_READER_BATTERY_LOW : JString read _GetACTION_READER_BATTERY_LOW;// Ljava/lang/String; A: $19
    property ACTION_READER_CONNECTED : JString read _GetACTION_READER_CONNECTED;// Ljava/lang/String; A: $19
    property ACTION_READER_CONN_FAILED : JString read _GetACTION_READER_CONN_FAILED;// Ljava/lang/String; A: $19
    property ACTION_READER_DISCONNECTED : JString read _GetACTION_READER_DISCONNECTED;// Ljava/lang/String; A: $19
    property ACTION_READER_STATUS_OBTAINED : JString read _GetACTION_READER_STATUS_OBTAINED;// Ljava/lang/String; A: $19
    property AUTO_DETECT_READERS : JString read _GetAUTO_DETECT_READERS;        // Ljava/lang/String; A: $19
    property AUTO_RECONNECTION_COUNT : Integer read _GetAUTO_RECONNECTION_COUNT;// I A: $19
    property AUTO_RECONNECT_READERS : JString read _GetAUTO_RECONNECT_READERS;  // Ljava/lang/String; A: $19
    property BATTERY_LEVEL_REQ_STRING : JString read _GetBATTERY_LEVEL_REQ_STRING;// Ljava/lang/String; A: $19
    property COLLAPSED_HEIGHT : Integer read _GetCOLLAPSED_HEIGHT;              // I A: $9
    property CONNECTION_SETTINGS_STATUS : JString read _GetCONNECTION_SETTINGS_STATUS;// Ljava/lang/String; A: $19
    property DATA_BLUETOOTH_DEVICE : JString read _GetDATA_BLUETOOTH_DEVICE;    // Ljava/lang/String; A: $19
    property DEBUG : boolean read _GetDEBUG;                                    // Z A: $19
    property DURATION : JString read _GetDURATION;                              // Ljava/lang/String; A: $19
    property EPC_MEMORY : JString read _GetEPC_MEMORY;                          // Ljava/lang/String; A: $19
    property FILTER_1_ACTION : JString read _GetFILTER_1_ACTION;                // Ljava/lang/String; A: $19
    property FILTER_1_ENABLED : JString read _GetFILTER_1_ENABLED;              // Ljava/lang/String; A: $19
    property FILTER_1_MEMORY_BANK : JString read _GetFILTER_1_MEMORY_BANK;      // Ljava/lang/String; A: $19
    property FILTER_1_OFFSET : JString read _GetFILTER_1_OFFSET;                // Ljava/lang/String; A: $19
    property FILTER_1_STATUS : JString read _GetFILTER_1_STATUS;                // Ljava/lang/String; A: $19
    property FILTER_1_TAG_PATTERN : JString read _GetFILTER_1_TAG_PATTERN;      // Ljava/lang/String; A: $19
    property FILTER_1_TARGET : JString read _GetFILTER_1_TARGET;                // Ljava/lang/String; A: $19
    property FILTER_2_ACTION : JString read _GetFILTER_2_ACTION;                // Ljava/lang/String; A: $19
    property FILTER_2_ENABLED : JString read _GetFILTER_2_ENABLED;              // Ljava/lang/String; A: $19
    property FILTER_2_MEMORY_BANK : JString read _GetFILTER_2_MEMORY_BANK;      // Ljava/lang/String; A: $19
    property FILTER_2_OFFSET : JString read _GetFILTER_2_OFFSET;                // Ljava/lang/String; A: $19
    property FILTER_2_STATUS : JString read _GetFILTER_2_STATUS;                // Ljava/lang/String; A: $19
    property FILTER_2_TAG_PATTERN : JString read _GetFILTER_2_TAG_PATTERN;      // Ljava/lang/String; A: $19
    property FILTER_2_TARGET : JString read _GetFILTER_2_TARGET;                // Ljava/lang/String; A: $19
    property GENX_DEVICE : JString read _GetGENX_DEVICE;                        // Ljava/lang/String; A: $19
    property HANDHELD : JString read _GetHANDHELD;                              // Ljava/lang/String; A: $19
    property IMMEDIATE : JString read _GetIMMEDIATE;                            // Ljava/lang/String; A: $19
    property INTENT_ACTION : JString read _GetINTENT_ACTION;                    // Ljava/lang/String; A: $19
    property INTENT_DATA : JString read _GetINTENT_DATA;                        // Ljava/lang/String; A: $19
    property INVENTORY_LIST_FONT_SIZE : Integer read _GetINVENTORY_LIST_FONT_SIZE;// I A: $9
    property INVENTORY_LIST_MARGIN_SIZE : Integer read _GetINVENTORY_LIST_MARGIN_SIZE;// I A: $9
    property LOCATE_TAG_EMPTY : JString read _GetLOCATE_TAG_EMPTY;              // Ljava/lang/String; A: $19
    property NGE : JString read _GetNGE;                                        // Ljava/lang/String; A: $19
    property NOTIFICATIONS_ID : JString read _GetNOTIFICATIONS_ID;              // Ljava/lang/String; A: $19
    property NOTIFICATIONS_TEXT : JString read _GetNOTIFICATIONS_TEXT;          // Ljava/lang/String; A: $19
    property NOTIFY_BATTERY_STATUS : JString read _GetNOTIFY_BATTERY_STATUS;    // Ljava/lang/String; A: $19
    property NOTIFY_READER_AVAILABLE : JString read _GetNOTIFY_READER_AVAILABLE;// Ljava/lang/String; A: $19
    property NOTIFY_READER_CONNECTION : JString read _GetNOTIFY_READER_CONNECTION;// Ljava/lang/String; A: $19
    property N_ATTEMPTS : JString read _GetN_ATTEMPTS;                          // Ljava/lang/String; A: $19
    property OFF : JString read _GetOFF;                                        // Ljava/lang/String; A: $19
    property ON : JString read _GetON;                                          // Ljava/lang/String; A: $19
    property PERIODIC : JString read _GetPERIODIC;                              // Ljava/lang/String; A: $19
    property RESERVED_MEMORY : JString read _GetRESERVED_MEMORY;                // Ljava/lang/String; A: $19
    property RESPONSE_TIMEOUT : Integer read _GetRESPONSE_TIMEOUT;              // I A: $19
    property SAVE_CONFIG_COMMAND_STRING : JString read _GetSAVE_CONFIG_COMMAND_STRING;// Ljava/lang/String; A: $19
    property SETTING_ITEM_ID : JString read _GetSETTING_ITEM_ID;                // Ljava/lang/String; A: $19
    property START_TRIGGER_HANDHELD_PRESSED_CHECKED : JString read _GetSTART_TRIGGER_HANDHELD_PRESSED_CHECKED;// Ljava/lang/String; A: $19
    property START_TRIGGER_HANDHELD_RELEASED_CHECKED : JString read _GetSTART_TRIGGER_HANDHELD_RELEASED_CHECKED;// Ljava/lang/String; A: $19
    property START_TRIGGER_PERIODIC_DURATION : JString read _GetSTART_TRIGGER_PERIODIC_DURATION;// Ljava/lang/String; A: $19
    property START_TRIGGER_PERIODIC_START_TIME : JString read _GetSTART_TRIGGER_PERIODIC_START_TIME;// Ljava/lang/String; A: $19
    property START_TRIGGER_STATUS : JString read _GetSTART_TRIGGER_STATUS;      // Ljava/lang/String; A: $19
    property STOP_TRIGGER_DURATION : JString read _GetSTOP_TRIGGER_DURATION;    // Ljava/lang/String; A: $19
    property STOP_TRIGGER_HANDHELD_PRESSED_CHECKED : JString read _GetSTOP_TRIGGER_HANDHELD_PRESSED_CHECKED;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_HANDHELD_RELEASED_CHECKED : JString read _GetSTOP_TRIGGER_HANDHELD_RELEASED_CHECKED;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_HANDHELD_TIMEOUT : JString read _GetSTOP_TRIGGER_HANDHELD_TIMEOUT;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_N_ATTEMPTS_NO_OF_ATTEMPTS : JString read _GetSTOP_TRIGGER_N_ATTEMPTS_NO_OF_ATTEMPTS;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_N_ATTEMPTS_TIMEOUT : JString read _GetSTOP_TRIGGER_N_ATTEMPTS_TIMEOUT;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_STATUS : JString read _GetSTOP_TRIGGER_STATUS;        // Ljava/lang/String; A: $19
    property STOP_TRIGGER_TAG_OBSERVE_NO_OF_TAGS : JString read _GetSTOP_TRIGGER_TAG_OBSERVE_NO_OF_TAGS;// Ljava/lang/String; A: $19
    property STOP_TRIGGER_TAG_OBSERVE_TIMEOUT : JString read _GetSTOP_TRIGGER_TAG_OBSERVE_TIMEOUT;// Ljava/lang/String; A: $19
    property TAG_ID : JString read _GetTAG_ID;                                  // Ljava/lang/String; A: $19
    property TAG_OBSERVATION : JString read _GetTAG_OBSERVATION;                // Ljava/lang/String; A: $19
    property TAG_PREFS : JString read _GetTAG_PREFS;                            // Ljava/lang/String; A: $19
    property TAG_REPORT_CHANNEL_INDEX : JString read _GetTAG_REPORT_CHANNEL_INDEX;// Ljava/lang/String; A: $19
    property TAG_REPORT_FIRST_SEEN_TIME : JString read _GetTAG_REPORT_FIRST_SEEN_TIME;// Ljava/lang/String; A: $19
    property TAG_REPORT_LAST_SEEN_TIME : JString read _GetTAG_REPORT_LAST_SEEN_TIME;// Ljava/lang/String; A: $19
    property TAG_REPORT_PC : JString read _GetTAG_REPORT_PC;                    // Ljava/lang/String; A: $19
    property TAG_REPORT_PHASE : JString read _GetTAG_REPORT_PHASE;              // Ljava/lang/String; A: $19
    property TAG_REPORT_RSSI : JString read _GetTAG_REPORT_RSSI;                // Ljava/lang/String; A: $19
    property TAG_REPORT_STATUS : JString read _GetTAG_REPORT_STATUS;            // Ljava/lang/String; A: $19
    property TAG_REPORT_TAG_SEEN_COUNT : JString read _GetTAG_REPORT_TAG_SEEN_COUNT;// Ljava/lang/String; A: $19
    property TID_MEMORY : JString read _GetTID_MEMORY;                          // Ljava/lang/String; A: $19
    property TRIGGER_STATUS : JString read _GetTRIGGER_STATUS;                  // Ljava/lang/String; A: $19
    property TYPE_DEBUG : Integer read _GetTYPE_DEBUG;                          // I A: $19
    property TYPE_ERROR : Integer read _GetTYPE_ERROR;                          // I A: $19
    property UNIQUE_TAG_LIMIT : Integer read _GetUNIQUE_TAG_LIMIT;              // I A: $19
    property USER_MEMORY : JString read _GetUSER_MEMORY;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/rfid/api3/Constants')]
  JConstants = interface(JObject)
    ['{B2C9D73D-C92B-414B-BBF6-AFEDDA257E6B}']
  end;

  TJConstants = class(TJavaGenericImport<JConstantsClass, JConstants>)
  end;

const
  TJConstantsIMMEDIATE = 'Immediate';
  TJConstantsHANDHELD = 'Handheld';
  TJConstantsPERIODIC = 'Periodic';
  TJConstantsDURATION = 'Duration';
  TJConstantsTAG_OBSERVATION = 'Tag Observation';
  TJConstantsN_ATTEMPTS = 'N attempts';
  TJConstantsDEBUG = 0;
  TJConstantsTYPE_DEBUG = 60;
  TJConstantsTYPE_ERROR = 61;
  TJConstantsINTENT_ACTION = 'intent_action';
  TJConstantsINTENT_DATA = 'intent_data';
  TJConstantsACTION_READER_BATTERY_LOW = 'battery.low';
  TJConstantsACTION_READER_BATTERY_CRITICAL = 'battery.critical';
  TJConstantsACTION_READER_BATTERY_CHARGING = 'battery.charging';
  TJConstantsACTION_READER_CONNECTED = 'connected';
  TJConstantsACTION_READER_DISCONNECTED = 'disconnected';
  TJConstantsACTION_READER_AVAILABLE = 'available';
  TJConstantsACTION_READER_CONN_FAILED = 'connection.failed';
  TJConstantsACTION_READER_STATUS_OBTAINED = 'status.received';
  TJConstantsDATA_BLUETOOTH_DEVICE = 'com.rfid.data.bluetooth.device';
  TJConstantsNOTIFICATIONS_TEXT = 'notifications_text';
  TJConstantsNOTIFICATIONS_ID = 'notifications_id';
  TJConstantsAUTO_RECONNECTION_COUNT = 5;
  TJConstantsRESPONSE_TIMEOUT = 6000;
  TJConstantsTAG_PREFS = 'TagPrefsFile';
  TJConstantsTAG_ID = 'tagID';
  TJConstantsTAG_REPORT_STATUS = 'TagReportingStatus';
  TJConstantsTAG_REPORT_FIRST_SEEN_TIME = 'TagReportFirstSeenTime';
  TJConstantsTAG_REPORT_LAST_SEEN_TIME = 'TagReportLastSeenTime';
  TJConstantsTAG_REPORT_PC = 'TagReportPC';
  TJConstantsTAG_REPORT_RSSI = 'TagReportRSSI';
  TJConstantsTAG_REPORT_PHASE = 'TagReportPhase';
  TJConstantsTAG_REPORT_CHANNEL_INDEX = 'TagReportChannelIndex';
  TJConstantsTAG_REPORT_TAG_SEEN_COUNT = 'TagReportTagSeen';
  TJConstantsCONNECTION_SETTINGS_STATUS = 'ConnectionSettingStatus';
  TJConstantsAUTO_DETECT_READERS = 'AutoDetectReaders';
  TJConstantsAUTO_RECONNECT_READERS = 'AutoReconnectReaders';
  TJConstantsNOTIFY_READER_AVAILABLE = 'NotifyReaderAvailable';
  TJConstantsNOTIFY_READER_CONNECTION = 'NotifyReaderConnection';
  TJConstantsNOTIFY_BATTERY_STATUS = 'NotifyBatteryStatus';
  TJConstantsTRIGGER_STATUS = 'TriggersStatus';
  TJConstantsSTART_TRIGGER_STATUS = 'StartTriggersStatus';
  TJConstantsSTART_TRIGGER_HANDHELD_RELEASED_CHECKED = 'StartTriggersHandheldReleased';
  TJConstantsSTART_TRIGGER_HANDHELD_PRESSED_CHECKED = 'StartTriggersHandheldPressed';
  TJConstantsSTART_TRIGGER_PERIODIC_START_TIME = 'StartTriggersPeriodicStartTime';
  TJConstantsSTART_TRIGGER_PERIODIC_DURATION = 'StartTriggersPeriodicDuration';
  TJConstantsSTOP_TRIGGER_STATUS = 'StopTriggersStatus';
  TJConstantsSTOP_TRIGGER_HANDHELD_RELEASED_CHECKED = 'StopTriggersHandheldReleased';
  TJConstantsSTOP_TRIGGER_HANDHELD_PRESSED_CHECKED = 'StopTriggersHandheldPressed';
  TJConstantsSTOP_TRIGGER_HANDHELD_TIMEOUT = 'StopTriggersHandheldTimeout';
  TJConstantsSTOP_TRIGGER_DURATION = 'StopTriggersDuration';
  TJConstantsSTOP_TRIGGER_TAG_OBSERVE_NO_OF_TAGS = 'StopTriggersTagObserveNoOfTags';
  TJConstantsSTOP_TRIGGER_TAG_OBSERVE_TIMEOUT = 'StopTriggersTagObserveTimeout';
  TJConstantsSTOP_TRIGGER_N_ATTEMPTS_NO_OF_ATTEMPTS = 'StopTriggersNAttemptsNoOfAttemps';
  TJConstantsSTOP_TRIGGER_N_ATTEMPTS_TIMEOUT = 'StopTriggersNAttemptsTimeout';
  TJConstantsFILTER_1_STATUS = 'Filter1Status';
  TJConstantsFILTER_1_TAG_PATTERN = 'Filter1TagPattern';
  TJConstantsFILTER_1_MEMORY_BANK = 'Filter1MemoryBank';
  TJConstantsFILTER_1_OFFSET = 'Filter1Offset';
  TJConstantsFILTER_1_ACTION = 'Filter1Action';
  TJConstantsFILTER_1_TARGET = 'Filter1Target';
  TJConstantsFILTER_1_ENABLED = 'Filter1Enabled';
  TJConstantsFILTER_2_STATUS = 'Filter2Status';
  TJConstantsFILTER_2_TAG_PATTERN = 'Filter2TagPattern';
  TJConstantsFILTER_2_MEMORY_BANK = 'Filter2MemoryBank';
  TJConstantsFILTER_2_OFFSET = 'Filter2Offset';
  TJConstantsFILTER_2_ACTION = 'Filter2Action';
  TJConstantsFILTER_2_TARGET = 'Filter2Target';
  TJConstantsFILTER_2_ENABLED = 'Filter2Enabled';
  TJConstantsSETTING_ITEM_ID = 'settingItemId';
  TJConstantsBATTERY_LEVEL_REQ_STRING = 'getdevicestatus .batterylevel';
  TJConstantsSAVE_CONFIG_COMMAND_STRING = 'saveconfig ';
  TJConstantsEPC_MEMORY = 'EPC MEMORY';
  TJConstantsTID_MEMORY = 'TID MEMORY';
  TJConstantsUSER_MEMORY = 'USER MEMORY';
  TJConstantsRESERVED_MEMORY = 'RESERVED MEMORY';
  TJConstantsUNIQUE_TAG_LIMIT = 30000;
  TJConstantsON = 'ENABLE';
  TJConstantsOFF = 'DISABLE';
  TJConstantsNGE = 'NGE';
  TJConstantsGENX_DEVICE = 'GENX_DEVICE';
  TJConstantsLOCATE_TAG_EMPTY = 'Please fill Tag Id';

implementation

end.
