//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ay;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jay = interface;

  JayClass = interface(JObjectClass)
    ['{E0AC7A6C-EF72-417D-AF09-DDD596C7FA9F}']
    function a : Integer; cdecl; overload;                                      // ()I A: $1
    procedure a(Integerparam0 : Integer) ; cdecl; overload;                     // (I)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ay')]
  Jay = interface(JObject)
    ['{C835CF49-2334-474A-B21D-9A47F4F9D3F0}']
    function a : Integer; cdecl; overload;                                      // ()I A: $1
    procedure a(Integerparam0 : Integer) ; cdecl; overload;                     // (I)V A: $1
  end;

  TJay = class(TJavaGenericImport<JayClass, Jay>)
  end;

implementation

end.
