//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ReaderInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JReaderInfo = interface;

  JReaderInfoClass = interface(JObjectClass)
    ['{2764C1E2-076D-4CB6-A9D2-825A5FCEE01A}']
    function getContact : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getDescription : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function getLocation : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function init : JReaderInfo; cdecl; overload;                               // ()V A: $1
    function init(&name : JString; description : JString; location : JString; contact : JString) : JReaderInfo; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V A: $1
    procedure setContact(contact : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
    procedure setDescription(description : JString) ; cdecl;                    // (Ljava/lang/String;)V A: $1
    procedure setLocation(location : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setName(m_sName : JString) ; cdecl;                               // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ReaderInfo')]
  JReaderInfo = interface(JObject)
    ['{EA9B979E-7EB5-4795-9647-1559723C2040}']
    function getContact : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getDescription : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function getLocation : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    procedure setContact(contact : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
    procedure setDescription(description : JString) ; cdecl;                    // (Ljava/lang/String;)V A: $1
    procedure setLocation(location : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setName(m_sName : JString) ; cdecl;                               // (Ljava/lang/String;)V A: $1
  end;

  TJReaderInfo = class(TJavaGenericImport<JReaderInfoClass, JReaderInfo>)
  end;

implementation

end.
