//
// Generated by JavaToPas v1.5 20170214 - 172216
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Notification_BatteryEvent;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.NOTIFICATION_TYPE;

type
  JNotification_BatteryEvent = interface;

  JNotification_BatteryEventClass = interface(JObjectClass)
    ['{09872577-69B5-40FD-8FA3-2FEAFD6ED30F}']
    function FromString(str : JString) : JNotification_BatteryEvent; cdecl;     // (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/Notification_BatteryEvent; A: $9
    function _GetCause : JString; cdecl;                                        //  A: $1
    function _GetCharging : boolean; cdecl;                                     //  A: $1
    function _GetLevel : Integer; cdecl;                                        //  A: $1
    function getNotificationType : JNOTIFICATION_TYPE; cdecl;                   // ()Lcom/zebra/ASCII_SDK/NOTIFICATION_TYPE; A: $1
    function init : JNotification_BatteryEvent; cdecl;                          // ()V A: $1
    procedure _SetCause(Value : JString) ; cdecl;                               //  A: $1
    procedure _SetCharging(Value : boolean) ; cdecl;                            //  A: $1
    procedure _SetLevel(Value : Integer) ; cdecl;                               //  A: $1
    property Cause : JString read _GetCause write _SetCause;                    // Ljava/lang/String; A: $1
    property Charging : boolean read _GetCharging write _SetCharging;           // Z A: $1
    property Level : Integer read _GetLevel write _SetLevel;                    // I A: $1
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Notification_BatteryEvent')]
  JNotification_BatteryEvent = interface(JObject)
    ['{AF8E0CE7-C68A-4461-9C9D-A14278952793}']
    function _GetCause : JString; cdecl;                                        //  A: $1
    function _GetCharging : boolean; cdecl;                                     //  A: $1
    function _GetLevel : Integer; cdecl;                                        //  A: $1
    function getNotificationType : JNOTIFICATION_TYPE; cdecl;                   // ()Lcom/zebra/ASCII_SDK/NOTIFICATION_TYPE; A: $1
    procedure _SetCause(Value : JString) ; cdecl;                               //  A: $1
    procedure _SetCharging(Value : boolean) ; cdecl;                            //  A: $1
    procedure _SetLevel(Value : Integer) ; cdecl;                               //  A: $1
    property Cause : JString read _GetCause write _SetCause;                    // Ljava/lang/String; A: $1
    property Charging : boolean read _GetCharging write _SetCharging;           // Z A: $1
    property Level : Integer read _GetLevel write _SetLevel;                    // I A: $1
  end;

  TJNotification_BatteryEvent = class(TJavaGenericImport<JNotification_BatteryEventClass, JNotification_BatteryEvent>)
  end;

implementation

end.
