//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Events_InventoryStopEventData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Events;

type
  JEvents_InventoryStopEventData = interface;

  JEvents_InventoryStopEventDataClass = interface(JObjectClass)
    ['{5D1EACA5-B321-4BEF-A186-5099C1CE6E29}']
  end;

  [JavaSignature('com/zebra/rfid/api3/Events_InventoryStopEventData')]
  JEvents_InventoryStopEventData = interface(JObject)
    ['{DECE0FE2-0CA4-4210-AD0D-F801044CC631}']
  end;

  TJEvents_InventoryStopEventData = class(TJavaGenericImport<JEvents_InventoryStopEventDataClass, JEvents_InventoryStopEventData>)
  end;

implementation

end.
