//
// Generated by JavaToPas v1.5 20170214 - 172215
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_GetSupportedLinkprofiles;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_GetSupportedLinkprofiles = interface;

  JCommand_GetSupportedLinkprofilesClass = interface(JObjectClass)
    ['{A1BD4BF6-F060-46DE-B007-5CE6BB4FC2B5}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function init : JCommand_GetSupportedLinkprofiles; cdecl;                   // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_GetSupportedLinkprofiles')]
  JCommand_GetSupportedLinkprofiles = interface(JObject)
    ['{3B06009B-1D12-4677-9EB5-36C810977594}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
  end;

  TJCommand_GetSupportedLinkprofiles = class(TJavaGenericImport<JCommand_GetSupportedLinkprofilesClass, JCommand_GetSupportedLinkprofiles>)
  end;

const
  TJCommand_GetSupportedLinkprofilescommandName = 'GetSupportedLinkprofiles';

implementation

end.
