//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ReaderManagement;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Profile,
  com.zebra.rfid.api3.UserApp,
  com.zebra.rfid.api3.LLRPConnection,
  com.zebra.rfid.api3.ReadPoint,
  com.zebra.rfid.api3.TimeZone,
  com.zebra.rfid.api3.ANTENNA_MODE,
  com.zebra.rfid.api3.RadioFirmwareUpdate,
  com.zebra.rfid.api3.RadioConfigUpdate,
  com.zebra.rfid.api3.SoftwareUpdate,
  java.util.Vector,
  com.zebra.rfid.api3.SYSTEMTIME,
  com.zebra.rfid.api3.ReaderInfo,
  com.zebra.rfid.api3.USBOperationMode,
  com.zebra.rfid.api3.TRACE_LEVEL,
  com.zebra.rfid.api3.LoginInfo,
  com.zebra.rfid.api3.READER_TYPE,
  com.zebra.rfid.api3.SystemInfo,
  com.zebra.rfid.api3.HEALTH_STATUS,
  com.zebra.rfid.api3.SERVICE_ID,
  com.zebra.rfid.api3.LedInfo,
  com.zebra.rfid.api3.ReaderStatistics,
  com.zebra.rfid.api3.CableLossCompensation;

type
  JReaderManagement = interface;

  JReaderManagementClass = interface(JObjectClass)
    ['{B62A9036-2AD0-4773-B29C-DD6001CDE29A}']
    function _GetLLRPConnection : JLLRPConnection; cdecl;                       //  A: $1
    function _GetProfile : JProfile; cdecl;                                     //  A: $1
    function _GetReadPoint : JReadPoint; cdecl;                                 //  A: $1
    function _GetTimeZone : JTimeZone; cdecl;                                   //  A: $1
    function _GetUserApp : JUserApp; cdecl;                                     //  A: $1
    function clearReaderStatistics : boolean; cdecl;                            // ()Z A: $1
    function getAntennaMode : JANTENNA_MODE; cdecl;                             // ()Lcom/zebra/rfid/api3/ANTENNA_MODE; A: $1
    function getCableLossCompensation(antennaID : Integer) : JCableLossCompensation; cdecl;// (I)Lcom/zebra/rfid/api3/CableLossCompensation; A: $1
    function getGPIDebounceTimeMilliseconds : Integer; cdecl;                   // ()I A: $1
    function getHealthStatus(serviceID : JSERVICE_ID) : JHEALTH_STATUS; cdecl;  // (Lcom/zebra/rfid/api3/SERVICE_ID;)Lcom/zebra/rfid/api3/HEALTH_STATUS; A: $1
    function getLocalTime : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function getRadioConfigUpdate : JRadioConfigUpdate; cdecl;                  // ()Lcom/zebra/rfid/api3/RadioConfigUpdate; A: $1
    function getRadioFirmwareUpdate : JRadioFirmwareUpdate; cdecl;              // ()Lcom/zebra/rfid/api3/RadioFirmwareUpdate; A: $1
    function getRadioIdleTimeout : Integer; cdecl;                              // ()I A: $1
    function getReaderInfo : JReaderInfo; cdecl;                                // ()Lcom/zebra/rfid/api3/ReaderInfo; A: $1
    function getReaderStatistics(antennaID : SmallInt) : JReaderStatistics; cdecl;// (S)Lcom/zebra/rfid/api3/ReaderStatistics; A: $1
    function getSoftwareUpdate : JSoftwareUpdate; cdecl;                        // ()Lcom/zebra/rfid/api3/SoftwareUpdate; A: $1
    function getSystemInfo : JSystemInfo; cdecl;                                // ()Lcom/zebra/rfid/api3/SystemInfo; A: $1
    function getTraceLevel : TJavaArray<JTRACE_LEVEL>; cdecl;                   // ()[Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $1
    function getUSBOperationMode : JUSBOperationMode; cdecl;                    // ()Lcom/zebra/rfid/api3/USBOperationMode; A: $1
    function init : JReaderManagement; cdecl;                                   // ()V A: $1
    function isLoggedIn : boolean; cdecl;                                       // ()Z A: $1
    procedure _SetLLRPConnection(Value : JLLRPConnection) ; cdecl;              //  A: $1
    procedure _SetProfile(Value : JProfile) ; cdecl;                            //  A: $1
    procedure _SetReadPoint(Value : JReadPoint) ; cdecl;                        //  A: $1
    procedure _SetTimeZone(Value : JTimeZone) ; cdecl;                          //  A: $1
    procedure _SetUserApp(Value : JUserApp) ; cdecl;                            //  A: $1
    procedure dispose ; cdecl;                                                  // ()V A: $1
    procedure login(loginInfo : JLoginInfo; readerType : JREADER_TYPE) ; cdecl; // (Lcom/zebra/rfid/api3/LoginInfo;Lcom/zebra/rfid/api3/READER_TYPE;)V A: $1
    procedure logout ; cdecl;                                                   // ()V A: $1
    procedure restart ; cdecl;                                                  // ()V A: $1
    procedure setAntennaMode(antennaMode : JANTENNA_MODE) ; cdecl;              // (Lcom/zebra/rfid/api3/ANTENNA_MODE;)V A: $1
    procedure setCableLossCompensation(cableLossCompensationInfo : TJavaArray<JCableLossCompensation>) ; cdecl;// ([Lcom/zebra/rfid/api3/CableLossCompensation;)V A: $1
    procedure setGPIDebounceTimeMilliseconds(gpiDebounceTimeMilliseconds : Integer) ; cdecl;// (I)V A: $1
    procedure setLocalTime(localTime : JSYSTEMTIME) ; cdecl;                    // (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setReaderInfo(readerInfo : JReaderInfo) ; cdecl;                  // (Lcom/zebra/rfid/api3/ReaderInfo;)V A: $1
    procedure setTraceLevel(arrTraceLevel : TJavaArray<JTRACE_LEVEL>) ; cdecl; overload;// ([Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setTraceLevel(traceLevel : JTRACE_LEVEL) ; cdecl; overload;       // (Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setUSBOperationMode(usbOperationMode : JUSBOperationMode) ; cdecl;// (Lcom/zebra/rfid/api3/USBOperationMode;)V A: $1
    procedure setUserLED(ledInfo : JLedInfo) ; cdecl;                           // (Lcom/zebra/rfid/api3/LedInfo;)V A: $1
    procedure turnOffRadiowhenIdle(idleTimeout : Integer) ; cdecl;              // (I)V A: $1
    property LLRPConnection : JLLRPConnection read _GetLLRPConnection write _SetLLRPConnection;// Lcom/zebra/rfid/api3/LLRPConnection; A: $1
    property Profile : JProfile read _GetProfile write _SetProfile;             // Lcom/zebra/rfid/api3/Profile; A: $1
    property ReadPoint : JReadPoint read _GetReadPoint write _SetReadPoint;     // Lcom/zebra/rfid/api3/ReadPoint; A: $1
    property TimeZone : JTimeZone read _GetTimeZone write _SetTimeZone;         // Lcom/zebra/rfid/api3/TimeZone; A: $1
    property UserApp : JUserApp read _GetUserApp write _SetUserApp;             // Lcom/zebra/rfid/api3/UserApp; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ReaderManagement')]
  JReaderManagement = interface(JObject)
    ['{048BD91D-47E6-4F7E-8020-7D35429990BA}']
    function _GetLLRPConnection : JLLRPConnection; cdecl;                       //  A: $1
    function _GetProfile : JProfile; cdecl;                                     //  A: $1
    function _GetReadPoint : JReadPoint; cdecl;                                 //  A: $1
    function _GetTimeZone : JTimeZone; cdecl;                                   //  A: $1
    function _GetUserApp : JUserApp; cdecl;                                     //  A: $1
    function clearReaderStatistics : boolean; cdecl;                            // ()Z A: $1
    function getAntennaMode : JANTENNA_MODE; cdecl;                             // ()Lcom/zebra/rfid/api3/ANTENNA_MODE; A: $1
    function getCableLossCompensation(antennaID : Integer) : JCableLossCompensation; cdecl;// (I)Lcom/zebra/rfid/api3/CableLossCompensation; A: $1
    function getGPIDebounceTimeMilliseconds : Integer; cdecl;                   // ()I A: $1
    function getHealthStatus(serviceID : JSERVICE_ID) : JHEALTH_STATUS; cdecl;  // (Lcom/zebra/rfid/api3/SERVICE_ID;)Lcom/zebra/rfid/api3/HEALTH_STATUS; A: $1
    function getLocalTime : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function getRadioConfigUpdate : JRadioConfigUpdate; cdecl;                  // ()Lcom/zebra/rfid/api3/RadioConfigUpdate; A: $1
    function getRadioFirmwareUpdate : JRadioFirmwareUpdate; cdecl;              // ()Lcom/zebra/rfid/api3/RadioFirmwareUpdate; A: $1
    function getRadioIdleTimeout : Integer; cdecl;                              // ()I A: $1
    function getReaderInfo : JReaderInfo; cdecl;                                // ()Lcom/zebra/rfid/api3/ReaderInfo; A: $1
    function getReaderStatistics(antennaID : SmallInt) : JReaderStatistics; cdecl;// (S)Lcom/zebra/rfid/api3/ReaderStatistics; A: $1
    function getSoftwareUpdate : JSoftwareUpdate; cdecl;                        // ()Lcom/zebra/rfid/api3/SoftwareUpdate; A: $1
    function getSystemInfo : JSystemInfo; cdecl;                                // ()Lcom/zebra/rfid/api3/SystemInfo; A: $1
    function getTraceLevel : TJavaArray<JTRACE_LEVEL>; cdecl;                   // ()[Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $1
    function getUSBOperationMode : JUSBOperationMode; cdecl;                    // ()Lcom/zebra/rfid/api3/USBOperationMode; A: $1
    function isLoggedIn : boolean; cdecl;                                       // ()Z A: $1
    procedure _SetLLRPConnection(Value : JLLRPConnection) ; cdecl;              //  A: $1
    procedure _SetProfile(Value : JProfile) ; cdecl;                            //  A: $1
    procedure _SetReadPoint(Value : JReadPoint) ; cdecl;                        //  A: $1
    procedure _SetTimeZone(Value : JTimeZone) ; cdecl;                          //  A: $1
    procedure _SetUserApp(Value : JUserApp) ; cdecl;                            //  A: $1
    procedure dispose ; cdecl;                                                  // ()V A: $1
    procedure login(loginInfo : JLoginInfo; readerType : JREADER_TYPE) ; cdecl; // (Lcom/zebra/rfid/api3/LoginInfo;Lcom/zebra/rfid/api3/READER_TYPE;)V A: $1
    procedure logout ; cdecl;                                                   // ()V A: $1
    procedure restart ; cdecl;                                                  // ()V A: $1
    procedure setAntennaMode(antennaMode : JANTENNA_MODE) ; cdecl;              // (Lcom/zebra/rfid/api3/ANTENNA_MODE;)V A: $1
    procedure setCableLossCompensation(cableLossCompensationInfo : TJavaArray<JCableLossCompensation>) ; cdecl;// ([Lcom/zebra/rfid/api3/CableLossCompensation;)V A: $1
    procedure setGPIDebounceTimeMilliseconds(gpiDebounceTimeMilliseconds : Integer) ; cdecl;// (I)V A: $1
    procedure setLocalTime(localTime : JSYSTEMTIME) ; cdecl;                    // (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setReaderInfo(readerInfo : JReaderInfo) ; cdecl;                  // (Lcom/zebra/rfid/api3/ReaderInfo;)V A: $1
    procedure setTraceLevel(arrTraceLevel : TJavaArray<JTRACE_LEVEL>) ; cdecl; overload;// ([Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setTraceLevel(traceLevel : JTRACE_LEVEL) ; cdecl; overload;       // (Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setUSBOperationMode(usbOperationMode : JUSBOperationMode) ; cdecl;// (Lcom/zebra/rfid/api3/USBOperationMode;)V A: $1
    procedure setUserLED(ledInfo : JLedInfo) ; cdecl;                           // (Lcom/zebra/rfid/api3/LedInfo;)V A: $1
    procedure turnOffRadiowhenIdle(idleTimeout : Integer) ; cdecl;              // (I)V A: $1
    property LLRPConnection : JLLRPConnection read _GetLLRPConnection write _SetLLRPConnection;// Lcom/zebra/rfid/api3/LLRPConnection; A: $1
    property Profile : JProfile read _GetProfile write _SetProfile;             // Lcom/zebra/rfid/api3/Profile; A: $1
    property ReadPoint : JReadPoint read _GetReadPoint write _SetReadPoint;     // Lcom/zebra/rfid/api3/ReadPoint; A: $1
    property TimeZone : JTimeZone read _GetTimeZone write _SetTimeZone;         // Lcom/zebra/rfid/api3/TimeZone; A: $1
    property UserApp : JUserApp read _GetUserApp write _SetUserApp;             // Lcom/zebra/rfid/api3/UserApp; A: $1
  end;

  TJReaderManagement = class(TJavaGenericImport<JReaderManagementClass, JReaderManagement>)
  end;

implementation

end.
