//
// Generated by JavaToPas v1.5 20170214 - 172216
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Notification;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.MSG_TYPE,
  com.zebra.ASCII_SDK.NOTIFICATION_TYPE;

type
  JNotification = interface;

  JNotificationClass = interface(JObjectClass)
    ['{30FBACB1-EA8E-45D6-B383-9BF2FF7B7B5F}']
    function getMsgType : JMSG_TYPE; cdecl;                                     // ()Lcom/zebra/ASCII_SDK/MSG_TYPE; A: $1
    function getNotificationType : JNOTIFICATION_TYPE; cdecl;                   // ()Lcom/zebra/ASCII_SDK/NOTIFICATION_TYPE; A: $401
    function init : JNotification; cdecl;                                       // ()V A: $1
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Notification')]
  JNotification = interface(JObject)
    ['{4CDA720F-1F92-49EC-9EA0-26320B7325C6}']
    function getMsgType : JMSG_TYPE; cdecl;                                     // ()Lcom/zebra/ASCII_SDK/MSG_TYPE; A: $1
    function getNotificationType : JNOTIFICATION_TYPE; cdecl;                   // ()Lcom/zebra/ASCII_SDK/NOTIFICATION_TYPE; A: $401
  end;

  TJNotification = class(TJavaGenericImport<JNotificationClass, JNotification>)
  end;

implementation

end.
