//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagPatternBase;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.MEMORY_BANK;

type
  JTagPatternBase = interface;

  JTagPatternBaseClass = interface(JObjectClass)
    ['{37AB1C23-2F5B-48E5-9886-6CF1E6443B38}']
    function getBitOffset : Integer; cdecl;                                     // ()I A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getStringTagMask : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
    function getStringTagPattern : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function getTagMask : TJavaArray<Byte>; cdecl;                              // ()[B A: $1
    function getTagMaskBitCount : Integer; cdecl;                               // ()I A: $1
    function getTagPattern : TJavaArray<Byte>; cdecl;                           // ()[B A: $1
    function getTagPatternBitCount : Integer; cdecl;                            // ()I A: $1
    function init : JTagPatternBase; cdecl;                                     // ()V A: $1
    procedure setBitOffset(bitOffset : Integer) ; cdecl;                        // (I)V A: $1
    procedure setMemoryBank(memoryBank : JMEMORY_BANK) ; cdecl;                 // (Lcom/zebra/rfid/api3/MEMORY_BANK;)V A: $1
    procedure setTagMask(tagMask : JString) ; cdecl; overload;                  // (Ljava/lang/String;)V A: $1
    procedure setTagMask(tagMask : TJavaArray<Byte>) ; cdecl; overload;         // ([B)V A: $1
    procedure setTagMaskBitCount(tagMaskBitCount : Integer) ; cdecl;            // (I)V A: $1
    procedure setTagPattern(tagPattern : JString) ; cdecl; overload;            // (Ljava/lang/String;)V A: $1
    procedure setTagPattern(tagPattern : TJavaArray<Byte>) ; cdecl; overload;   // ([B)V A: $1
    procedure setTagPatternBitCount(tagPatternBitCount : Integer) ; cdecl;      // (I)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagPatternBase')]
  JTagPatternBase = interface(JObject)
    ['{13CEE0DA-C82E-4F82-BD80-912D4F69B47B}']
    function getBitOffset : Integer; cdecl;                                     // ()I A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getStringTagMask : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
    function getStringTagPattern : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function getTagMask : TJavaArray<Byte>; cdecl;                              // ()[B A: $1
    function getTagMaskBitCount : Integer; cdecl;                               // ()I A: $1
    function getTagPattern : TJavaArray<Byte>; cdecl;                           // ()[B A: $1
    function getTagPatternBitCount : Integer; cdecl;                            // ()I A: $1
    procedure setBitOffset(bitOffset : Integer) ; cdecl;                        // (I)V A: $1
    procedure setMemoryBank(memoryBank : JMEMORY_BANK) ; cdecl;                 // (Lcom/zebra/rfid/api3/MEMORY_BANK;)V A: $1
    procedure setTagMask(tagMask : JString) ; cdecl; overload;                  // (Ljava/lang/String;)V A: $1
    procedure setTagMask(tagMask : TJavaArray<Byte>) ; cdecl; overload;         // ([B)V A: $1
    procedure setTagMaskBitCount(tagMaskBitCount : Integer) ; cdecl;            // (I)V A: $1
    procedure setTagPattern(tagPattern : JString) ; cdecl; overload;            // (Ljava/lang/String;)V A: $1
    procedure setTagPattern(tagPattern : TJavaArray<Byte>) ; cdecl; overload;   // ([B)V A: $1
    procedure setTagPatternBitCount(tagPatternBitCount : Integer) ; cdecl;      // (I)V A: $1
  end;

  TJTagPatternBase = class(TJavaGenericImport<JTagPatternBaseClass, JTagPatternBase>)
  end;

implementation

end.
