//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.BTEventsReceiver;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.content.Intent;

type
  JBTEventsReceiver = interface;

  JBTEventsReceiverClass = interface(JObjectClass)
    ['{59AA4629-9C96-49D9-8CAA-D21D892D008E}']
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/BTEventsReceiver$BluetoothDeviceEventHandler')]
  JBTEventsReceiver = interface(JObject)
    ['{C54E44DE-448C-425D-96B7-19A3235888B7}']
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  TJBTEventsReceiver = class(TJavaGenericImport<JBTEventsReceiverClass, JBTEventsReceiver>)
  end;

implementation

end.
