//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.cv;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jcv = interface;

  JcvClass = interface(JObjectClass)
    ['{398EC909-6A55-40CC-A33F-1D5D7855F50A}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : JString) ; cdecl;                                   //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : JString read _Getb write _Setb;                                // Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/cv')]
  Jcv = interface(JObject)
    ['{B5A78C5B-936A-4EF0-BCDD-C0DD44A23CA0}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : JString) ; cdecl;                                   //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : JString read _Getb write _Setb;                                // Ljava/lang/String; A: $1
  end;

  TJcv = class(TJavaGenericImport<JcvClass, Jcv>)
  end;

implementation

end.
