//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RegionInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JRegionInfo = interface;

  JRegionInfoClass = interface(JObjectClass)
    ['{EA0D8243-7CA8-48FE-9282-BF89AB234F82}']
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getRegionCode : JString; cdecl;                                    // ()Ljava/lang/String; A: $1
    function getSupportedChannels : TJavaArray<JString>; cdecl;                 // ()[Ljava/lang/String; A: $1
    function init : JRegionInfo; cdecl;                                         // ()V A: $1
    function isHoppingConfigurable : boolean; cdecl;                            // ()Z A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/RegionInfo')]
  JRegionInfo = interface(JObject)
    ['{A59598A9-9337-49B1-BB55-A1268D1B4977}']
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getRegionCode : JString; cdecl;                                    // ()Ljava/lang/String; A: $1
    function getSupportedChannels : TJavaArray<JString>; cdecl;                 // ()[Ljava/lang/String; A: $1
    function isHoppingConfigurable : boolean; cdecl;                            // ()Z A: $1
  end;

  TJRegionInfo = class(TJavaGenericImport<JRegionInfoClass, JRegionInfo>)
  end;

implementation

end.
