//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.DYNAMIC_POWER_OPTIMIZATION;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JDYNAMIC_POWER_OPTIMIZATION = interface;

  JDYNAMIC_POWER_OPTIMIZATIONClass = interface(JObjectClass)
    ['{C1AF3F25-51AD-4BE1-B642-51E4B9D1A668}']
    function GetDPOState(value : Integer) : JObject; cdecl;                     // (I)Ljava/lang/Object; A: $9
    function _GetDISABLE : JDYNAMIC_POWER_OPTIMIZATION; cdecl;                  //  A: $19
    function _GetENABLE : JDYNAMIC_POWER_OPTIMIZATION; cdecl;                   //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property DISABLE : JDYNAMIC_POWER_OPTIMIZATION read _GetDISABLE;            // Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION; A: $19
    property ENABLE : JDYNAMIC_POWER_OPTIMIZATION read _GetENABLE;              // Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION')]
  JDYNAMIC_POWER_OPTIMIZATION = interface(JObject)
    ['{A29FA9D6-29BD-4347-949E-C0D384EA28A8}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJDYNAMIC_POWER_OPTIMIZATION = class(TJavaGenericImport<JDYNAMIC_POWER_OPTIMIZATIONClass, JDYNAMIC_POWER_OPTIMIZATION>)
  end;

implementation

end.
