//
// Generated by JavaToPas v1.5 20170214 - 172217
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Param_ReportConfig;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JParam_ReportConfig = interface;

  JParam_ReportConfigClass = interface(JObjectClass)
    ['{99734610-F159-4017-BD94-B6425B09D4AB}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getExcChannelIndex : boolean; cdecl;                               // ()Z A: $1
    function getExcFirstSeenTime : boolean; cdecl;                              // ()Z A: $1
    function getExcLastseenTime : boolean; cdecl;                               // ()Z A: $1
    function getExcPC : boolean; cdecl;                                         // ()Z A: $1
    function getExcPhase : boolean; cdecl;                                      // ()Z A: $1
    function getExcRSSI : boolean; cdecl;                                       // ()Z A: $1
    function getExcTagSeenCount : boolean; cdecl;                               // ()Z A: $1
    function getIncChannelIndex : boolean; cdecl;                               // ()Z A: $1
    function getIncFirstSeenTime : boolean; cdecl;                              // ()Z A: $1
    function getIncLastSeenTime : boolean; cdecl;                               // ()Z A: $1
    function getIncPC : boolean; cdecl;                                         // ()Z A: $1
    function getIncPhase : boolean; cdecl;                                      // ()Z A: $1
    function getIncRSSI : boolean; cdecl;                                       // ()Z A: $1
    function getIncTagSeenCount : boolean; cdecl;                               // ()Z A: $1
    function init : JParam_ReportConfig; cdecl;                                 // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setExcChannelIndex(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setExcFirstSeenTime(value : boolean) ; cdecl;                     // (Z)V A: $1
    procedure setExcLastseenTime(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setExcPC(value : boolean) ; cdecl;                                // (Z)V A: $1
    procedure setExcPhase(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setExcRSSI(value : boolean) ; cdecl;                              // (Z)V A: $1
    procedure setExcTagSeenCount(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncChannelIndex(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncFirstSeenTime(value : boolean) ; cdecl;                     // (Z)V A: $1
    procedure setIncLastSeenTime(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncPC(value : boolean) ; cdecl;                                // (Z)V A: $1
    procedure setIncPhase(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setIncRSSI(value : boolean) ; cdecl;                              // (Z)V A: $1
    procedure setIncTagSeenCount(value : boolean) ; cdecl;                      // (Z)V A: $1
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Param_ReportConfig')]
  JParam_ReportConfig = interface(JObject)
    ['{24A2AE94-A678-4609-B441-BD174C4E6B76}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getExcChannelIndex : boolean; cdecl;                               // ()Z A: $1
    function getExcFirstSeenTime : boolean; cdecl;                              // ()Z A: $1
    function getExcLastseenTime : boolean; cdecl;                               // ()Z A: $1
    function getExcPC : boolean; cdecl;                                         // ()Z A: $1
    function getExcPhase : boolean; cdecl;                                      // ()Z A: $1
    function getExcRSSI : boolean; cdecl;                                       // ()Z A: $1
    function getExcTagSeenCount : boolean; cdecl;                               // ()Z A: $1
    function getIncChannelIndex : boolean; cdecl;                               // ()Z A: $1
    function getIncFirstSeenTime : boolean; cdecl;                              // ()Z A: $1
    function getIncLastSeenTime : boolean; cdecl;                               // ()Z A: $1
    function getIncPC : boolean; cdecl;                                         // ()Z A: $1
    function getIncPhase : boolean; cdecl;                                      // ()Z A: $1
    function getIncRSSI : boolean; cdecl;                                       // ()Z A: $1
    function getIncTagSeenCount : boolean; cdecl;                               // ()Z A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setExcChannelIndex(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setExcFirstSeenTime(value : boolean) ; cdecl;                     // (Z)V A: $1
    procedure setExcLastseenTime(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setExcPC(value : boolean) ; cdecl;                                // (Z)V A: $1
    procedure setExcPhase(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setExcRSSI(value : boolean) ; cdecl;                              // (Z)V A: $1
    procedure setExcTagSeenCount(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncChannelIndex(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncFirstSeenTime(value : boolean) ; cdecl;                     // (Z)V A: $1
    procedure setIncLastSeenTime(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setIncPC(value : boolean) ; cdecl;                                // (Z)V A: $1
    procedure setIncPhase(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setIncRSSI(value : boolean) ; cdecl;                              // (Z)V A: $1
    procedure setIncTagSeenCount(value : boolean) ; cdecl;                      // (Z)V A: $1
  end;

  TJParam_ReportConfig = class(TJavaGenericImport<JParam_ReportConfigClass, JParam_ReportConfig>)
  end;

implementation

end.
