//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.al;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jal = interface;

  JalClass = interface(JObjectClass)
    ['{EC3E286C-31CC-427E-B662-EFEB2CEFF829}']
    function _Geta : Int64; cdecl;                                              //  A: $1
    procedure _Seta(Value : Int64) ; cdecl;                                     //  A: $1
    property a : Int64 read _Geta write _Seta;                                  // J A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/al')]
  Jal = interface(JObject)
    ['{4819AEBB-EFA4-4A28-A68D-A38BDE15C058}']
    function _Geta : Int64; cdecl;                                              //  A: $1
    procedure _Seta(Value : Int64) ; cdecl;                                     //  A: $1
    property a : Int64 read _Geta write _Seta;                                  // J A: $1
  end;

  TJal = class(TJavaGenericImport<JalClass, Jal>)
  end;

implementation

end.
