//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.GPOs;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.GPO_PORT_STATE,
  com.zebra.rfid.api3.GPOs_Port;

type
  JGPOs = interface;

  JGPOsClass = interface(JObjectClass)
    ['{E821A7FC-0480-4C2E-A94A-43473E0BB692}']
    function getLength : Integer; cdecl;                                        // ()I A: $1
    function getPortState(portIndex : Integer) : JGPO_PORT_STATE; cdecl;        // (I)Lcom/zebra/rfid/api3/GPO_PORT_STATE; A: $1
    procedure setPortState(portIndex : Integer; portState : JGPO_PORT_STATE) ; cdecl;// (ILcom/zebra/rfid/api3/GPO_PORT_STATE;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/GPOs$Port')]
  JGPOs = interface(JObject)
    ['{61E37E02-F21F-4C34-9351-4EFDA50AD402}']
    function getLength : Integer; cdecl;                                        // ()I A: $1
    function getPortState(portIndex : Integer) : JGPO_PORT_STATE; cdecl;        // (I)Lcom/zebra/rfid/api3/GPO_PORT_STATE; A: $1
    procedure setPortState(portIndex : Integer; portState : JGPO_PORT_STATE) ; cdecl;// (ILcom/zebra/rfid/api3/GPO_PORT_STATE;)V A: $1
  end;

  TJGPOs = class(TJavaGenericImport<JGPOsClass, JGPOs>)
  end;

implementation

end.
