//
// Generated by JavaToPas v1.5 20170214 - 172217
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.o;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.ResponseMsg,
  com.zebra.ASCII_SDK.MetaData;

type
  Jo = interface;

  JoClass = interface(JObjectClass)
    ['{652DD770-4662-4654-9179-35F0E5DC0FC7}']
    function a(JStringparam0 : JString; JMetaDataparam1 : JMetaData) : JResponseMsg; cdecl;// (Ljava/lang/String;Lcom/zebra/ASCII_SDK/MetaData;)Lcom/zebra/ASCII_SDK/ResponseMsg; A: $9
  end;

  [JavaSignature('com/zebra/ASCII_SDK/o$1')]
  Jo = interface(JObject)
    ['{7A0F7A85-879B-47DB-82F0-30481D054631}']
  end;

  TJo = class(TJavaGenericImport<JoClass, Jo>)
  end;

implementation

end.
