//
// Generated by JavaToPas v1.5 20170214 - 172216
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.j;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.RESPONSE_TYPE;

type
  Jj = interface;

  JjClass = interface(JObjectClass)
    ['{D09FACAF-4501-44CC-8C70-CE8916E1BE7D}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function a(JStringparam0 : JString) : Jj; cdecl;                            // (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/j; A: $9
    function getResponseType : JRESPONSE_TYPE; cdecl;                           // ()Lcom/zebra/ASCII_SDK/RESPONSE_TYPE; A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
  end;

  [JavaSignature('com/zebra/ASCII_SDK/j')]
  Jj = interface(JObject)
    ['{4ABA934C-3BDC-4691-BA8B-C87B1D183402}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function getResponseType : JRESPONSE_TYPE; cdecl;                           // ()Lcom/zebra/ASCII_SDK/RESPONSE_TYPE; A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
  end;

  TJj = class(TJavaGenericImport<JjClass, Jj>)
  end;

implementation

end.
