//
// Generated by JavaToPas v1.5 20170214 - 172215
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_SetQueryParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.ENUM_SL_FLAG,
  com.zebra.ASCII_SDK.ENUM_SESSION,
  com.zebra.ASCII_SDK.ENUM_STATE,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_SetQueryParams = interface;

  JCommand_SetQueryParamsClass = interface(JObjectClass)
    ['{29672D53-4BAC-48F7-A9F6-1A86A858EB0E}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getPopulation : Integer; cdecl;                                    // ()I A: $1
    function getQuerySelect : JENUM_SL_FLAG; cdecl;                             // ()Lcom/zebra/ASCII_SDK/ENUM_SL_FLAG; A: $1
    function getQuerySession : JENUM_SESSION; cdecl;                            // ()Lcom/zebra/ASCII_SDK/ENUM_SESSION; A: $1
    function getQueryTarget : JENUM_STATE; cdecl;                               // ()Lcom/zebra/ASCII_SDK/ENUM_STATE; A: $1
    function init : JCommand_SetQueryParams; cdecl;                             // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setPopulation(value : Integer) ; cdecl;                           // (I)V A: $1
    procedure setQuerySelect(value : JENUM_SL_FLAG) ; cdecl;                    // (Lcom/zebra/ASCII_SDK/ENUM_SL_FLAG;)V A: $1
    procedure setQuerySession(value : JENUM_SESSION) ; cdecl;                   // (Lcom/zebra/ASCII_SDK/ENUM_SESSION;)V A: $1
    procedure setQueryTarget(value : JENUM_STATE) ; cdecl;                      // (Lcom/zebra/ASCII_SDK/ENUM_STATE;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_SetQueryParams')]
  JCommand_SetQueryParams = interface(JObject)
    ['{4391EC57-4482-4872-84AF-DC3BDF402824}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getPopulation : Integer; cdecl;                                    // ()I A: $1
    function getQuerySelect : JENUM_SL_FLAG; cdecl;                             // ()Lcom/zebra/ASCII_SDK/ENUM_SL_FLAG; A: $1
    function getQuerySession : JENUM_SESSION; cdecl;                            // ()Lcom/zebra/ASCII_SDK/ENUM_SESSION; A: $1
    function getQueryTarget : JENUM_STATE; cdecl;                               // ()Lcom/zebra/ASCII_SDK/ENUM_STATE; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setPopulation(value : Integer) ; cdecl;                           // (I)V A: $1
    procedure setQuerySelect(value : JENUM_SL_FLAG) ; cdecl;                    // (Lcom/zebra/ASCII_SDK/ENUM_SL_FLAG;)V A: $1
    procedure setQuerySession(value : JENUM_SESSION) ; cdecl;                   // (Lcom/zebra/ASCII_SDK/ENUM_SESSION;)V A: $1
    procedure setQueryTarget(value : JENUM_STATE) ; cdecl;                      // (Lcom/zebra/ASCII_SDK/ENUM_STATE;)V A: $1
  end;

  TJCommand_SetQueryParams = class(TJavaGenericImport<JCommand_SetQueryParamsClass, JCommand_SetQueryParams>)
  end;

const
  TJCommand_SetQueryParamscommandName = 'SetQueryParams';

implementation

end.
