//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.GEN2V2_OPERATION_CODE;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JGEN2V2_OPERATION_CODE = interface;

  JGEN2V2_OPERATION_CODEClass = interface(JObjectClass)
    ['{48038DF4-5279-499D-82EB-32B734AC9CCF}']
    function GetG2V2OperationCodeValue(g2v2operation : JString) : JGEN2V2_OPERATION_CODE; cdecl; overload;// (Ljava/lang/String;)Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $9
    function GetG2V2OperationCodeValue(value : Integer) : JGEN2V2_OPERATION_CODE; cdecl; overload;// (I)Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $9
    function _GetG2V2_OPERATION_AUTHENTICATE : JGEN2V2_OPERATION_CODE; cdecl;   //  A: $19
    function _GetG2V2_OPERATION_CRYPTO : JGEN2V2_OPERATION_CODE; cdecl;         //  A: $19
    function _GetG2V2_OPERATION_READBUFFER : JGEN2V2_OPERATION_CODE; cdecl;     //  A: $19
    function _GetG2V2_OPERATION_UNTRACEABLE : JGEN2V2_OPERATION_CODE; cdecl;    //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property G2V2_OPERATION_AUTHENTICATE : JGEN2V2_OPERATION_CODE read _GetG2V2_OPERATION_AUTHENTICATE;// Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $19
    property G2V2_OPERATION_CRYPTO : JGEN2V2_OPERATION_CODE read _GetG2V2_OPERATION_CRYPTO;// Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $19
    property G2V2_OPERATION_READBUFFER : JGEN2V2_OPERATION_CODE read _GetG2V2_OPERATION_READBUFFER;// Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $19
    property G2V2_OPERATION_UNTRACEABLE : JGEN2V2_OPERATION_CODE read _GetG2V2_OPERATION_UNTRACEABLE;// Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/GEN2V2_OPERATION_CODE')]
  JGEN2V2_OPERATION_CODE = interface(JObject)
    ['{8DF168F0-AA57-483A-BE05-80D0A6AEC0C2}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJGEN2V2_OPERATION_CODE = class(TJavaGenericImport<JGEN2V2_OPERATION_CODEClass, JGEN2V2_OPERATION_CODE>)
  end;

implementation

end.
