//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RFModeTable;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.RFModeTableEntry;

type
  JRFModeTable = interface;

  JRFModeTableClass = interface(JObjectClass)
    ['{5C797047-0C78-443F-B823-134B744620BB}']
    function getProtocolID : Integer; cdecl;                                    // ()I A: $1
    function getRFModeTableEntryInfo(&index : Integer) : JRFModeTableEntry; cdecl;// (I)Lcom/zebra/rfid/api3/RFModeTableEntry; A: $1
    function length : Integer; cdecl;                                           // ()I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/RFModeTable')]
  JRFModeTable = interface(JObject)
    ['{1CE63C72-DE9B-4BE8-A727-222B1CA8D475}']
    function getProtocolID : Integer; cdecl;                                    // ()I A: $1
    function getRFModeTableEntryInfo(&index : Integer) : JRFModeTableEntry; cdecl;// (I)Lcom/zebra/rfid/api3/RFModeTableEntry; A: $1
    function length : Integer; cdecl;                                           // ()I A: $1
  end;

  TJRFModeTable = class(TJavaGenericImport<JRFModeTableClass, JRFModeTable>)
  end;

implementation

end.
