//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.BluetoothService_BluetoothDataHandler;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JBluetoothService_BluetoothDataHandler = interface;

  JBluetoothService_BluetoothDataHandlerClass = interface(JObjectClass)
    ['{0ED338D5-3D3D-414B-B865-B977EC54EC00}']
    procedure dataReceivedFromBluetooth(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
  end;

  [JavaSignature('com/zebra/rfid/api3/BluetoothService_BluetoothDataHandler')]
  JBluetoothService_BluetoothDataHandler = interface(JObject)
    ['{BB0ACA80-E1C2-44ED-AA9A-1CDF07C7BCFB}']
    procedure dataReceivedFromBluetooth(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
  end;

  TJBluetoothService_BluetoothDataHandler = class(TJavaGenericImport<JBluetoothService_BluetoothDataHandlerClass, JBluetoothService_BluetoothDataHandler>)
  end;

implementation

end.
