//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.VersionInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JVersionInfo = interface;

  JVersionInfoClass = interface(JObjectClass)
    ['{507E4777-EE6D-4420-B593-31116BCA0DEF}']
    function getVersion : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/VersionInfo')]
  JVersionInfo = interface(JObject)
    ['{317A9105-1624-4070-BCD1-8B392FC6874B}']
    function getVersion : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
  end;

  TJVersionInfo = class(TJavaGenericImport<JVersionInfoClass, JVersionInfo>)
  end;

implementation

end.
