//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.GPIs_Port;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.GPI_PORT_STATE;

type
  JGPIs_Port = interface;

  JGPIs_PortClass = interface(JObjectClass)
    ['{E80F5A3E-6B0F-4E07-959B-D041F522DBE2}']
  end;

  [JavaSignature('com/zebra/rfid/api3/GPIs_Port')]
  JGPIs_Port = interface(JObject)
    ['{4075C0AC-1B85-49D7-8E3A-0B15C6D60F13}']
  end;

  TJGPIs_Port = class(TJavaGenericImport<JGPIs_PortClass, JGPIs_Port>)
  end;

implementation

end.
