//
// Generated by JavaToPas v1.5 20170214 - 172214
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_ChangeConfig;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.ENUM_CHANGE_CONFIG_MODE,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_ChangeConfig = interface;

  JCommand_ChangeConfigClass = interface(JObjectClass)
    ['{78015623-818C-4BCE-A00B-86FB9A89E84B}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getMode : JENUM_CHANGE_CONFIG_MODE; cdecl;                         // ()Lcom/zebra/ASCII_SDK/ENUM_CHANGE_CONFIG_MODE; A: $1
    function init : JCommand_ChangeConfig; cdecl;                               // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setMode(value : JENUM_CHANGE_CONFIG_MODE) ; cdecl;                // (Lcom/zebra/ASCII_SDK/ENUM_CHANGE_CONFIG_MODE;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_ChangeConfig')]
  JCommand_ChangeConfig = interface(JObject)
    ['{777ADD12-9BD4-4E94-B712-663FE5AB5765}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getMode : JENUM_CHANGE_CONFIG_MODE; cdecl;                         // ()Lcom/zebra/ASCII_SDK/ENUM_CHANGE_CONFIG_MODE; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setMode(value : JENUM_CHANGE_CONFIG_MODE) ; cdecl;                // (Lcom/zebra/ASCII_SDK/ENUM_CHANGE_CONFIG_MODE;)V A: $1
  end;

  TJCommand_ChangeConfig = class(TJavaGenericImport<JCommand_ChangeConfigClass, JCommand_ChangeConfig>)
  end;

const
  TJCommand_ChangeConfigcommandName = 'ChangeConfig';

implementation

end.
