//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ReaderDevice;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.RFIDReader;

type
  JReaderDevice = interface;

  JReaderDeviceClass = interface(JObjectClass)
    ['{6B9DF4A8-9356-4C4B-BE37-FF6E795A6FA8}']
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function getAddress : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getPassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getRFIDReader : JRFIDReader; cdecl;                                // ()Lcom/zebra/rfid/api3/RFIDReader; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function init : JReaderDevice; cdecl; overload;                             // ()V A: $1
    function init(&name : JString; address : JString) : JReaderDevice; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function init(&name : JString; address : JString; rfidReader : JRFIDReader) : JReaderDevice; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Lcom/zebra/rfid/api3/RFIDReader;)V A: $1
    procedure setAddress(address : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
    procedure setName(&name : JString) ; cdecl;                                 // (Ljava/lang/String;)V A: $1
    procedure setPassword(password : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setRFIDRReader(rfidReader : JRFIDReader) ; cdecl;                 // (Lcom/zebra/rfid/api3/RFIDReader;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ReaderDevice')]
  JReaderDevice = interface(JObject)
    ['{8B077591-5C3F-4D01-8E90-C4FF58B3B398}']
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function getAddress : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getPassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getRFIDReader : JRFIDReader; cdecl;                                // ()Lcom/zebra/rfid/api3/RFIDReader; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    procedure setAddress(address : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
    procedure setName(&name : JString) ; cdecl;                                 // (Ljava/lang/String;)V A: $1
    procedure setPassword(password : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setRFIDRReader(rfidReader : JRFIDReader) ; cdecl;                 // (Lcom/zebra/rfid/api3/RFIDReader;)V A: $1
  end;

  TJReaderDevice = class(TJavaGenericImport<JReaderDeviceClass, JReaderDevice>)
  end;

implementation

end.
