//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.LOCK_DATA_FIELD;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JLOCK_DATA_FIELD = interface;

  JLOCK_DATA_FIELDClass = interface(JObjectClass)
    ['{5886B7C4-DCF5-4B1F-9EE9-824E0DD05939}']
    function _GetLOCK_ACCESS_PASSWORD : JLOCK_DATA_FIELD; cdecl;                //  A: $19
    function _GetLOCK_EPC_MEMORY : JLOCK_DATA_FIELD; cdecl;                     //  A: $19
    function _GetLOCK_KILL_PASSWORD : JLOCK_DATA_FIELD; cdecl;                  //  A: $19
    function _GetLOCK_TID_MEMORY : JLOCK_DATA_FIELD; cdecl;                     //  A: $19
    function _GetLOCK_USER_MEMORY : JLOCK_DATA_FIELD; cdecl;                    //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property LOCK_ACCESS_PASSWORD : JLOCK_DATA_FIELD read _GetLOCK_ACCESS_PASSWORD;// Lcom/zebra/rfid/api3/LOCK_DATA_FIELD; A: $19
    property LOCK_EPC_MEMORY : JLOCK_DATA_FIELD read _GetLOCK_EPC_MEMORY;       // Lcom/zebra/rfid/api3/LOCK_DATA_FIELD; A: $19
    property LOCK_KILL_PASSWORD : JLOCK_DATA_FIELD read _GetLOCK_KILL_PASSWORD; // Lcom/zebra/rfid/api3/LOCK_DATA_FIELD; A: $19
    property LOCK_TID_MEMORY : JLOCK_DATA_FIELD read _GetLOCK_TID_MEMORY;       // Lcom/zebra/rfid/api3/LOCK_DATA_FIELD; A: $19
    property LOCK_USER_MEMORY : JLOCK_DATA_FIELD read _GetLOCK_USER_MEMORY;     // Lcom/zebra/rfid/api3/LOCK_DATA_FIELD; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/LOCK_DATA_FIELD')]
  JLOCK_DATA_FIELD = interface(JObject)
    ['{FAFC2BC0-8FD6-49F9-83A4-D577E881022E}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJLOCK_DATA_FIELD = class(TJavaGenericImport<JLOCK_DATA_FIELDClass, JLOCK_DATA_FIELD>)
  end;

implementation

end.
