//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bs;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jbs = interface;

  JbsClass = interface(JObjectClass)
    ['{C3E3C8F1-65BA-47C3-964B-492148D45822}']
    function _Geta : Jbs; cdecl;                                                //  A: $19
    function _Getb : Jbs; cdecl;                                                //  A: $19
    function _Getc : Jbs; cdecl;                                                //  A: $19
    function _Getd : Integer; cdecl;                                            //  A: $11
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property a : Jbs read _Geta;                                                // Lcom/zebra/rfid/api3/bs; A: $19
    property b : Jbs read _Getb;                                                // Lcom/zebra/rfid/api3/bs; A: $19
    property c : Jbs read _Getc;                                                // Lcom/zebra/rfid/api3/bs; A: $19
    property d : Integer read _Getd;                                            // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/bs')]
  Jbs = interface(JObject)
    ['{355EB5A9-4F53-4F1F-8286-F09561F264EB}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJbs = class(TJavaGenericImport<JbsClass, Jbs>)
  end;

implementation

end.
