//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.LoginInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.SECURE_MODE;

type
  JLoginInfo = interface;

  JLoginInfoClass = interface(JObjectClass)
    ['{06D45641-81D6-40BD-8BBA-7CA9DB287348}']
    function getForceLogin : boolean; cdecl;                                    // ()Z A: $1
    function getHostName : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getPassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getSecureMode : JSECURE_MODE; cdecl;                               // ()Lcom/zebra/rfid/api3/SECURE_MODE; A: $1
    function getUserName : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function init : JLoginInfo; cdecl; overload;                                // ()V A: $1
    function init(hostName : JString; userName : JString; password : JString; secureMode : JSECURE_MODE) : JLoginInfo; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/zebra/rfid/api3/SECURE_MODE;)V A: $1
    function init(hostName : JString; userName : JString; password : JString; secureMode : JSECURE_MODE; forceLogin : boolean) : JLoginInfo; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/zebra/rfid/api3/SECURE_MODE;Z)V A: $1
    procedure setForceLogin(forceLogin : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setHostName(hostName : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setPassword(password : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setSecureMode(m_eSecureMode : JSECURE_MODE) ; cdecl;              // (Lcom/zebra/rfid/api3/SECURE_MODE;)V A: $1
    procedure setUserName(userName : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/LoginInfo')]
  JLoginInfo = interface(JObject)
    ['{AA0FE438-77DB-47DE-B439-D2D0A663B058}']
    function getForceLogin : boolean; cdecl;                                    // ()Z A: $1
    function getHostName : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getPassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getSecureMode : JSECURE_MODE; cdecl;                               // ()Lcom/zebra/rfid/api3/SECURE_MODE; A: $1
    function getUserName : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    procedure setForceLogin(forceLogin : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setHostName(hostName : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setPassword(password : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
    procedure setSecureMode(m_eSecureMode : JSECURE_MODE) ; cdecl;              // (Lcom/zebra/rfid/api3/SECURE_MODE;)V A: $1
    procedure setUserName(userName : JString) ; cdecl;                          // (Ljava/lang/String;)V A: $1
  end;

  TJLoginInfo = class(TJavaGenericImport<JLoginInfoClass, JLoginInfo>)
  end;

implementation

end.
