//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.UTCTime;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.SYSTEMTIME;

type
  JUTCTime = interface;

  JUTCTimeClass = interface(JObjectClass)
    ['{A45327AC-F26D-40CD-BEC5-3FBBD15EEF02}']
    function getFirstSeenTimeStamp : JSYSTEMTIME; cdecl;                        // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    function getLastSeenTimeStamp : JSYSTEMTIME; cdecl;                         // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    procedure setFirstSeenTimeStamp(m_FirstSeenTimeStamp : JSYSTEMTIME) ; cdecl; overload;// (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setFirstSeenTimeStamp(year : SmallInt; month : SmallInt; day : SmallInt; dayOfWeek : SmallInt; hour : SmallInt; minute : SmallInt; second : SmallInt; milliseconds : SmallInt) ; cdecl; overload;// (SSSSSSSS)V A: $1
    procedure setLastSeenTimeStamp(m_LastSeenTimeStamp : JSYSTEMTIME) ; cdecl; overload;// (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setLastSeenTimeStamp(year : SmallInt; month : SmallInt; day : SmallInt; dayOfWeek : SmallInt; hour : SmallInt; minute : SmallInt; second : SmallInt; milliseconds : SmallInt) ; cdecl; overload;// (SSSSSSSS)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/UTCTime')]
  JUTCTime = interface(JObject)
    ['{A87C6214-9BBA-4404-B8F1-9986DBCCCAB4}']
    function getFirstSeenTimeStamp : JSYSTEMTIME; cdecl;                        // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    function getLastSeenTimeStamp : JSYSTEMTIME; cdecl;                         // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    procedure setFirstSeenTimeStamp(m_FirstSeenTimeStamp : JSYSTEMTIME) ; cdecl; overload;// (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setFirstSeenTimeStamp(year : SmallInt; month : SmallInt; day : SmallInt; dayOfWeek : SmallInt; hour : SmallInt; minute : SmallInt; second : SmallInt; milliseconds : SmallInt) ; cdecl; overload;// (SSSSSSSS)V A: $1
    procedure setLastSeenTimeStamp(m_LastSeenTimeStamp : JSYSTEMTIME) ; cdecl; overload;// (Lcom/zebra/rfid/api3/SYSTEMTIME;)V A: $1
    procedure setLastSeenTimeStamp(year : SmallInt; month : SmallInt; day : SmallInt; dayOfWeek : SmallInt; hour : SmallInt; minute : SmallInt; second : SmallInt; milliseconds : SmallInt) ; cdecl; overload;// (SSSSSSSS)V A: $1
  end;

  TJUTCTime = class(TJavaGenericImport<JUTCTimeClass, JUTCTime>)
  end;

implementation

end.
