//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.UpTime;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JUpTime = interface;

  JUpTimeClass = interface(JObjectClass)
    ['{BD174D96-17D3-47EE-AAF7-F14BD81219C7}']
    function getFirstSeenTimeStamp : Int64; cdecl;                              // ()J A: $1
    function getLastSeenTimeStamp : Int64; cdecl;                               // ()J A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/UpTime')]
  JUpTime = interface(JObject)
    ['{4CBC1526-52BC-4A21-85E7-4C0EBCCFA1AE}']
    function getFirstSeenTimeStamp : Int64; cdecl;                              // ()J A: $1
    function getLastSeenTimeStamp : Int64; cdecl;                               // ()J A: $1
  end;

  TJUpTime = class(TJavaGenericImport<JUpTimeClass, JUpTime>)
  end;

implementation

end.
