//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Events_AccessStopEventData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Events;

type
  JEvents_AccessStopEventData = interface;

  JEvents_AccessStopEventDataClass = interface(JObjectClass)
    ['{C8D0F1EE-6C09-42B1-AC32-6EF7902B081C}']
  end;

  [JavaSignature('com/zebra/rfid/api3/Events_AccessStopEventData')]
  JEvents_AccessStopEventData = interface(JObject)
    ['{8914F6DC-BAD2-4118-9B20-25DB6E8FD977}']
  end;

  TJEvents_AccessStopEventData = class(TJavaGenericImport<JEvents_AccessStopEventDataClass, JEvents_AccessStopEventData>)
  end;

implementation

end.
