//
// Generated by JavaToPas v1.5 20170214 - 172218
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.e;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.OPERATION_QUALIFIER;

type
  Je = interface;

  JeClass = interface(JObjectClass)
    ['{2332FDB4-5B5B-4136-8CFC-66C5EAAF06C1}']
    function _Geta : TJavaArray<SmallInt>; cdecl;                               //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : TJavaArray<JOPERATION_QUALIFIER>; cdecl;                   //  A: $1
    procedure _Seta(Value : TJavaArray<SmallInt>) ; cdecl;                      //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : TJavaArray<JOPERATION_QUALIFIER>) ; cdecl;          //  A: $1
    property a : TJavaArray<SmallInt> read _Geta write _Seta;                   // [S A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : TJavaArray<JOPERATION_QUALIFIER> read _Getc write _Setc;       // [Lcom/zebra/rfid/api3/OPERATION_QUALIFIER; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/e')]
  Je = interface(JObject)
    ['{C3E0E5F2-F3A7-483D-9C7D-31E81E8B17CA}']
    function _Geta : TJavaArray<SmallInt>; cdecl;                               //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : TJavaArray<JOPERATION_QUALIFIER>; cdecl;                   //  A: $1
    procedure _Seta(Value : TJavaArray<SmallInt>) ; cdecl;                      //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : TJavaArray<JOPERATION_QUALIFIER>) ; cdecl;          //  A: $1
    property a : TJavaArray<SmallInt> read _Geta write _Seta;                   // [S A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : TJavaArray<JOPERATION_QUALIFIER> read _Getc write _Setc;       // [Lcom/zebra/rfid/api3/OPERATION_QUALIFIER; A: $1
  end;

  TJe = class(TJavaGenericImport<JeClass, Je>)
  end;

implementation

end.
