//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagAccess_RecommisionAccessParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.RECOMMISSION_OPERATION_CODE,
  com.zebra.rfid.api3.Impinj;

type
  JTagAccess_RecommisionAccessParams = interface;

  JTagAccess_RecommisionAccessParamsClass = interface(JObjectClass)
    ['{B9409642-3B19-4A33-9CAE-021608B48C24}']
    function getKillPassword : Int64; cdecl;                                    // ()J A: $1
    function getOpCode : JRECOMMISSION_OPERATION_CODE; cdecl;                   // ()Lcom/zebra/rfid/api3/RECOMMISSION_OPERATION_CODE; A: $1
    function init(JTagAccessparam0 : JTagAccess) : JTagAccess_RecommisionAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    function init(m_nKillPassword : Int64; m_eOpCode : JRECOMMISSION_OPERATION_CODE) : JTagAccess_RecommisionAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;JLcom/zebra/rfid/api3/RECOMMISSION_OPERATION_CODE;)V A: $1
    procedure setKillPassword(killPassword : Int64) ; cdecl;                    // (J)V A: $1
    procedure setOpCode(opCode : JRECOMMISSION_OPERATION_CODE) ; cdecl;         // (Lcom/zebra/rfid/api3/RECOMMISSION_OPERATION_CODE;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess_RecommisionAccessParams')]
  JTagAccess_RecommisionAccessParams = interface(JObject)
    ['{08E7F0EA-4A37-4F72-8D4B-987313F98468}']
    function getKillPassword : Int64; cdecl;                                    // ()J A: $1
    function getOpCode : JRECOMMISSION_OPERATION_CODE; cdecl;                   // ()Lcom/zebra/rfid/api3/RECOMMISSION_OPERATION_CODE; A: $1
    procedure setKillPassword(killPassword : Int64) ; cdecl;                    // (J)V A: $1
    procedure setOpCode(opCode : JRECOMMISSION_OPERATION_CODE) ; cdecl;         // (Lcom/zebra/rfid/api3/RECOMMISSION_OPERATION_CODE;)V A: $1
  end;

  TJTagAccess_RecommisionAccessParams = class(TJavaGenericImport<JTagAccess_RecommisionAccessParamsClass, JTagAccess_RecommisionAccessParams>)
  end;

implementation

end.
