//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RssiRangeFilter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.MATCH_RANGE;

type
  JRssiRangeFilter = interface;

  JRssiRangeFilterClass = interface(JObjectClass)
    ['{59E0F5C4-9633-4B6B-A998-CFC6B6FA69D1}']
    function getMatchRange : JMATCH_RANGE; cdecl;                               // ()Lcom/zebra/rfid/api3/MATCH_RANGE; A: $1
    function getPeakRSSILowerLimit : SmallInt; cdecl;                           // ()S A: $1
    function getPeakRSSIUpperLimit : SmallInt; cdecl;                           // ()S A: $1
    function init : JRssiRangeFilter; cdecl;                                    // ()V A: $1
    procedure setMatchRange(matchRange : JMATCH_RANGE) ; cdecl;                 // (Lcom/zebra/rfid/api3/MATCH_RANGE;)V A: $1
    procedure setPeakRSSILowerLimit(peakRSSILowerLimit : SmallInt) ; cdecl;     // (S)V A: $1
    procedure setPeakRSSIUpperLimit(m_peakRSSIUpperLimit : SmallInt) ; cdecl;   // (S)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/RssiRangeFilter')]
  JRssiRangeFilter = interface(JObject)
    ['{53F219B7-C41C-4B49-BBA8-6AC2B19A73A7}']
    function getMatchRange : JMATCH_RANGE; cdecl;                               // ()Lcom/zebra/rfid/api3/MATCH_RANGE; A: $1
    function getPeakRSSILowerLimit : SmallInt; cdecl;                           // ()S A: $1
    function getPeakRSSIUpperLimit : SmallInt; cdecl;                           // ()S A: $1
    procedure setMatchRange(matchRange : JMATCH_RANGE) ; cdecl;                 // (Lcom/zebra/rfid/api3/MATCH_RANGE;)V A: $1
    procedure setPeakRSSILowerLimit(peakRSSILowerLimit : SmallInt) ; cdecl;     // (S)V A: $1
    procedure setPeakRSSIUpperLimit(m_peakRSSIUpperLimit : SmallInt) ; cdecl;   // (S)V A: $1
  end;

  TJRssiRangeFilter = class(TJavaGenericImport<JRssiRangeFilterClass, JRssiRangeFilter>)
  end;

implementation

end.
