//
// Generated by JavaToPas v1.5 20170214 - 172216
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.ENUM_SPECTRAL_MASK_INDICATOR;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JENUM_SPECTRAL_MASK_INDICATOR = interface;

  JENUM_SPECTRAL_MASK_INDICATORClass = interface(JObjectClass)
    ['{3AFF300B-2E03-4259-81B4-8795223780CA}']
    function _GetSMI_DI : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;                 //  A: $4019
    function _GetSMI_MI : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;                 //  A: $4019
    function _GetSMI_SI : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;                 //  A: $4019
    function _GetSMI_UNKNOWN : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;            //  A: $4019
    function getEnum(enumValS : JString) : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;// (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $9
    function getEnumValue : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function valueOf(&name : JString) : JENUM_SPECTRAL_MASK_INDICATOR; cdecl;   // (Ljava/lang/String;)Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $9
    function values : TJavaArray<JENUM_SPECTRAL_MASK_INDICATOR>; cdecl;         // ()[Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $9
    property SMI_DI : JENUM_SPECTRAL_MASK_INDICATOR read _GetSMI_DI;            // Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $4019
    property SMI_MI : JENUM_SPECTRAL_MASK_INDICATOR read _GetSMI_MI;            // Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $4019
    property SMI_SI : JENUM_SPECTRAL_MASK_INDICATOR read _GetSMI_SI;            // Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $4019
    property SMI_UNKNOWN : JENUM_SPECTRAL_MASK_INDICATOR read _GetSMI_UNKNOWN;  // Lcom/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR; A: $4019
  end;

  [JavaSignature('com/zebra/ASCII_SDK/ENUM_SPECTRAL_MASK_INDICATOR')]
  JENUM_SPECTRAL_MASK_INDICATOR = interface(JObject)
    ['{E6139142-1EA2-470A-91F3-3798073D470A}']
    function getEnumValue : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
  end;

  TJENUM_SPECTRAL_MASK_INDICATOR = class(TJavaGenericImport<JENUM_SPECTRAL_MASK_INDICATORClass, JENUM_SPECTRAL_MASK_INDICATOR>)
  end;

implementation

end.
