//
// Generated by JavaToPas v1.5 20170214 - 172219
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.AttributeInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JAttributeInfo = interface;

  JAttributeInfoClass = interface(JObjectClass)
    ['{368273C5-A9A3-4392-9ED8-DAC693CED398}']
    function _GetAttNum : Integer; cdecl;                                       //  A: $1
    function _GetLength : Integer; cdecl;                                       //  A: $1
    function _GetOffset : Integer; cdecl;                                       //  A: $1
    function _GetType : JString; cdecl;                                         //  A: $1
    function _GetValue : Integer; cdecl;                                        //  A: $1
    function _GetpropertyVal : Integer; cdecl;                                  //  A: $1
    function getAttNum : Integer; cdecl;                                        // ()I A: $1
    function getLength : Integer; cdecl;                                        // ()I A: $1
    function getOffset : Integer; cdecl;                                        // ()I A: $1
    function getPropertyVal : Integer; cdecl;                                   // ()I A: $1
    function getType : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function init : JAttributeInfo; cdecl;                                      // ()V A: $1
    procedure _SetAttNum(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetLength(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetOffset(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetType(Value : JString) ; cdecl;                                //  A: $1
    procedure _SetValue(Value : Integer) ; cdecl;                               //  A: $1
    procedure _SetpropertyVal(Value : Integer) ; cdecl;                         //  A: $1
    procedure setAttNum(attNum : Integer) ; cdecl;                              // (I)V A: $1
    procedure setLength(length : Integer) ; cdecl;                              // (I)V A: $1
    procedure setOffset(offset : Integer) ; cdecl;                              // (I)V A: $1
    procedure setPropertyVal(propertyVal : Integer) ; cdecl;                    // (I)V A: $1
    procedure setType(&type : JString) ; cdecl;                                 // (Ljava/lang/String;)V A: $1
    procedure setValue(value : Integer) ; cdecl;                                // (I)V A: $1
    property &Type : JString read _GetType write _SetType;                      // Ljava/lang/String; A: $1
    property AttNum : Integer read _GetAttNum write _SetAttNum;                 // I A: $1
    property Length : Integer read _GetLength write _SetLength;                 // I A: $1
    property Offset : Integer read _GetOffset write _SetOffset;                 // I A: $1
    property Value : Integer read _GetValue write _SetValue;                    // I A: $1
    property propertyVal : Integer read _GetpropertyVal write _SetpropertyVal;  // I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/AttributeInfo')]
  JAttributeInfo = interface(JObject)
    ['{A7FE7D20-A19D-459A-A57B-0B86ABC1E7B3}']
    function _GetAttNum : Integer; cdecl;                                       //  A: $1
    function _GetLength : Integer; cdecl;                                       //  A: $1
    function _GetOffset : Integer; cdecl;                                       //  A: $1
    function _GetType : JString; cdecl;                                         //  A: $1
    function _GetValue : Integer; cdecl;                                        //  A: $1
    function _GetpropertyVal : Integer; cdecl;                                  //  A: $1
    function getAttNum : Integer; cdecl;                                        // ()I A: $1
    function getLength : Integer; cdecl;                                        // ()I A: $1
    function getOffset : Integer; cdecl;                                        // ()I A: $1
    function getPropertyVal : Integer; cdecl;                                   // ()I A: $1
    function getType : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    procedure _SetAttNum(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetLength(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetOffset(Value : Integer) ; cdecl;                              //  A: $1
    procedure _SetType(Value : JString) ; cdecl;                                //  A: $1
    procedure _SetValue(Value : Integer) ; cdecl;                               //  A: $1
    procedure _SetpropertyVal(Value : Integer) ; cdecl;                         //  A: $1
    procedure setAttNum(attNum : Integer) ; cdecl;                              // (I)V A: $1
    procedure setLength(length : Integer) ; cdecl;                              // (I)V A: $1
    procedure setOffset(offset : Integer) ; cdecl;                              // (I)V A: $1
    procedure setPropertyVal(propertyVal : Integer) ; cdecl;                    // (I)V A: $1
    procedure setType(&type : JString) ; cdecl;                                 // (Ljava/lang/String;)V A: $1
    procedure setValue(value : Integer) ; cdecl;                                // (I)V A: $1
    property &Type : JString read _GetType write _SetType;                      // Ljava/lang/String; A: $1
    property AttNum : Integer read _GetAttNum write _SetAttNum;                 // I A: $1
    property Length : Integer read _GetLength write _SetLength;                 // I A: $1
    property Offset : Integer read _GetOffset write _SetOffset;                 // I A: $1
    property Value : Integer read _GetValue write _SetValue;                    // I A: $1
    property propertyVal : Integer read _GetpropertyVal write _SetpropertyVal;  // I A: $1
  end;

  TJAttributeInfo = class(TJavaGenericImport<JAttributeInfoClass, JAttributeInfo>)
  end;

implementation

end.
