//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagData;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.LocationInfo,
  com.zebra.rfid.api3.SeenTime,
  com.zebra.rfid.api3.AccessOperationResult,
  com.zebra.rfid.api3.ACCESS_OPERATION_CODE,
  com.zebra.rfid.api3.GEN2V2_OPERATION_CODE,
  com.zebra.rfid.api3.ACCESS_OPERATION_STATUS,
  com.zebra.rfid.api3.GEN2V2_OPERATION_STATUS,
  com.zebra.rfid.api3.MEMORY_BANK,
  com.zebra.rfid.api3.TAG_EVENT,
  com.zebra.rfid.api3.SYSTEMTIME;

type
  JTagData = interface;

  JTagDataClass = interface(JObjectClass)
    ['{CAD286FA-82EE-48D3-A222-59EE60A78034}']
    function _GetAccessOperationResult : JAccessOperationResult; cdecl;         //  A: $1
    function _GetLocationInfo : JLocationInfo; cdecl;                           //  A: $1
    function _GetSeenTime : JSeenTime; cdecl;                                   //  A: $1
    function getAntennaID : SmallInt; cdecl;                                    // ()S A: $1
    function getCRC : Integer; cdecl;                                           // ()I A: $1
    function getChannelIndex : SmallInt; cdecl;                                 // ()S A: $1
    function getG2v2OpCode : JGEN2V2_OPERATION_CODE; cdecl;                     // ()Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $1
    function getG2v2OpStatus : JGEN2V2_OPERATION_STATUS; cdecl;                 // ()Lcom/zebra/rfid/api3/GEN2V2_OPERATION_STATUS; A: $1
    function getG2v2Response : JString; cdecl;                                  // ()Ljava/lang/String; A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getMemoryBankData : JString; cdecl;                                // ()Ljava/lang/String; A: $1
    function getMemoryBankDataAllocatedSize : Integer; cdecl;                   // ()I A: $1
    function getMemoryBankDataOffset : Integer; cdecl;                          // ()I A: $1
    function getNumberOfWords : Integer; cdecl;                                 // ()I A: $1
    function getOpCode : JACCESS_OPERATION_CODE; cdecl;                         // ()Lcom/zebra/rfid/api3/ACCESS_OPERATION_CODE; A: $1
    function getOpStatus : JACCESS_OPERATION_STATUS; cdecl;                     // ()Lcom/zebra/rfid/api3/ACCESS_OPERATION_STATUS; A: $1
    function getPC : Integer; cdecl;                                            // ()I A: $1
    function getPeakRSSI : SmallInt; cdecl;                                     // ()S A: $1
    function getPermaLockData : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
    function getPhase : SmallInt; cdecl;                                        // ()S A: $1
    function getTagEvent : JTAG_EVENT; cdecl;                                   // ()Lcom/zebra/rfid/api3/TAG_EVENT; A: $1
    function getTagEventTimeStamp : JSYSTEMTIME; cdecl;                         // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    function getTagID : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getTagIDAllocatedSize : Integer; cdecl;                            // ()I A: $1
    function getTagSeenCount : SmallInt; cdecl;                                 // ()S A: $1
    function getXPC_W1 : Integer; cdecl;                                        // ()I A: $1
    function getXPC_W2 : Integer; cdecl;                                        // ()I A: $1
    function init : JTagData; cdecl;                                            // ()V A: $1
    function isContainsLocationInfo : boolean; cdecl;                           // ()Z A: $1
    procedure _SetAccessOperationResult(Value : JAccessOperationResult) ; cdecl;//  A: $1
    procedure _SetLocationInfo(Value : JLocationInfo) ; cdecl;                  //  A: $1
    procedure _SetSeenTime(Value : JSeenTime) ; cdecl;                          //  A: $1
    property AccessOperationResult : JAccessOperationResult read _GetAccessOperationResult write _SetAccessOperationResult;// Lcom/zebra/rfid/api3/AccessOperationResult; A: $1
    property LocationInfo : JLocationInfo read _GetLocationInfo write _SetLocationInfo;// Lcom/zebra/rfid/api3/LocationInfo; A: $1
    property SeenTime : JSeenTime read _GetSeenTime write _SetSeenTime;         // Lcom/zebra/rfid/api3/SeenTime; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagData')]
  JTagData = interface(JObject)
    ['{048A0FFC-AC38-465A-914E-FF997EE4FAA2}']
    function _GetAccessOperationResult : JAccessOperationResult; cdecl;         //  A: $1
    function _GetLocationInfo : JLocationInfo; cdecl;                           //  A: $1
    function _GetSeenTime : JSeenTime; cdecl;                                   //  A: $1
    function getAntennaID : SmallInt; cdecl;                                    // ()S A: $1
    function getCRC : Integer; cdecl;                                           // ()I A: $1
    function getChannelIndex : SmallInt; cdecl;                                 // ()S A: $1
    function getG2v2OpCode : JGEN2V2_OPERATION_CODE; cdecl;                     // ()Lcom/zebra/rfid/api3/GEN2V2_OPERATION_CODE; A: $1
    function getG2v2OpStatus : JGEN2V2_OPERATION_STATUS; cdecl;                 // ()Lcom/zebra/rfid/api3/GEN2V2_OPERATION_STATUS; A: $1
    function getG2v2Response : JString; cdecl;                                  // ()Ljava/lang/String; A: $1
    function getMemoryBank : JMEMORY_BANK; cdecl;                               // ()Lcom/zebra/rfid/api3/MEMORY_BANK; A: $1
    function getMemoryBankData : JString; cdecl;                                // ()Ljava/lang/String; A: $1
    function getMemoryBankDataAllocatedSize : Integer; cdecl;                   // ()I A: $1
    function getMemoryBankDataOffset : Integer; cdecl;                          // ()I A: $1
    function getNumberOfWords : Integer; cdecl;                                 // ()I A: $1
    function getOpCode : JACCESS_OPERATION_CODE; cdecl;                         // ()Lcom/zebra/rfid/api3/ACCESS_OPERATION_CODE; A: $1
    function getOpStatus : JACCESS_OPERATION_STATUS; cdecl;                     // ()Lcom/zebra/rfid/api3/ACCESS_OPERATION_STATUS; A: $1
    function getPC : Integer; cdecl;                                            // ()I A: $1
    function getPeakRSSI : SmallInt; cdecl;                                     // ()S A: $1
    function getPermaLockData : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
    function getPhase : SmallInt; cdecl;                                        // ()S A: $1
    function getTagEvent : JTAG_EVENT; cdecl;                                   // ()Lcom/zebra/rfid/api3/TAG_EVENT; A: $1
    function getTagEventTimeStamp : JSYSTEMTIME; cdecl;                         // ()Lcom/zebra/rfid/api3/SYSTEMTIME; A: $1
    function getTagID : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getTagIDAllocatedSize : Integer; cdecl;                            // ()I A: $1
    function getTagSeenCount : SmallInt; cdecl;                                 // ()S A: $1
    function getXPC_W1 : Integer; cdecl;                                        // ()I A: $1
    function getXPC_W2 : Integer; cdecl;                                        // ()I A: $1
    function isContainsLocationInfo : boolean; cdecl;                           // ()Z A: $1
    procedure _SetAccessOperationResult(Value : JAccessOperationResult) ; cdecl;//  A: $1
    procedure _SetLocationInfo(Value : JLocationInfo) ; cdecl;                  //  A: $1
    procedure _SetSeenTime(Value : JSeenTime) ; cdecl;                          //  A: $1
    property AccessOperationResult : JAccessOperationResult read _GetAccessOperationResult write _SetAccessOperationResult;// Lcom/zebra/rfid/api3/AccessOperationResult; A: $1
    property LocationInfo : JLocationInfo read _GetLocationInfo write _SetLocationInfo;// Lcom/zebra/rfid/api3/LocationInfo; A: $1
    property SeenTime : JSeenTime read _GetSeenTime write _SetSeenTime;         // Lcom/zebra/rfid/api3/SeenTime; A: $1
  end;

  TJTagData = class(TJavaGenericImport<JTagDataClass, JTagData>)
  end;

implementation

end.
