//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.at;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jat = interface;

  JatClass = interface(JObjectClass)
    ['{311566A4-BDB8-48C2-B175-776A146BC89A}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/at')]
  Jat = interface(JObject)
    ['{0E64BF44-81B9-49C3-84AD-0AF4561F787D}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  TJat = class(TJavaGenericImport<JatClass, Jat>)
  end;

implementation

end.
