//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagEventReportInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.TAG_EVENT_REPORT_TRIGGER;

type
  JTagEventReportInfo = interface;

  JTagEventReportInfoClass = interface(JObjectClass)
    ['{A6342B60-817E-4892-9CBC-D523E92BA78D}']
    function getNewTagEventModeratedTimeoutMilliseconds : SmallInt; cdecl;      // ()S A: $1
    function getReportNewTagEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;           // ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getReportTagBackToVisibilityEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;// ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getReportTagInvisibleEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;     // ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getTagBackToVisibilityModeratedTimeoutMilliseconds : SmallInt; cdecl;// ()S A: $1
    function getTagInvisibleEventModeratedTimeoutMilliseconds : SmallInt; cdecl;// ()S A: $1
    procedure setNewTagEventModeratedTimeoutMilliseconds(newTagEventModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
    procedure setReportNewTagEvent(reportNewTagEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setReportTagBackToVisibilityEvent(reportTagBackToVisibilityEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setReportTagInvisibleEvent(reportTagInvisibleEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setTagBackToVisibilityModeratedTimeoutMilliseconds(tagBackToVisibilityModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
    procedure setTagInvisibleEventModeratedTimeoutMilliseconds(tagInvisibleEventModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagEventReportInfo')]
  JTagEventReportInfo = interface(JObject)
    ['{E22E6963-3D11-4BA2-BA72-DED3DE71560D}']
    function getNewTagEventModeratedTimeoutMilliseconds : SmallInt; cdecl;      // ()S A: $1
    function getReportNewTagEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;           // ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getReportTagBackToVisibilityEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;// ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getReportTagInvisibleEvent : JTAG_EVENT_REPORT_TRIGGER; cdecl;     // ()Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER; A: $1
    function getTagBackToVisibilityModeratedTimeoutMilliseconds : SmallInt; cdecl;// ()S A: $1
    function getTagInvisibleEventModeratedTimeoutMilliseconds : SmallInt; cdecl;// ()S A: $1
    procedure setNewTagEventModeratedTimeoutMilliseconds(newTagEventModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
    procedure setReportNewTagEvent(reportNewTagEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setReportTagBackToVisibilityEvent(reportTagBackToVisibilityEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setReportTagInvisibleEvent(reportTagInvisibleEvent : JTAG_EVENT_REPORT_TRIGGER) ; cdecl;// (Lcom/zebra/rfid/api3/TAG_EVENT_REPORT_TRIGGER;)V A: $1
    procedure setTagBackToVisibilityModeratedTimeoutMilliseconds(tagBackToVisibilityModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
    procedure setTagInvisibleEventModeratedTimeoutMilliseconds(tagInvisibleEventModeratedTimeoutMilliseconds : SmallInt) ; cdecl;// (S)V A: $1
  end;

  TJTagEventReportInfo = class(TJavaGenericImport<JTagEventReportInfoClass, JTagEventReportInfo>)
  end;

implementation

end.
