//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.SecureModeConfig;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JSecureModeConfig = interface;

  JSecureModeConfigClass = interface(JObjectClass)
    ['{A38D49C8-969F-485B-8875-84BDD3917B33}']
    function init : JSecureModeConfig; cdecl;                                   // ()V A: $1
    function isSecureModeEnabled : boolean; cdecl;                              // ()Z A: $1
    function isValidatePeerCertificateEnabled : boolean; cdecl;                 // ()Z A: $1
    procedure setSecureMode(secureMode : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setValidatePeerCerticate(validatePeerCertificate : boolean) ; cdecl;// (Z)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/SecureModeConfig')]
  JSecureModeConfig = interface(JObject)
    ['{5CCD72DE-0247-4F20-8DA3-F65AC2329C09}']
    function isSecureModeEnabled : boolean; cdecl;                              // ()Z A: $1
    function isValidatePeerCertificateEnabled : boolean; cdecl;                 // ()Z A: $1
    procedure setSecureMode(secureMode : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setValidatePeerCerticate(validatePeerCertificate : boolean) ; cdecl;// (Z)V A: $1
  end;

  TJSecureModeConfig = class(TJavaGenericImport<JSecureModeConfigClass, JSecureModeConfig>)
  end;

implementation

end.
