//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.cr;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jcr = interface;

  JcrClass = interface(JObjectClass)
    ['{1C6C8811-A4E5-4F59-86DD-4622AD329947}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : TJavaArray<SmallInt>; cdecl;                               //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : TJavaArray<SmallInt>) ; cdecl;                      //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : TJavaArray<SmallInt> read _Getb write _Setb;                   // [S A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/cr')]
  Jcr = interface(JObject)
    ['{EE137708-5578-4469-9332-57F65F69A8A8}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    function _Getb : TJavaArray<SmallInt>; cdecl;                               //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    procedure _Setb(Value : TJavaArray<SmallInt>) ; cdecl;                      //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
    property b : TJavaArray<SmallInt> read _Getb write _Setb;                   // [S A: $1
  end;

  TJcr = class(TJavaGenericImport<JcrClass, Jcr>)
  end;

implementation

end.
