//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Readers;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Readers_RFIDReaderEventHandler,
  Androidapi.JNI.GraphicsContentViewText,
  android.content.Intent,
  android.bluetooth.BluetoothDevice;

type
  JReaders = interface;

  JReadersClass = interface(JObjectClass)
    ['{B9664128-C282-402D-B3C8-4C66E64753F2}']
    function GetActiveRFIDReaderList : JArrayList; cdecl;                       // ()Ljava/util/ArrayList; A: $1
    function GetAvailableRFIDReaderList : JArrayList; cdecl;                    // ()Ljava/util/ArrayList; A: $1
    function init : JReaders; cdecl;                                            // ()V A: $1
    procedure EnableAutomaticReconnection(enable : boolean) ; cdecl;            // (Z)V A: $1
    procedure EnableAvailableRFIDReadersDetection(enable : boolean) ; cdecl;    // (Z)V A: $1
    procedure attach(rfidReaderEventHandler : JReaders_RFIDReaderEventHandler) ; cdecl;// (Lcom/zebra/rfid/api3/Readers$RFIDReaderEventHandler;)V A: $9
    procedure deattach(rfidReaderEventHandler : JReaders_RFIDReaderEventHandler) ; cdecl;// (Lcom/zebra/rfid/api3/Readers$RFIDReaderEventHandler;)V A: $9
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Readers$RFIDReaderEventHandler')]
  JReaders = interface(JObject)
    ['{1EC628FE-4E5C-49E0-91E4-09E78D5DACB4}']
    function GetActiveRFIDReaderList : JArrayList; cdecl;                       // ()Ljava/util/ArrayList; A: $1
    function GetAvailableRFIDReaderList : JArrayList; cdecl;                    // ()Ljava/util/ArrayList; A: $1
    procedure EnableAutomaticReconnection(enable : boolean) ; cdecl;            // (Z)V A: $1
    procedure EnableAvailableRFIDReadersDetection(enable : boolean) ; cdecl;    // (Z)V A: $1
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  TJReaders = class(TJavaGenericImport<JReadersClass, JReaders>)
  end;

implementation

end.
