//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ImpinjStats;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JImpinjStats = interface;

  JImpinjStatsClass = interface(JObjectClass)
    ['{2268EB43-0BAD-4ED6-BA63-713CDDA01DB7}']
    function getQTFailureCount : Integer; cdecl;                                // ()I A: $1
    function getQTSuccesCount : Integer; cdecl;                                 // ()I A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ImpinjStats')]
  JImpinjStats = interface(JObject)
    ['{C101D235-E7A6-441E-B151-D8E28FD59856}']
    function getQTFailureCount : Integer; cdecl;                                // ()I A: $1
    function getQTSuccesCount : Integer; cdecl;                                 // ()I A: $1
  end;

  TJImpinjStats = class(TJavaGenericImport<JImpinjStatsClass, JImpinjStats>)
  end;

implementation

end.
