//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ch;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.ad,
  com.zebra.rfid.api3.ct,
  com.zebra.rfid.api3.ag;

type
  Jch = interface;

  JchClass = interface(JObjectClass)
    ['{DA97ECCE-849A-4A86-940B-ACF0AB3BAB90}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : Jad; cdecl;                                                //  A: $1
    function _Getc : Jct; cdecl;                                                //  A: $1
    function _Getd : Jct; cdecl;                                                //  A: $1
    function _Gete : Jag; cdecl;                                                //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : Jad) ; cdecl;                                       //  A: $1
    procedure _Setc(Value : Jct) ; cdecl;                                       //  A: $1
    procedure _Setd(Value : Jct) ; cdecl;                                       //  A: $1
    procedure _Sete(Value : Jag) ; cdecl;                                       //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : Jad read _Getb write _Setb;                                    // Lcom/zebra/rfid/api3/ad; A: $1
    property c : Jct read _Getc write _Setc;                                    // Lcom/zebra/rfid/api3/ct; A: $1
    property d : Jct read _Getd write _Setd;                                    // Lcom/zebra/rfid/api3/ct; A: $1
    property e : Jag read _Gete write _Sete;                                    // Lcom/zebra/rfid/api3/ag; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ch')]
  Jch = interface(JObject)
    ['{7B991D8D-EEDE-4BBB-863B-9F1D9BDE17EE}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : Jad; cdecl;                                                //  A: $1
    function _Getc : Jct; cdecl;                                                //  A: $1
    function _Getd : Jct; cdecl;                                                //  A: $1
    function _Gete : Jag; cdecl;                                                //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : Jad) ; cdecl;                                       //  A: $1
    procedure _Setc(Value : Jct) ; cdecl;                                       //  A: $1
    procedure _Setd(Value : Jct) ; cdecl;                                       //  A: $1
    procedure _Sete(Value : Jag) ; cdecl;                                       //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : Jad read _Getb write _Setb;                                    // Lcom/zebra/rfid/api3/ad; A: $1
    property c : Jct read _Getc write _Setc;                                    // Lcom/zebra/rfid/api3/ct; A: $1
    property d : Jct read _Getd write _Setd;                                    // Lcom/zebra/rfid/api3/ct; A: $1
    property e : Jag read _Gete write _Sete;                                    // Lcom/zebra/rfid/api3/ag; A: $1
  end;

  TJch = class(TJavaGenericImport<JchClass, Jch>)
  end;

implementation

end.
