//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bl;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jbl = interface;

  JblClass = interface(JObjectClass)
    ['{E6FBD1A1-71FD-4712-A2F2-2663CA410ECE}']
    function _Geta : JString; cdecl;                                            //  A: $1
    function _Getb : JString; cdecl;                                            //  A: $1
    function _Getc : JString; cdecl;                                            //  A: $1
    function _Getd : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setd(Value : JString) ; cdecl;                                   //  A: $1
    property a : JString read _Geta write _Seta;                                // Ljava/lang/String; A: $1
    property b : JString read _Getb write _Setb;                                // Ljava/lang/String; A: $1
    property c : JString read _Getc write _Setc;                                // Ljava/lang/String; A: $1
    property d : JString read _Getd write _Setd;                                // Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/bl')]
  Jbl = interface(JObject)
    ['{DBC4E358-CE75-4FF1-8BAC-B4F4271A8AE8}']
    function _Geta : JString; cdecl;                                            //  A: $1
    function _Getb : JString; cdecl;                                            //  A: $1
    function _Getc : JString; cdecl;                                            //  A: $1
    function _Getd : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : JString) ; cdecl;                                   //  A: $1
    procedure _Setd(Value : JString) ; cdecl;                                   //  A: $1
    property a : JString read _Geta write _Seta;                                // Ljava/lang/String; A: $1
    property b : JString read _Getb write _Setb;                                // Ljava/lang/String; A: $1
    property c : JString read _Getc write _Setc;                                // Ljava/lang/String; A: $1
    property d : JString read _Getd write _Setd;                                // Ljava/lang/String; A: $1
  end;

  TJbl = class(TJavaGenericImport<JblClass, Jbl>)
  end;

implementation

end.
