//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.FrequencyHopInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.FrequencyHopTable;

type
  JFrequencyHopInfo = interface;

  JFrequencyHopInfoClass = interface(JObjectClass)
    ['{1ABCA475-A955-4C51-B632-238643DFFE8E}']
    function Length : Integer; cdecl;                                           // ()I A: $1
    function getFrepuencyHopTablesInfo(&index : Integer) : JFrequencyHopTable; cdecl;// (I)Lcom/zebra/rfid/api3/FrequencyHopTable; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/FrequencyHopInfo')]
  JFrequencyHopInfo = interface(JObject)
    ['{59F93FED-3C73-4FDE-B8FA-9A2EF5633C31}']
    function Length : Integer; cdecl;                                           // ()I A: $1
    function getFrepuencyHopTablesInfo(&index : Integer) : JFrequencyHopTable; cdecl;// (I)Lcom/zebra/rfid/api3/FrequencyHopTable; A: $1
  end;

  TJFrequencyHopInfo = class(TJavaGenericImport<JFrequencyHopInfoClass, JFrequencyHopInfo>)
  end;

implementation

end.
