//
// Generated by JavaToPas v1.5 20170214 - 172215
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_GetCapabilities;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_GetCapabilities = interface;

  JCommand_GetCapabilitiesClass = interface(JObjectClass)
    ['{135EA801-9795-4CE6-9D84-1F773FD5E575}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function init : JCommand_GetCapabilities; cdecl;                            // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_GetCapabilities')]
  JCommand_GetCapabilities = interface(JObject)
    ['{47C2EB0F-A7A1-4C66-AAC0-7E4D72A3876F}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
  end;

  TJCommand_GetCapabilities = class(TJavaGenericImport<JCommand_GetCapabilitiesClass, JCommand_GetCapabilities>)
  end;

const
  TJCommand_GetCapabilitiescommandName = 'GetCapabilities';

implementation

end.
