//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.BluetoothService;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.bluetooth.BluetoothAdapter,
  Androidapi.JNI.os,
  com.zebra.rfid.api3.BluetoothService_a,
  com.zebra.rfid.api3.BluetoothService_BluetoothDataHandler,
  Androidapi.JNI.GraphicsContentViewText,
  android.bluetooth.BluetoothDevice,
  android.bluetooth.BluetoothSocket,
  java.io.BufferedReader;

type
  JBluetoothService_c = interface; // merged
  JBluetoothService_b = interface; // merged
  JBluetoothService = interface;

  JBluetoothServiceClass = interface(JObjectClass)
    ['{FC9C39FA-2478-4FF3-BF20-603131D51341}']
    function init(context : JContext; handler : JHandler) : JBluetoothService; cdecl;// (Landroid/content/Context;Landroid/os/Handler;)V A: $1
    procedure a ; cdecl; overload;                                              // ()V A: $21
    procedure a(JBluetoothDeviceparam0 : JBluetoothDevice) ; cdecl; overload;   // (Landroid/bluetooth/BluetoothDevice;)V A: $21
    procedure a(JBluetoothService_BluetoothDataHandlerparam0 : JBluetoothService_BluetoothDataHandler) ; cdecl; overload;// (Lcom/zebra/rfid/api3/BluetoothService$BluetoothDataHandler;)V A: $1
    procedure a(JBluetoothSocketparam0 : JBluetoothSocket; JBluetoothDeviceparam1 : JBluetoothDevice) ; cdecl; overload;// (Landroid/bluetooth/BluetoothSocket;Landroid/bluetooth/BluetoothDevice;)V A: $21
    procedure a(JSetparam0 : JSet) ; cdecl; overload;                           // (Ljava/util/Set;)V A: $1
    procedure a(TJavaArrayByteparam0 : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
    procedure b ; cdecl; overload;                                              // ()V A: $21
    procedure c ; cdecl; overload;                                              // ()V A: $21
  end;

  [JavaSignature('com/zebra/rfid/api3/BluetoothService$c')]
  JBluetoothService = interface(JObject)
    ['{9C429572-326F-48FA-9EF8-DE1154E907D8}']
    procedure a(JBluetoothService_BluetoothDataHandlerparam0 : JBluetoothService_BluetoothDataHandler) ; cdecl; overload;// (Lcom/zebra/rfid/api3/BluetoothService$BluetoothDataHandler;)V A: $1
    procedure a(JSetparam0 : JSet) ; cdecl; overload;                           // (Ljava/util/Set;)V A: $1
    procedure a(TJavaArrayByteparam0 : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
  end;

  TJBluetoothService = class(TJavaGenericImport<JBluetoothServiceClass, JBluetoothService>)
  end;

  // Merged from: .\com.zebra.rfid.api3.BluetoothService_b.pas
  JBluetoothService_bClass = interface(JObjectClass)
    ['{8807751D-6259-4A4F-8FB2-7A20D7202617}']
    function init(JBluetoothServiceparam0 : JBluetoothService; JBluetoothDeviceparam1 : JBluetoothDevice) : JBluetoothService_b; cdecl;// (Lcom/zebra/rfid/api3/BluetoothService;Landroid/bluetooth/BluetoothDevice;)V A: $1
    procedure a ; cdecl;                                                        // ()V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/BluetoothService_b')]
  JBluetoothService_b = interface(JObject)
    ['{FEF1D85B-3A43-4738-91A2-43A2C0EB3747}']
    procedure a ; cdecl;                                                        // ()V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJBluetoothService_b = class(TJavaGenericImport<JBluetoothService_bClass, JBluetoothService_b>)
  end;


  // Merged from: .\com.zebra.rfid.api3.BluetoothService_c.pas
  JBluetoothService_cClass = interface(JObjectClass)
    ['{770B1362-166E-4816-88BA-2BBE7DBEB1A8}']
    function init(JBluetoothServiceparam0 : JBluetoothService; JBluetoothSocketparam1 : JBluetoothSocket; JBluetoothDeviceparam2 : JBluetoothDevice) : JBluetoothService_c; cdecl;// (Lcom/zebra/rfid/api3/BluetoothService;Landroid/bluetooth/BluetoothSocket;Landroid/bluetooth/BluetoothDevice;)V A: $1
    procedure a ; cdecl; overload;                                              // ()V A: $1
    procedure a(TJavaArrayByteparam0 : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/BluetoothService_c')]
  JBluetoothService_c = interface(JObject)
    ['{4C351EB0-E6E6-41C7-B939-8AA79260DD00}']
    procedure a ; cdecl; overload;                                              // ()V A: $1
    procedure a(TJavaArrayByteparam0 : TJavaArray<Byte>) ; cdecl; overload;     // ([B)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJBluetoothService_c = class(TJavaGenericImport<JBluetoothService_cClass, JBluetoothService_c>)
  end;


implementation

end.
