//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.HANDHELD_TRIGGER_EVENT_TYPE;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JHANDHELD_TRIGGER_EVENT_TYPE = interface;

  JHANDHELD_TRIGGER_EVENT_TYPEClass = interface(JObjectClass)
    ['{6D47515B-D509-4613-A5DF-8C3015E9331A}']
    function GetHandleTriggerEventTypeValue(value : Integer) : JHANDHELD_TRIGGER_EVENT_TYPE; cdecl;// (I)Lcom/zebra/rfid/api3/HANDHELD_TRIGGER_EVENT_TYPE; A: $9
    function _GetHANDHELD_TRIGGER_PRESSED : JHANDHELD_TRIGGER_EVENT_TYPE; cdecl;//  A: $19
    function _GetHANDHELD_TRIGGER_RELEASED : JHANDHELD_TRIGGER_EVENT_TYPE; cdecl;//  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property HANDHELD_TRIGGER_PRESSED : JHANDHELD_TRIGGER_EVENT_TYPE read _GetHANDHELD_TRIGGER_PRESSED;// Lcom/zebra/rfid/api3/HANDHELD_TRIGGER_EVENT_TYPE; A: $19
    property HANDHELD_TRIGGER_RELEASED : JHANDHELD_TRIGGER_EVENT_TYPE read _GetHANDHELD_TRIGGER_RELEASED;// Lcom/zebra/rfid/api3/HANDHELD_TRIGGER_EVENT_TYPE; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/HANDHELD_TRIGGER_EVENT_TYPE')]
  JHANDHELD_TRIGGER_EVENT_TYPE = interface(JObject)
    ['{23EAD681-1E92-46A8-9A06-AD7EF748DE67}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJHANDHELD_TRIGGER_EVENT_TYPE = class(TJavaGenericImport<JHANDHELD_TRIGGER_EVENT_TYPEClass, JHANDHELD_TRIGGER_EVENT_TYPE>)
  end;

implementation

end.
