//
// Generated by JavaToPas v1.5 20170214 - 172214
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_admdisconnect;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_admdisconnect = interface;

  JCommand_admdisconnectClass = interface(JObjectClass)
    ['{C0DD934D-BFC2-4D83-B79E-C7EE62E7E092}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function init : JCommand_admdisconnect; cdecl;                              // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_admdisconnect')]
  JCommand_admdisconnect = interface(JObject)
    ['{AEDB059D-6230-4DBF-BE55-BAFCC18E5396}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
  end;

  TJCommand_admdisconnect = class(TJavaGenericImport<JCommand_admdisconnectClass, JCommand_admdisconnect>)
  end;

const
  TJCommand_admdisconnectcommandName = 'admdisconnect';

implementation

end.
