//
// Generated by JavaToPas v1.5 20170214 - 172217
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.AccessFilter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.TagPatternBase,
  com.zebra.rfid.api3.RssiRangeFilter,
  com.zebra.rfid.api3.FILTER_MATCH_PATTERN;

type
  JAccessFilter = interface;

  JAccessFilterClass = interface(JObjectClass)
    ['{B5D73FD3-8C3F-43C6-9ED2-DA69CC3C452A}']
    function _GetRssiRangeFilter : JRssiRangeFilter; cdecl;                     //  A: $1
    function _GetTagPatternA : JTagPatternBase; cdecl;                          //  A: $1
    function _GetTagPatternB : JTagPatternBase; cdecl;                          //  A: $1
    function getAccessFilterMatchPattern : JFILTER_MATCH_PATTERN; cdecl;        // ()Lcom/zebra/rfid/api3/FILTER_MATCH_PATTERN; A: $1
    function init : JAccessFilter; cdecl;                                       // ()V A: $1
    function isRSSIRangeFilterUsed : boolean; cdecl;                            // ()Z A: $1
    procedure _SetRssiRangeFilter(Value : JRssiRangeFilter) ; cdecl;            //  A: $1
    procedure _SetTagPatternA(Value : JTagPatternBase) ; cdecl;                 //  A: $1
    procedure _SetTagPatternB(Value : JTagPatternBase) ; cdecl;                 //  A: $1
    procedure setAccessFilterMatchPattern(accessFilterMatchPattern : JFILTER_MATCH_PATTERN) ; cdecl;// (Lcom/zebra/rfid/api3/FILTER_MATCH_PATTERN;)V A: $1
    procedure setRSSIRangeFilter(useRSSIRangeFilter : boolean) ; cdecl;         // (Z)V A: $1
    property RssiRangeFilter : JRssiRangeFilter read _GetRssiRangeFilter write _SetRssiRangeFilter;// Lcom/zebra/rfid/api3/RssiRangeFilter; A: $1
    property TagPatternA : JTagPatternBase read _GetTagPatternA write _SetTagPatternA;// Lcom/zebra/rfid/api3/TagPatternBase; A: $1
    property TagPatternB : JTagPatternBase read _GetTagPatternB write _SetTagPatternB;// Lcom/zebra/rfid/api3/TagPatternBase; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/AccessFilter')]
  JAccessFilter = interface(JObject)
    ['{2AA2FD72-5FE6-422C-9E21-93E2FF2618C8}']
    function _GetRssiRangeFilter : JRssiRangeFilter; cdecl;                     //  A: $1
    function _GetTagPatternA : JTagPatternBase; cdecl;                          //  A: $1
    function _GetTagPatternB : JTagPatternBase; cdecl;                          //  A: $1
    function getAccessFilterMatchPattern : JFILTER_MATCH_PATTERN; cdecl;        // ()Lcom/zebra/rfid/api3/FILTER_MATCH_PATTERN; A: $1
    function isRSSIRangeFilterUsed : boolean; cdecl;                            // ()Z A: $1
    procedure _SetRssiRangeFilter(Value : JRssiRangeFilter) ; cdecl;            //  A: $1
    procedure _SetTagPatternA(Value : JTagPatternBase) ; cdecl;                 //  A: $1
    procedure _SetTagPatternB(Value : JTagPatternBase) ; cdecl;                 //  A: $1
    procedure setAccessFilterMatchPattern(accessFilterMatchPattern : JFILTER_MATCH_PATTERN) ; cdecl;// (Lcom/zebra/rfid/api3/FILTER_MATCH_PATTERN;)V A: $1
    procedure setRSSIRangeFilter(useRSSIRangeFilter : boolean) ; cdecl;         // (Z)V A: $1
    property RssiRangeFilter : JRssiRangeFilter read _GetRssiRangeFilter write _SetRssiRangeFilter;// Lcom/zebra/rfid/api3/RssiRangeFilter; A: $1
    property TagPatternA : JTagPatternBase read _GetTagPatternA write _SetTagPatternA;// Lcom/zebra/rfid/api3/TagPatternBase; A: $1
    property TagPatternB : JTagPatternBase read _GetTagPatternB write _SetTagPatternB;// Lcom/zebra/rfid/api3/TagPatternBase; A: $1
  end;

  TJAccessFilter = class(TJavaGenericImport<JAccessFilterClass, JAccessFilter>)
  end;

implementation

end.
