//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RfidReadEvents;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Events_ReadEventData;

type
  JRfidReadEvents = interface;

  JRfidReadEventsClass = interface(JObjectClass)
    ['{616FAFDC-71F8-4AF8-8F48-21BC36344A0D}']
    function getReadEventData : JEvents_ReadEventData; cdecl;                   // ()Lcom/zebra/rfid/api3/Events$ReadEventData; A: $1
    function init(source : JObject) : JRfidReadEvents; cdecl;                   // (Ljava/lang/Object;)V A: $1
    procedure setReadEventData(readEventData : JEvents_ReadEventData) ; cdecl;  // (Lcom/zebra/rfid/api3/Events$ReadEventData;)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/RfidReadEvents')]
  JRfidReadEvents = interface(JObject)
    ['{9C0F571D-24EC-4C30-9EB7-D64E661A1E4A}']
    function getReadEventData : JEvents_ReadEventData; cdecl;                   // ()Lcom/zebra/rfid/api3/Events$ReadEventData; A: $1
    procedure setReadEventData(readEventData : JEvents_ReadEventData) ; cdecl;  // (Lcom/zebra/rfid/api3/Events$ReadEventData;)V A: $1
  end;

  TJRfidReadEvents = class(TJavaGenericImport<JRfidReadEventsClass, JRfidReadEvents>)
  end;

implementation

end.
