//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TRACE_LEVEL;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JTRACE_LEVEL = interface;

  JTRACE_LEVELClass = interface(JObjectClass)
    ['{BCE67D54-4355-4A6A-B465-4482A758C245}']
    function _GetTRACE_LEVEL_ALL : JTRACE_LEVEL; cdecl;                         //  A: $19
    function _GetTRACE_LEVEL_ERROR : JTRACE_LEVEL; cdecl;                       //  A: $19
    function _GetTRACE_LEVEL_FATAL : JTRACE_LEVEL; cdecl;                       //  A: $19
    function _GetTRACE_LEVEL_INFO : JTRACE_LEVEL; cdecl;                        //  A: $19
    function _GetTRACE_LEVEL_OFF : JTRACE_LEVEL; cdecl;                         //  A: $19
    function _GetTRACE_LEVEL_VERBOSE : JTRACE_LEVEL; cdecl;                     //  A: $19
    function _GetTRACE_LEVEL_WARNING : JTRACE_LEVEL; cdecl;                     //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property TRACE_LEVEL_ALL : JTRACE_LEVEL read _GetTRACE_LEVEL_ALL;           // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_ERROR : JTRACE_LEVEL read _GetTRACE_LEVEL_ERROR;       // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_FATAL : JTRACE_LEVEL read _GetTRACE_LEVEL_FATAL;       // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_INFO : JTRACE_LEVEL read _GetTRACE_LEVEL_INFO;         // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_OFF : JTRACE_LEVEL read _GetTRACE_LEVEL_OFF;           // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_VERBOSE : JTRACE_LEVEL read _GetTRACE_LEVEL_VERBOSE;   // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property TRACE_LEVEL_WARNING : JTRACE_LEVEL read _GetTRACE_LEVEL_WARNING;   // Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/TRACE_LEVEL')]
  JTRACE_LEVEL = interface(JObject)
    ['{E573A4CF-079F-483D-92DA-D7582E2E5A11}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJTRACE_LEVEL = class(TJavaGenericImport<JTRACE_LEVELClass, JTRACE_LEVEL>)
  end;

implementation

end.
