//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TransportAbstract;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.concurrent.BlockingQueue;

type
  JTransportAbstract = interface;

  JTransportAbstractClass = interface(JObjectClass)
    ['{6306B2F0-8FAB-4F33-840B-C020FE953305}']
    function Connect(JStringparam0 : JString) : boolean; cdecl;                 // (Ljava/lang/String;)Z A: $401
    function ReConnect : boolean; cdecl;                                        // ()Z A: $401
    function ReadData : JString; cdecl;                                         // ()Ljava/lang/String; A: $401
    function init : JTransportAbstract; cdecl;                                  // ()V A: $1
    procedure Disconnect ; cdecl;                                               // ()V A: $401
    procedure SetQueue(JBlockingQueueparam0 : JBlockingQueue) ; cdecl;          // (Ljava/util/concurrent/BlockingQueue;)V A: $401
    procedure WriteData(JStringparam0 : JString) ; cdecl;                       // (Ljava/lang/String;)V A: $401
  end;

  [JavaSignature('com/zebra/rfid/api3/TransportAbstract')]
  JTransportAbstract = interface(JObject)
    ['{0FF54C9A-1335-4531-90FD-C9E7FE5EEA8C}']
    function Connect(JStringparam0 : JString) : boolean; cdecl;                 // (Ljava/lang/String;)Z A: $401
    function ReConnect : boolean; cdecl;                                        // ()Z A: $401
    function ReadData : JString; cdecl;                                         // ()Ljava/lang/String; A: $401
    procedure Disconnect ; cdecl;                                               // ()V A: $401
    procedure SetQueue(JBlockingQueueparam0 : JBlockingQueue) ; cdecl;          // (Ljava/util/concurrent/BlockingQueue;)V A: $401
    procedure WriteData(JStringparam0 : JString) ; cdecl;                       // (Ljava/lang/String;)V A: $401
  end;

  TJTransportAbstract = class(TJavaGenericImport<JTransportAbstractClass, JTransportAbstract>)
  end;

implementation

end.
