//
// Generated by JavaToPas v1.5 20170214 - 172215
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_GetRegion;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_GetRegion = interface;

  JCommand_GetRegionClass = interface(JObjectClass)
    ['{1847FBE1-7EAD-4990-9193-6F51A0689428}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getregion : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    function init : JCommand_GetRegion; cdecl;                                  // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setregion(value : JString) ; cdecl;                               // (Ljava/lang/String;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_GetRegion')]
  JCommand_GetRegion = interface(JObject)
    ['{D37080D0-F066-4EB5-BFF7-4EB59069660A}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getregion : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setregion(value : JString) ; cdecl;                               // (Ljava/lang/String;)V A: $1
  end;

  TJCommand_GetRegion = class(TJavaGenericImport<JCommand_GetRegionClass, JCommand_GetRegion>)
  end;

const
  TJCommand_GetRegioncommandName = 'GetRegion';

implementation

end.
