//
// Generated by JavaToPas v1.5 20170214 - 172214
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Command_Connect;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.COMMAND_TYPE;

type
  JCommand_Connect = interface;

  JCommand_ConnectClass = interface(JObjectClass)
    ['{F2EE0928-6A86-445B-BF66-81227FEEE04B}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function _GetcommandName : JString; cdecl;                                  //  A: $19
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getdisableLowPower : boolean; cdecl;                               // ()Z A: $1
    function getoverride : boolean; cdecl;                                      // ()Z A: $1
    function getpassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function init : JCommand_Connect; cdecl;                                    // ()V A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setdisableLowPower(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setoverride(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setpassword(value : JString) ; cdecl;                             // (Ljava/lang/String;)V A: $1
    property commandName : JString read _GetcommandName;                        // Ljava/lang/String; A: $19
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Command_Connect')]
  JCommand_Connect = interface(JObject)
    ['{BE60D4D3-6365-4DE6-8535-27883B525AB6}']
    function ToString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function getCommandType : JCOMMAND_TYPE; cdecl;                             // ()Lcom/zebra/ASCII_SDK/COMMAND_TYPE; A: $1
    function getdisableLowPower : boolean; cdecl;                               // ()Z A: $1
    function getoverride : boolean; cdecl;                                      // ()Z A: $1
    function getpassword : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    procedure FromString(str : JString) ; cdecl;                                // (Ljava/lang/String;)V A: $1
    procedure setdisableLowPower(value : boolean) ; cdecl;                      // (Z)V A: $1
    procedure setoverride(value : boolean) ; cdecl;                             // (Z)V A: $1
    procedure setpassword(value : JString) ; cdecl;                             // (Ljava/lang/String;)V A: $1
  end;

  TJCommand_Connect = class(TJavaGenericImport<JCommand_ConnectClass, JCommand_Connect>)
  end;

const
  TJCommand_ConnectcommandName = 'Connect';

implementation

end.
