//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.ai;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jai = interface;

  JaiClass = interface(JObjectClass)
    ['{B77C6795-EE0C-4129-B6BB-CF549B2A236C}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/ai')]
  Jai = interface(JObject)
    ['{C6AB0535-A828-4064-BCD5-1DFA8CEB9F5E}']
    function _Geta : SmallInt; cdecl;                                           //  A: $1
    procedure _Seta(Value : SmallInt) ; cdecl;                                  //  A: $1
    property a : SmallInt read _Geta write _Seta;                               // S A: $1
  end;

  TJai = class(TJavaGenericImport<JaiClass, Jai>)
  end;

implementation

end.
