//
// Generated by JavaToPas v1.5 20170214 - 172224
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.RfidEventsListener;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.RfidReadEvents,
  com.zebra.rfid.api3.RfidStatusEvents;

type
  JRfidEventsListener = interface;

  JRfidEventsListenerClass = interface(JObjectClass)
    ['{FF0E7EA5-3C53-4559-B920-7D5B51C8C61E}']
    procedure eventReadNotify(JRfidReadEventsparam0 : JRfidReadEvents) ; cdecl; // (Lcom/zebra/rfid/api3/RfidReadEvents;)V A: $401
    procedure eventStatusNotify(JRfidStatusEventsparam0 : JRfidStatusEvents) ; cdecl;// (Lcom/zebra/rfid/api3/RfidStatusEvents;)V A: $401
  end;

  [JavaSignature('com/zebra/rfid/api3/RfidEventsListener')]
  JRfidEventsListener = interface(JObject)
    ['{8DEDA623-C99D-4713-86DD-8B04A3F3C7F4}']
    procedure eventReadNotify(JRfidReadEventsparam0 : JRfidReadEvents) ; cdecl; // (Lcom/zebra/rfid/api3/RfidReadEvents;)V A: $401
    procedure eventStatusNotify(JRfidStatusEventsparam0 : JRfidStatusEvents) ; cdecl;// (Lcom/zebra/rfid/api3/RfidStatusEvents;)V A: $401
  end;

  TJRfidEventsListener = class(TJavaGenericImport<JRfidEventsListenerClass, JRfidEventsListener>)
  end;

implementation

end.
