//
// Generated by JavaToPas v1.5 20170214 - 172225
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TagAccess_KillAccessParams;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Impinj;

type
  JTagAccess_KillAccessParams = interface;

  JTagAccess_KillAccessParamsClass = interface(JObjectClass)
    ['{0A5FFAC0-44CC-4BE8-8B4E-3FA511C03CFF}']
    function getKillPassword : Int64; cdecl;                                    // ()J A: $1
    function init(JTagAccessparam0 : JTagAccess) : JTagAccess_KillAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;)V A: $1
    function init(m_nKillPassword : Int64) : JTagAccess_KillAccessParams; cdecl; overload;// (Lcom/zebra/rfid/api3/TagAccess;J)V A: $1
    procedure setKillPassword(killPassword : Int64) ; cdecl;                    // (J)V A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/TagAccess_KillAccessParams')]
  JTagAccess_KillAccessParams = interface(JObject)
    ['{F1A5316A-D2D5-4E70-90D6-7CA2DA6516CB}']
    function getKillPassword : Int64; cdecl;                                    // ()J A: $1
    procedure setKillPassword(killPassword : Int64) ; cdecl;                    // (J)V A: $1
  end;

  TJTagAccess_KillAccessParams = class(TJavaGenericImport<JTagAccess_KillAccessParamsClass, JTagAccess_KillAccessParams>)
  end;

implementation

end.
