//
// Generated by JavaToPas v1.5 20170214 - 172217
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.ASCII_SDK.Response_VersionInfo;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.ASCII_SDK.RESPONSE_TYPE,
  com.zebra.ASCII_SDK.MetaData;

type
  JResponse_VersionInfo = interface;

  JResponse_VersionInfoClass = interface(JObjectClass)
    ['{FADF46E0-0A6F-4D22-9496-54E39BB83EDD}']
    function FromString(str : JString; mData : JMetaData) : JResponse_VersionInfo; cdecl;// (Ljava/lang/String;Lcom/zebra/ASCII_SDK/MetaData;)Lcom/zebra/ASCII_SDK/Response_VersionInfo; A: $9
    function _GetDevice : JString; cdecl;                                       //  A: $1
    function _GetVersion : JString; cdecl;                                      //  A: $1
    function getResponseType : JRESPONSE_TYPE; cdecl;                           // ()Lcom/zebra/ASCII_SDK/RESPONSE_TYPE; A: $1
    function init : JResponse_VersionInfo; cdecl;                               // ()V A: $1
    procedure _SetDevice(Value : JString) ; cdecl;                              //  A: $1
    procedure _SetVersion(Value : JString) ; cdecl;                             //  A: $1
    property Device : JString read _GetDevice write _SetDevice;                 // Ljava/lang/String; A: $1
    property Version : JString read _GetVersion write _SetVersion;              // Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/ASCII_SDK/Response_VersionInfo')]
  JResponse_VersionInfo = interface(JObject)
    ['{2F9FF89D-5EE1-4044-9E0D-F3118B7D8FFE}']
    function _GetDevice : JString; cdecl;                                       //  A: $1
    function _GetVersion : JString; cdecl;                                      //  A: $1
    function getResponseType : JRESPONSE_TYPE; cdecl;                           // ()Lcom/zebra/ASCII_SDK/RESPONSE_TYPE; A: $1
    procedure _SetDevice(Value : JString) ; cdecl;                              //  A: $1
    procedure _SetVersion(Value : JString) ; cdecl;                             //  A: $1
    property Device : JString read _GetDevice write _SetDevice;                 // Ljava/lang/String; A: $1
    property Version : JString read _GetVersion write _SetVersion;              // Ljava/lang/String; A: $1
  end;

  TJResponse_VersionInfo = class(TJavaGenericImport<JResponse_VersionInfoClass, JResponse_VersionInfo>)
  end;

implementation

end.
