//
// Generated by JavaToPas v1.5 20170214 - 172221
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.GPI_PORT_STATE;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.TreeMap;

type
  JGPI_PORT_STATE = interface;

  JGPI_PORT_STATEClass = interface(JObjectClass)
    ['{305C64A6-9F13-4E98-89F1-B7A6FBE48C8B}']
    function GetGpiPortState(value : Integer) : JGPI_PORT_STATE; cdecl;         // (I)Lcom/zebra/rfid/api3/GPI_PORT_STATE; A: $9
    function _GetGPI_PORT_STATE_HIGH : JGPI_PORT_STATE; cdecl;                  //  A: $19
    function _GetGPI_PORT_STATE_LOW : JGPI_PORT_STATE; cdecl;                   //  A: $19
    function _GetGPI_PORT_STATE_UNKNOWN : JGPI_PORT_STATE; cdecl;               //  A: $19
    function _Getordinal : Integer; cdecl;                                      //  A: $11
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    property GPI_PORT_STATE_HIGH : JGPI_PORT_STATE read _GetGPI_PORT_STATE_HIGH;// Lcom/zebra/rfid/api3/GPI_PORT_STATE; A: $19
    property GPI_PORT_STATE_LOW : JGPI_PORT_STATE read _GetGPI_PORT_STATE_LOW;  // Lcom/zebra/rfid/api3/GPI_PORT_STATE; A: $19
    property GPI_PORT_STATE_UNKNOWN : JGPI_PORT_STATE read _GetGPI_PORT_STATE_UNKNOWN;// Lcom/zebra/rfid/api3/GPI_PORT_STATE; A: $19
    property ordinal : Integer read _Getordinal;                                // I A: $11
  end;

  [JavaSignature('com/zebra/rfid/api3/GPI_PORT_STATE')]
  JGPI_PORT_STATE = interface(JObject)
    ['{40AAE494-E069-4585-A1FB-AD60CECED5DC}']
    function equals(val : Integer) : boolean; cdecl;                            // (I)Z A: $1
    function getValue : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJGPI_PORT_STATE = class(TJavaGenericImport<JGPI_PORT_STATEClass, JGPI_PORT_STATE>)
  end;

implementation

end.
