//
// Generated by JavaToPas v1.5 20170214 - 172218
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.f;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.g;

type
  Jf = interface;

  JfClass = interface(JObjectClass)
    ['{4471F66A-FD12-4568-93AA-C5837BB79FDA}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : Integer; cdecl;                                            //  A: $1
    function _Getd : Int64; cdecl;                                              //  A: $1
    function _Gete : Int64; cdecl;                                              //  A: $1
    function _Getf : Integer; cdecl;                                            //  A: $1
    function _Getg : Integer; cdecl;                                            //  A: $1
    function _Geth : Jg; cdecl;                                                 //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setd(Value : Int64) ; cdecl;                                     //  A: $1
    procedure _Sete(Value : Int64) ; cdecl;                                     //  A: $1
    procedure _Setf(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setg(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Seth(Value : Jg) ; cdecl;                                        //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : Integer read _Getc write _Setc;                                // I A: $1
    property d : Int64 read _Getd write _Setd;                                  // J A: $1
    property e : Int64 read _Gete write _Sete;                                  // J A: $1
    property f : Integer read _Getf write _Setf;                                // I A: $1
    property g : Integer read _Getg write _Setg;                                // I A: $1
    property h : Jg read _Geth write _Seth;                                     // Lcom/zebra/rfid/api3/g; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/f')]
  Jf = interface(JObject)
    ['{8DB339AA-F3B1-47F2-A7A8-607EC43D1296}']
    function _Geta : Integer; cdecl;                                            //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : Integer; cdecl;                                            //  A: $1
    function _Getd : Int64; cdecl;                                              //  A: $1
    function _Gete : Int64; cdecl;                                              //  A: $1
    function _Getf : Integer; cdecl;                                            //  A: $1
    function _Getg : Integer; cdecl;                                            //  A: $1
    function _Geth : Jg; cdecl;                                                 //  A: $1
    procedure _Seta(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setd(Value : Int64) ; cdecl;                                     //  A: $1
    procedure _Sete(Value : Int64) ; cdecl;                                     //  A: $1
    procedure _Setf(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setg(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Seth(Value : Jg) ; cdecl;                                        //  A: $1
    property a : Integer read _Geta write _Seta;                                // I A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : Integer read _Getc write _Setc;                                // I A: $1
    property d : Int64 read _Getd write _Setd;                                  // J A: $1
    property e : Int64 read _Gete write _Sete;                                  // J A: $1
    property f : Integer read _Getf write _Setf;                                // I A: $1
    property g : Integer read _Getg write _Setg;                                // I A: $1
    property h : Jg read _Geth write _Seth;                                     // Lcom/zebra/rfid/api3/g; A: $1
  end;

  TJf = class(TJavaGenericImport<JfClass, Jf>)
  end;

implementation

end.
