//
// Generated by JavaToPas v1.5 20170214 - 172218
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.d;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.ANTENNA_EVENT_TYPE;

type
  Jd = interface;

  JdClass = interface(JObjectClass)
    ['{7CC304FA-4A00-45C7-8366-3D6B1FBE1F78}']
  end;

  [JavaSignature('com/zebra/rfid/api3/d')]
  Jd = interface(JObject)
    ['{2FF4692A-1032-43C4-B9FD-512AAE327F6F}']
  end;

  TJd = class(TJavaGenericImport<JdClass, Jd>)
  end;

implementation

end.
