//
// Generated by JavaToPas v1.5 20170214 - 172226
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.TransportBT_TransportHandler;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JTransportBT_TransportHandler = interface;

  JTransportBT_TransportHandlerClass = interface(JObjectClass)
    ['{99B5102D-0E2D-40BC-BE6B-89A3004280E9}']
    procedure NotificationFromTransport(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
    procedure dataReceivedFromTransport(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
  end;

  [JavaSignature('com/zebra/rfid/api3/TransportBT_TransportHandler')]
  JTransportBT_TransportHandler = interface(JObject)
    ['{6E6CCB52-21FF-47E0-9082-05A1459D612A}']
    procedure NotificationFromTransport(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
    procedure dataReceivedFromTransport(JStringparam0 : JString) ; cdecl;       // (Ljava/lang/String;)V A: $401
  end;

  TJTransportBT_TransportHandler = class(TJavaGenericImport<JTransportBT_TransportHandlerClass, JTransportBT_TransportHandler>)
  end;

implementation

end.
