//
// Generated by JavaToPas v1.5 20170214 - 172222
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.OperationFailureException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.RFIDResults;

type
  JOperationFailureException = interface;

  JOperationFailureExceptionClass = interface(JObjectClass)
    ['{4B283FF6-21EC-4F51-A86D-8F5EDAA7DFF6}']
    function getResults : JRFIDResults; cdecl;                                  // ()Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function getStatusDescription : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function getTimeStamp : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function getVendorMessage : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/OperationFailureException')]
  JOperationFailureException = interface(JObject)
    ['{0C75F884-611C-4A16-AA1B-365A3147930D}']
    function getResults : JRFIDResults; cdecl;                                  // ()Lcom/zebra/rfid/api3/RFIDResults; A: $1
    function getStatusDescription : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function getTimeStamp : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function getVendorMessage : JString; cdecl;                                 // ()Ljava/lang/String; A: $1
  end;

  TJOperationFailureException = class(TJavaGenericImport<JOperationFailureExceptionClass, JOperationFailureException>)
  end;

implementation

end.
