//
// Generated by JavaToPas v1.5 20170214 - 172220
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.Config;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.Antennas,
  com.zebra.rfid.api3.GPIs,
  com.zebra.rfid.api3.GPOs,
  com.zebra.rfid.api3.ReaderCapabilities,
  com.zebra.rfid.api3.ay,
  java.util.Vector,
  com.zebra.rfid.api3.RADIO_POWER_STATE,
  com.zebra.rfid.api3.DYNAMIC_POWER_OPTIMIZATION,
  com.zebra.rfid.api3.UNIQUE_TAG_REPORT_SETTING,
  com.zebra.rfid.api3.BATCH_MODE,
  com.zebra.rfid.api3.BEEPER_VOLUME,
  com.zebra.rfid.api3.TRACE_LEVEL,
  java.util.logging.Level,
  com.zebra.rfid.api3.TagStorageSettings,
  com.zebra.rfid.api3.StartTrigger,
  com.zebra.rfid.api3.StopTrigger,
  com.zebra.rfid.api3.RegulatoryConfig,
  com.zebra.rfid.api3.RegionInfo;

type
  JConfig = interface;

  JConfigClass = interface(JObjectClass)
    ['{C1046C7C-8463-4EB2-8174-E54BDBA2A664}']
    function _GetAntennas : JAntennas; cdecl;                                   //  A: $1
    function _GetGPI : JGPIs; cdecl;                                            //  A: $1
    function _GetGPO : JGPOs; cdecl;                                            //  A: $1
    function getBatchModeConfig : JBATCH_MODE; cdecl;                           // ()Lcom/zebra/rfid/api3/BATCH_MODE; A: $1
    function getBeeperVolume : JBEEPER_VOLUME; cdecl;                           // ()Lcom/zebra/rfid/api3/BEEPER_VOLUME; A: $1
    function getDPOState : JDYNAMIC_POWER_OPTIMIZATION; cdecl;                  // ()Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION; A: $1
    function getDutyCycleIndex : SmallInt; cdecl;                               // ()S A: $1
    function getRadioPowerState : JRADIO_POWER_STATE; cdecl;                    // ()Lcom/zebra/rfid/api3/RADIO_POWER_STATE; A: $1
    function getRegionInfo(regionInfo : JRegionInfo) : JRegionInfo; cdecl;      // (Lcom/zebra/rfid/api3/RegionInfo;)Lcom/zebra/rfid/api3/RegionInfo; A: $1
    function getRegulatoryConfig : JRegulatoryConfig; cdecl;                    // ()Lcom/zebra/rfid/api3/RegulatoryConfig; A: $1
    function getStartTrigger : JStartTrigger; cdecl;                            // ()Lcom/zebra/rfid/api3/StartTrigger; A: $1
    function getStopTrigger : JStopTrigger; cdecl;                              // ()Lcom/zebra/rfid/api3/StopTrigger; A: $1
    function getTagStorageSettings : JTagStorageSettings; cdecl;                // ()Lcom/zebra/rfid/api3/TagStorageSettings; A: $1
    function getTraceLevel : TJavaArray<JTRACE_LEVEL>; cdecl;                   // ()[Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $1
    function getUniqueTagReport : JUNIQUE_TAG_REPORT_SETTING; cdecl;            // ()Lcom/zebra/rfid/api3/UNIQUE_TAG_REPORT_SETTING; A: $1
    function setUniqueTagReport(uniqueTagReport : boolean) : boolean; cdecl;    // (Z)Z A: $1
    procedure _SetAntennas(Value : JAntennas) ; cdecl;                          //  A: $1
    procedure _SetGPI(Value : JGPIs) ; cdecl;                                   //  A: $1
    procedure _SetGPO(Value : JGPOs) ; cdecl;                                   //  A: $1
    procedure getDeviceStatus(battery : boolean; power : boolean; temperature : boolean) ; cdecl;// (ZZZ)V A: $1
    procedure getDeviceVersionInfo(deviceVersion : JHashMap) ; cdecl;           // (Ljava/util/HashMap;)V A: $1
    procedure resetFactoryDefaults ; cdecl;                                     // ()V A: $1
    procedure saveConfig ; cdecl;                                               // ()V A: $1
    procedure setBatchMode(batchMode : JBATCH_MODE) ; cdecl;                    // (Lcom/zebra/rfid/api3/BATCH_MODE;)V A: $1
    procedure setBeeperVolume(beeperVolume : JBEEPER_VOLUME) ; cdecl;           // (Lcom/zebra/rfid/api3/BEEPER_VOLUME;)V A: $1
    procedure setDPOState(dpoState : JDYNAMIC_POWER_OPTIMIZATION) ; cdecl;      // (Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)V A: $1
    procedure setDutyCycleIndex(dutyCycleIndex : SmallInt) ; cdecl;             // (S)V A: $1
    procedure setLogLevel(logLevel : JLevel) ; cdecl;                           // (Ljava/util/logging/Level;)V A: $1
    procedure setRadioPowerState(radioPowerState : JRADIO_POWER_STATE) ; cdecl; // (Lcom/zebra/rfid/api3/RADIO_POWER_STATE;)V A: $1
    procedure setRegulatoryConfig(regulatoryConfig : JRegulatoryConfig) ; cdecl;// (Lcom/zebra/rfid/api3/RegulatoryConfig;)V A: $1
    procedure setStartTrigger(startTrigger : JStartTrigger) ; cdecl;            // (Lcom/zebra/rfid/api3/StartTrigger;)V A: $1
    procedure setStopTrigger(stopTrigger : JStopTrigger) ; cdecl;               // (Lcom/zebra/rfid/api3/StopTrigger;)V A: $1
    procedure setTagStorageSettings(tagStorageSettings : JTagStorageSettings) ; cdecl;// (Lcom/zebra/rfid/api3/TagStorageSettings;)V A: $1
    procedure setTraceLevel(arrTraceLevel : TJavaArray<JTRACE_LEVEL>) ; cdecl; overload;// ([Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setTraceLevel(traceLevel : JTRACE_LEVEL) ; cdecl; overload;       // (Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    property Antennas : JAntennas read _GetAntennas write _SetAntennas;         // Lcom/zebra/rfid/api3/Antennas; A: $1
    property GPI : JGPIs read _GetGPI write _SetGPI;                            // Lcom/zebra/rfid/api3/GPIs; A: $1
    property GPO : JGPOs read _GetGPO write _SetGPO;                            // Lcom/zebra/rfid/api3/GPOs; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/Config')]
  JConfig = interface(JObject)
    ['{DCC9F0A5-23D7-4B8A-93E3-9A6BBCAD4FD3}']
    function _GetAntennas : JAntennas; cdecl;                                   //  A: $1
    function _GetGPI : JGPIs; cdecl;                                            //  A: $1
    function _GetGPO : JGPOs; cdecl;                                            //  A: $1
    function getBatchModeConfig : JBATCH_MODE; cdecl;                           // ()Lcom/zebra/rfid/api3/BATCH_MODE; A: $1
    function getBeeperVolume : JBEEPER_VOLUME; cdecl;                           // ()Lcom/zebra/rfid/api3/BEEPER_VOLUME; A: $1
    function getDPOState : JDYNAMIC_POWER_OPTIMIZATION; cdecl;                  // ()Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION; A: $1
    function getDutyCycleIndex : SmallInt; cdecl;                               // ()S A: $1
    function getRadioPowerState : JRADIO_POWER_STATE; cdecl;                    // ()Lcom/zebra/rfid/api3/RADIO_POWER_STATE; A: $1
    function getRegionInfo(regionInfo : JRegionInfo) : JRegionInfo; cdecl;      // (Lcom/zebra/rfid/api3/RegionInfo;)Lcom/zebra/rfid/api3/RegionInfo; A: $1
    function getRegulatoryConfig : JRegulatoryConfig; cdecl;                    // ()Lcom/zebra/rfid/api3/RegulatoryConfig; A: $1
    function getStartTrigger : JStartTrigger; cdecl;                            // ()Lcom/zebra/rfid/api3/StartTrigger; A: $1
    function getStopTrigger : JStopTrigger; cdecl;                              // ()Lcom/zebra/rfid/api3/StopTrigger; A: $1
    function getTagStorageSettings : JTagStorageSettings; cdecl;                // ()Lcom/zebra/rfid/api3/TagStorageSettings; A: $1
    function getTraceLevel : TJavaArray<JTRACE_LEVEL>; cdecl;                   // ()[Lcom/zebra/rfid/api3/TRACE_LEVEL; A: $1
    function getUniqueTagReport : JUNIQUE_TAG_REPORT_SETTING; cdecl;            // ()Lcom/zebra/rfid/api3/UNIQUE_TAG_REPORT_SETTING; A: $1
    function setUniqueTagReport(uniqueTagReport : boolean) : boolean; cdecl;    // (Z)Z A: $1
    procedure _SetAntennas(Value : JAntennas) ; cdecl;                          //  A: $1
    procedure _SetGPI(Value : JGPIs) ; cdecl;                                   //  A: $1
    procedure _SetGPO(Value : JGPOs) ; cdecl;                                   //  A: $1
    procedure getDeviceStatus(battery : boolean; power : boolean; temperature : boolean) ; cdecl;// (ZZZ)V A: $1
    procedure getDeviceVersionInfo(deviceVersion : JHashMap) ; cdecl;           // (Ljava/util/HashMap;)V A: $1
    procedure resetFactoryDefaults ; cdecl;                                     // ()V A: $1
    procedure saveConfig ; cdecl;                                               // ()V A: $1
    procedure setBatchMode(batchMode : JBATCH_MODE) ; cdecl;                    // (Lcom/zebra/rfid/api3/BATCH_MODE;)V A: $1
    procedure setBeeperVolume(beeperVolume : JBEEPER_VOLUME) ; cdecl;           // (Lcom/zebra/rfid/api3/BEEPER_VOLUME;)V A: $1
    procedure setDPOState(dpoState : JDYNAMIC_POWER_OPTIMIZATION) ; cdecl;      // (Lcom/zebra/rfid/api3/DYNAMIC_POWER_OPTIMIZATION;)V A: $1
    procedure setDutyCycleIndex(dutyCycleIndex : SmallInt) ; cdecl;             // (S)V A: $1
    procedure setLogLevel(logLevel : JLevel) ; cdecl;                           // (Ljava/util/logging/Level;)V A: $1
    procedure setRadioPowerState(radioPowerState : JRADIO_POWER_STATE) ; cdecl; // (Lcom/zebra/rfid/api3/RADIO_POWER_STATE;)V A: $1
    procedure setRegulatoryConfig(regulatoryConfig : JRegulatoryConfig) ; cdecl;// (Lcom/zebra/rfid/api3/RegulatoryConfig;)V A: $1
    procedure setStartTrigger(startTrigger : JStartTrigger) ; cdecl;            // (Lcom/zebra/rfid/api3/StartTrigger;)V A: $1
    procedure setStopTrigger(stopTrigger : JStopTrigger) ; cdecl;               // (Lcom/zebra/rfid/api3/StopTrigger;)V A: $1
    procedure setTagStorageSettings(tagStorageSettings : JTagStorageSettings) ; cdecl;// (Lcom/zebra/rfid/api3/TagStorageSettings;)V A: $1
    procedure setTraceLevel(arrTraceLevel : TJavaArray<JTRACE_LEVEL>) ; cdecl; overload;// ([Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    procedure setTraceLevel(traceLevel : JTRACE_LEVEL) ; cdecl; overload;       // (Lcom/zebra/rfid/api3/TRACE_LEVEL;)V A: $1
    property Antennas : JAntennas read _GetAntennas write _SetAntennas;         // Lcom/zebra/rfid/api3/Antennas; A: $1
    property GPI : JGPIs read _GetGPI write _SetGPI;                            // Lcom/zebra/rfid/api3/GPIs; A: $1
    property GPO : JGPOs read _GetGPO write _SetGPO;                            // Lcom/zebra/rfid/api3/GPOs; A: $1
  end;

  TJConfig = class(TJavaGenericImport<JConfigClass, JConfig>)
  end;

const
  TJConfiga = 10;

implementation

end.
