//
// Generated by JavaToPas v1.5 20170214 - 172223
////////////////////////////////////////////////////////////////////////////////
unit com.zebra.rfid.api3.bk;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.zebra.rfid.api3.READER_ID_TYPE;

type
  Jbk = interface;

  JbkClass = interface(JObjectClass)
    ['{7A2C722F-94FF-47D9-929F-B1B308527FAE}']
    function _Geta : JREADER_ID_TYPE; cdecl;                                    //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : JREADER_ID_TYPE) ; cdecl;                           //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : JString) ; cdecl;                                   //  A: $1
    property a : JREADER_ID_TYPE read _Geta write _Seta;                        // Lcom/zebra/rfid/api3/READER_ID_TYPE; A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : JString read _Getc write _Setc;                                // Ljava/lang/String; A: $1
  end;

  [JavaSignature('com/zebra/rfid/api3/bk')]
  Jbk = interface(JObject)
    ['{35A3DFD2-A66F-4EC6-B446-CC512046425D}']
    function _Geta : JREADER_ID_TYPE; cdecl;                                    //  A: $1
    function _Getb : Integer; cdecl;                                            //  A: $1
    function _Getc : JString; cdecl;                                            //  A: $1
    procedure _Seta(Value : JREADER_ID_TYPE) ; cdecl;                           //  A: $1
    procedure _Setb(Value : Integer) ; cdecl;                                   //  A: $1
    procedure _Setc(Value : JString) ; cdecl;                                   //  A: $1
    property a : JREADER_ID_TYPE read _Geta write _Seta;                        // Lcom/zebra/rfid/api3/READER_ID_TYPE; A: $1
    property b : Integer read _Getb write _Setb;                                // I A: $1
    property c : JString read _Getc write _Setc;                                // Ljava/lang/String; A: $1
  end;

  TJbk = class(TJavaGenericImport<JbkClass, Jbk>)
  end;

implementation

end.
